version: "3.7"

services:
  # BACK
  english-back:
    image: english-back
    restart: always
    ports:
      - 4000:4000
  # FRONT
  english-front:
    image: english-front
    restart: always
    ports:
      - 80:80
    environment:
      REACT_APP_PUBLIC_URL: "http://localhost:4000"
