version: "3.7"

services:
  # API
  english-api:
    image: english-api
    restart: always
    ports:
      - 4000:4000
    environment:
      COLLECTOR_URL: http://18.212.213.136:8585/collect
  # WEB
  english-web:
    image: english-web
    restart: always
    ports:
      - 80:80
