import { TDictionaryItem } from "../types"
export const a_arr: TDictionaryItem[] = [
  { key: "abandon", value: "оставить, забросить" },
  { key: "abate", value: "уменьшаться, ослабевать" },
  { key: "abduct", value: "похищать" },
  { key: "abide", value: "смириться, выносить" },
  { key: "able", value: "способный, могущий" },
  { key: "abnormal", value: "ненормальный, аномальный" },
  { key: "aboard", value: "на борту" },
  { key: "abolish", value: "упразднять" },
  { key: "abort", value: "прерывать" },
  { key: "abound", value: "изобиловать" },
  { key: "about", value: "примерно" },
  { key: "abroad", value: "за границу" },
  { key: "abrupt", value: "крутой, резкий" },
  { key: "absent", value: "отсутствующий" },
  { key: "absorb", value: "впитывать, поглощать" },
  { key: "abundant", value: "обильный" },
  {
    key: "abuse",
    value: ["оскорблять, бранить, брань", "злоупотреблять", "насилие, домогательство"],
  },
  { key: "accelerate", value: "ускорять" },
  { key: "accept", value: "принять" },
  { key: "access", value: "доступ" },
  { key: "accessory", value: "принадлежность, аксессуар" },
  { key: "accident", value: ["случайность", "происшествие, напр. ДТП"] },
  { key: "acclaim", value: "приветствовать, аплодировать" },
  { key: "accommodate", value: "размещать, вмещать" },
  { key: "accompany", value: "сопровождать" },
  { key: "accomplish", value: "выполнить, завершить" },
  { key: "accord", value: "согласие" },
  { key: "according to", value: "в соответствии" },
  { key: "account", value: ["счёт (в банке)", "отчёт"] },
  { key: "account for", value: "объяснить (произошедшее)" },
  { key: "accurate", value: "точный" },
  { key: "accuse", value: "обвинять" },
  { key: "accustom", value: "приучить" },
  { key: "ache", value: "боль, болеть" },
  { key: "achieve", value: "достигать" },
  { key: "acid", value: "кислота" },
  { key: "acknowledge", value: "признавать, подтверждать" },
  { key: "acquaint", value: "знакомить" },
  { key: "acquire", value: "обретать" },
  { key: "acquit", value: "оправдать (в суде)" },
  { key: "across", value: "за, через" },
  { key: "act", value: "действовать" },
  { key: "act on", value: "действовать в соответствии" },
  { key: "acute", value: "острый" },
  { key: "adamant", value: "непреклонный" },
  { key: "add to", value: "увеличивать" },
  { key: "add up", value: "сходиться (об информации)" },
  { key: "addict", value: "наркоман, привыкать" },
  { key: "addition", value: "добавление, сложение" },
  { key: "adhere", value: "придерживаться" },
  { key: "adjacent", value: "смежный, прилегающий" },
  { key: "adjective", value: "прилагательное" },
  { key: "adjust", value: "настраивать, поправлять и т.д." },
  { key: "admire", value: "восхищаться" },
  { key: "admit", value: "признавать, допускать" },
  { key: "adolescent", value: "подросток, подростковый" },
  { key: "adopt", value: ["принимать, перенимать", "усыновить или взять (животное)"] },
  { key: "adore", value: "обожать" },
  { key: "adorn", value: "украшать" },
  { key: "adult", value: "взрослый" },
  { key: "adultery", value: "прелюбодеяние, неверность" },
  { key: "advance", value: "продвигаться, продвижение" },
  { key: "advantage", value: "преимущество" },
  { key: "adventure", value: "приключение" },
  { key: "adverb", value: "наречие" },
  { key: "adversary", value: "противник, соперник" },
  { key: "adverse", value: "неблагоприятный" },
  { key: "advertise", value: "рекламировать" },
  { key: "advice", value: "совет (неисчисл!)" },
  { key: "advise", value: "советовать" },
  { key: "advocate", value: "защищать, отстаивать" },
  { key: "aerial", value: ["воздушный", "антенна"] },
  { key: "affair", value: ["дело, занятие", "роман, любовная история"] },
  { key: "affect", value: "воздействовать" },
  { key: "affection", value: "привязанность, влечение" },
  { key: "affiliate", value: "филиал, отделение, мл. партнёр" },
  { key: "affirm", value: "утверждать, подтверждать" },
  { key: "afflict", value: "поражать, вредить" },
  { key: "affluent", value: "обеспеченный, состоятельный" },
  { key: "afford", value: "позволить себе" },
  { key: "afraid", value: "напуганный" },
  { key: "after all", value: "всё-таки, в конце концов" },
  { key: "aftermath", value: "последствие, результат" },
  { key: "age", value: ["век, эпоха", "возраст"] },
  { key: "agenda", value: "повестка дня" },
  { key: "aggravate", value: "обострять" },
  { key: "aggregate", value: "совокупный" },
  { key: "agile", value: "проворный, гибкий" },
  { key: "agitate", value: "волновать" },
  { key: "agree", value: "соглашаться" },
  { key: "agreement", value: "соглашение, договор" },
  { key: "agriculture", value: "сельское хозяйство" },
  { key: "ahead", value: "вперёд, впереди" },
  { key: "aid", value: "помощь, помогать" },
  { key: "ailment", value: "недомогание, болезнь" },
  { key: "aim", value: "цель" },
  { key: "air", value: "вид, впечатление" },
  { key: "airborne", value: "находящийся в воздухе" },
  { key: "aircraft", value: "самолёт, авиация" },
  { key: "airline", value: "авиалиния" },
  { key: "aisle", value: "проход" },
  { key: "akin", value: "похожий" },
  { key: "alarm", value: "тревога, сигнализация" },
  { key: "alas", value: "увы" },
  { key: "albeit", value: "хотя" },
  { key: "alert", value: "тревога, бдительный" },
  { key: "alien", value: "чужак, пришелец, иммигрант" },
  { key: "alienate", value: "отчуждать, отдалять, отвергать" },
  { key: "align", value: "выравнивать, выстраивать" },
  { key: "alike", value: "подобно" },
  { key: "alive", value: "живой" },
  { key: "all along", value: "всё время" },
  { key: "allege", value: "утверждать, приписывать" },
  { key: "allegiance", value: "верность" },
  { key: "allocate", value: "распределять (ресурсы)" },
  { key: "allot", value: "выделять, отводить" },
  { key: "allow", value: "разрешать" },
  { key: "allow for", value: "выделять, рассчитывать" },
  { key: "allowance", value: "выплата, пособие" },
  { key: "allude", value: "намекать, указывать" },
  { key: "allure", value: "очарование, очаровывать" },
  { key: "ally", value: "союзник" },
  { key: "almost", value: "почти" },
  { key: "alone", value: "в одиночестве" },
  { key: "alongside", value: "рядом" },
  { key: "aloud", value: "вслух" },
  { key: "alter", value: "изменять" },
  { key: "alternate", value: "чередовать, чередующийся" },
  { key: "although", value: "хотя и" },
  { key: "altitude", value: "высота" },
  { key: "altogether", value: "в целом" },
  { key: "amateur", value: "любитель, любительский" },
  { key: "amaze", value: "поражать, изумлять" },
  { key: "ambassador", value: "посол" },
  { key: "amber", value: "янтарь" },
  { key: "ambiguous", value: "двусмысленный, неоднозначный" },
  { key: "ambulance", value: "скорая помощь" },
  { key: "ambush", value: "засада" },
  { key: "amend", value: "исправить, улучшить" },
  { key: "amenity", value: "удобство, обустройство" },
  { key: "amid (amidst)", value: "среди" },
  { key: "ammunition", value: "боеприпасы" },
  { key: "amount", value: "количество (неисчисл.)" },
  { key: "ample", value: "обильный, широкий" },
  { key: "amplify", value: "усиливать" },
  { key: "amuse", value: "развлечь, порадовать" },
  { key: "ancestor", value: "предок" },
  { key: "anchor", value: "якорь, закреплять" },
  { key: "ancient", value: "древний" },
  { key: "anew", value: "заново" },
  { key: "anger", value: "гнев" },
  { key: "angle", value: "угол, угловой" },
  { key: "angry", value: "злой" },
  { key: "anguish", value: "мука, страдание" },
  { key: "animate", value: "живой, одушевлённый, оживлять" },
  { key: "ankle", value: "лодыжка, щиколотка" },
  { key: "anniversary", value: "годовщина" },
  { key: "announce", value: "объявлять" },
  { key: "annoy", value: "раздражать, надоедать" },
  { key: "annual", value: "ежегодный" },
  { key: "ant", value: "муравей" },
  { key: "anthem", value: "гимн" },
  { key: "anticipate", value: "ожидать" },
  { key: "antique", value: "старинный" },
  { key: "anxiety", value: "беспокойство, тревога" },
  { key: "anxious", value: "озабоченный, встревоженный" },
  { key: "anymore", value: "больше не" },
  { key: "anytime", value: "в любой момент" },
  { key: "anyway", value: "в любом случае" },
  { key: "anywhere", value: "где угодно, куда угодно" },
  { key: "apart", value: "отдельно, врозь" },
  { key: "apart from", value: "помимо" },
  { key: "apartment", value: "квартира" },
  { key: "ape", value: "обезьяна (крупная)" },
  { key: "apiece", value: "каждый, за штуку" },
  { key: "apology", value: "извинение(я)" },
  { key: "appal", value: "потрясать, ужасать" },
  { key: "apparent", value: "явный, видимый" },
  { key: "appeal", value: "обращаться, взывать" },
  { key: "appear", value: ["появиться", "казаться"] },
  { key: "applause", value: "аплодисменты" },
  { key: "appliance", value: "прибор, приспособление" },
  { key: "apply", value: ["применять, применяться", "обращаться (с заявлением)"] },
  { key: "appoint", value: "назначать, утверждать" },
  { key: "appraise", value: "оценивать" },
  { key: "appreciate", value: "ценить" },
  { key: "apprentice", value: "ученик, стажёр" },
  { key: "approach", value: "приближаться, подходить" },
  { key: "appropriate", value: ["присвоить", "подходящий, присущий"] },
  { key: "approve", value: "утвердить, одобрить (офиц.)" },
  { key: "approve of", value: "одобрять (субъективно)" },
  { key: "approximate", value: "приблизительный" },
  { key: "apron", value: "фартук, передник" },
  { key: "apt", value: "склонный, способный" },
  { key: "aquatic", value: "водный" },
  { key: "arbitrary", value: "произвольный" },
  { key: "arc", value: "дуга" },
  { key: "arch", value: "арка, изгибать" },
  { key: "archive", value: "архив" },
  { key: "area", value: "область, участок" },
  { key: "argue", value: "спорить, доказывать" },
  { key: "arise (arose, arisen)", value: "возникать, происходить" },
  { key: "arm", value: "рука" },
  { key: "armor (armour)", value: "броня, доспехи" },
  { key: "arms", value: "оружие" },
  { key: "arouse", value: "вызывать, пробуждать" },
  { key: "arrange", value: "организовать, уладить и т.д." },
  { key: "array", value: "ряд, порядок, строй" },
  { key: "arrest", value: "задерживать, тормозить" },
  { key: "arrive", value: "прибывать" },
  { key: "arrogant", value: "высокомерный" },
  { key: "arrow", value: "стрела, стрелка" },
  { key: "arson", value: "поджог" },
  { key: "article", value: ["статья", "вещь, изделие"] },
  { key: "artificial", value: "искусственный" },
  { key: "as though", value: "как будто" },
  { key: "as well", value: "также" },
  { key: "as well as", value: "так же как и" },
  { key: "ascend", value: "восходить" },
  { key: "ascertain", value: "выяснить, установить" },
  { key: "ash", value: "пепел, зола" },
  { key: "ashamed", value: "пристыженный" },
  { key: "ashtray", value: "пепельница" },
  { key: "aside", value: "в стороне, в сторону" },
  { key: "aside from", value: "кроме" },
  { key: "ask around", value: "поспрашивать" },
  { key: "ask out", value: "пригласить сходить" },
  { key: "asleep", value: "спящий" },
  { key: "aspire", value: "стремиться" },
  { key: "ass", value: "жопа" },
  { key: "assassin", value: "убийца" },
  { key: "assault", value: "нападение, нападать" },
  { key: "assemble", value: "собирать" },
  { key: "assert", value: "утверждать, отстаивать" },
  { key: "assess", value: "оценить" },
  { key: "asset", value: "актив, имущество" },
  { key: "assign", value: "назначать, присваивать" },
  { key: "assimilate", value: "усваивать" },
  { key: "assist", value: "помогать" },
  { key: "associate", value: "общаться, связываться" },
  { key: "assume", value: ["принимать на себя", "предпогалать"] },
  { key: "assure", value: "уверять" },
  { key: "astonish", value: "изумлять" },
  { key: "astound", value: "изумлять" },
  { key: "asylum", value: "убежище" },
  { key: "at all", value: "совсем" },
  { key: "at first", value: "сначала" },
  { key: "at last", value: "наконец" },
  { key: "at least", value: "по крайней мере" },
  { key: "at odds with", value: "в противоречии, в конфликте" },
  { key: "at once", value: "сразу" },
  { key: "at the moment", value: "сейчас" },
  { key: "atop", value: "наверху" },
  { key: "atrocity", value: "зверство, злодеяние" },
  { key: "attach", value: "прикрепить, привязать" },
  { key: "attack", value: "нападать, нападение" },
  { key: "attain", value: "достигать" },
  { key: "attempt", value: "попытка, пытаться" },
  { key: "attend", value: "уделить внимание, посетить" },
  { key: "attic", value: "чердак" },
  { key: "attitude", value: "отношение" },
  { key: "attorney", value: "адвокат, прокурор, поверенный" },
  { key: "attract", value: "привлекать, притягивать" },
  { key: "attribute", value: "приписывать, относить" },
  { key: "audible", value: "слышимый" },
  { key: "audience", value: "аудитория (люди)" },
  { key: "augment", value: "увеличить, нарастить" },
  { key: "aunt", value: "тётя" },
  { key: "authorities", value: "органы власти" },
  { key: "authority", value: "власть" },
  { key: "authorize", value: "дать полномочия, поручение" },
  { key: "available", value: "доступный, в наличии" },
  { key: "avalanche", value: "лавина" },
  { key: "average", value: "средний" },
  { key: "avert", value: "предотвращать, отводить" },
  { key: "avid", value: "заядлый, рьяный, алчный" },
  { key: "avoid", value: "избегать" },
  { key: "await", value: "ожидать" },
  { key: "awake", value: "проснуться, бодрствующий" },
  { key: "award", value: "награда, премия, присуждать" },
  { key: "aware", value: "осведомлённый" },
  { key: "awe", value: "трепет, благоговение" },
  { key: "awesome", value: "здорово, классно" },
  { key: "awful", value: "ужасный" },
  { key: "awhile", value: "какое-то время" },
  { key: "awkward", value: "неуклюжий" },
  { key: "axe (ax)", value: "топор" },
  { key: "axis", value: "ось" },
]
