import { TDictionaryItem } from "../types"
export const b_arr: TDictionaryItem[] = [
  { key: "bachelor", value: ["бакалавр", "холостяк"] },
  { key: "back down", value: "отступить, отказаться" },
  { key: "back then", value: "тогда" },
  { key: "back up", value: "поддержать, прикрыть" },
  { key: "backbone", value: "хребет" },
  { key: "backdrop", value: "фон" },
  { key: "background", value: ["происхождение, предыстория и т.д.", "фон"] },
  { key: "backpack", value: "рюкзак" },
  { key: "badge", value: "значок" },
  { key: "baffled", value: "в неодумении, в тупике" },
  { key: "bag", value: "сумка, мешок" },
  { key: "bail", value: "залог" },
  { key: "bait", value: "приманка" },
  { key: "bake", value: "печь (выпекать)" },
  { key: "bald", value: "лысый, плешивый" },
  { key: "bale", value: "тюк" },
  { key: "balloon", value: "воздушный шар" },
  { key: "ballot", value: "госолование, бюллетень" },
  { key: "ban", value: "запрещать" },
  { key: "band", value: "ансамбль" },
  { key: "bandage", value: "повязка" },
  { key: "bang", value: "удар, взрыв" },
  { key: "banish", value: "отгонять" },
  { key: "bank", value: "берег (реки, озера)" },
  { key: "bank on", value: "надеяться, полагаться" },
  { key: "bankrupt", value: "банкрот, неплатежеспособный" },
  { key: "banner", value: "знамя, транспарант" },
  { key: "baptize", value: "крестить" },
  { key: "bar", value: ["пластина, брусок, прут и т. д.", "загораживать"] },
  { key: "barb", value: "шип, зазубрина" },
  { key: "barber", value: "парикмахер" },
  { key: "bare", value: "голый" },
  { key: "barefoot", value: "босиком" },
  { key: "barely", value: "едва, лишь только" },
  { key: "bargain", value: "сделка, торговаться" },
  { key: "bark", value: ["кора", "лаять"] },
  { key: "barn", value: "сарай" },
  { key: "barrel", value: "бочка" },
  { key: "barren", value: "бесплодный" },
  { key: "bartender", value: "бармен" },
  { key: "base", value: "основа, основывать" },
  { key: "basement", value: "подвал" },
  { key: "bash", value: "колотить" },
  { key: "basket", value: "корзина" },
  { key: "bastard", value: "ублюдок" },
  { key: "bat", value: ["бита", "летучая мышь"] },
  { key: "batch", value: "партия, серия, группа" },
  { key: "bath", value: "ванна" },
  { key: "bathe", value: "купаться, купать" },
  { key: "batter", value: "паста, тесто, взбивать" },
  { key: "battle", value: "битва" },
  { key: "bay", value: "залив" },
  { key: "be after", value: "иметь целью" },
  { key: "be back", value: "возвращаться" },
  { key: "be in", value: "участвовать" },
  { key: "be into", value: "любить, увлекаться" },
  { key: "be keen to", value: "желать, стремиться" },
  { key: "be late", value: "опоздать" },
  { key: "be off", value: "отсутствовать" },
  { key: "be on fire", value: "гореть" },
  { key: "be over", value: "закончиться" },
  { key: "be up to", value: "замышлять что-то" },
  { key: "bead", value: "шарик, бусинка" },
  { key: "beak", value: "клюв" },
  { key: "beam", value: ["балка, перекладина", "луч"] },
  { key: "bean", value: "боб" },
  { key: "bear (bore, born)", value: ["рожать", "нести, втч перен."] },
  { key: "beard", value: "борода" },
  { key: "beast", value: "зверь, животное, скот" },
  { key: "beat (beat, beaten)", value: ["победить", "бить"] },
  { key: "beat up", value: "побить" },
  { key: "beauty", value: "красота или красавица" },
  { key: "beaver", value: "бобр" },
  { key: "beckon", value: "манить" },
  { key: "become of", value: "случиться с к-л впоследствии" },
  { key: "beef", value: "говядина" },
  { key: "beep", value: "гудок, гудеть, пищать" },
  { key: "beetle", value: "жук" },
  { key: "beforehand", value: "заранее" },
  { key: "beg", value: "просить" },
  { key: "behave", value: "вести себя" },
  { key: "behavior", value: "поведение" },
  { key: "behold", value: "созерцать, видеть" },
  { key: "beige", value: "бежевый" },
  { key: "belief", value: "убеждение, вера" },
  { key: "bell", value: "колокол, колокольчик" },
  { key: "bellow", value: "реветь, рёв" },
  { key: "belly", value: "живот" },
  { key: "belong to", value: "принадлежать" },
  { key: "beloved", value: "любимый" },
  { key: "below", value: "ниже, под" },
  { key: "belt", value: "пояс" },
  { key: "bench", value: "скамейка" },
  { key: "bend (bent, bent)", value: "изгибать, изгиб" },
  { key: "bend down", value: "наклониться" },
  { key: "beneath", value: "ниже, под" },
  { key: "benefit", value: "польза, создавать пользу" },
  { key: "benevolent", value: "благожелательный" },
  { key: "berry", value: "ягода" },
  { key: "berth", value: "койка, место, полка в поезде" },
  { key: "beside", value: "рядом" },
  { key: "besides", value: "кроме" },
  { key: "bestow", value: "даровать" },
  { key: "bet", value: "ставка, пари, держать пари" },
  { key: "betray", value: "предавать" },
  { key: "beverage", value: "напиток" },
  { key: "beware", value: "остерегаться" },
  { key: "bewilder", value: "смущать, сбивать с толку" },
  { key: "beyond", value: "вне, свыше" },
  { key: "bias", value: "склонность, предвзятость" },
  { key: "bicycle", value: "велосипед" },
  { key: "bid", value: "заявка, предложение цены" },
  { key: "bigot", value: "фанатик" },
  { key: "bill", value: ["счёт (к оплате)", "банкнота"] },
  { key: "billboard", value: "рекламный щит" },
  { key: "billion", value: "миллиард" },
  { key: "bin", value: "ящик, ведро, ларь" },
  { key: "bind (bound, bound)", value: "связывать" },
  { key: "binge", value: "кутёж, загул, пьянка" },
  { key: "birth", value: "рождение" },
  { key: "bishop", value: "епископ" },
  { key: "bitch", value: "сука" },
  { key: "bite (bit, bitten)", value: "кусать, укус" },
  { key: "bitter", value: "горький" },
  { key: "bizarre", value: "странный, причудливый" },
  { key: "black out", value: "обесточить" },
  { key: "blackmail", value: "шантажировать" },
  { key: "blade", value: "лезвие" },
  { key: "blame", value: "винить" },
  { key: "bland", value: "пресный, мягкий" },
  { key: "blank", value: "пустой, чистый" },
  { key: "blanket", value: "одеяло, покрывало" },
  { key: "blast", value: ["дуновение, порыв", "взрыв, взрывать"] },
  { key: "blatant", value: "явный, вопиющий" },
  { key: "blaze", value: "полыхать, пламя" },
  { key: "bleach", value: "отбелить, обесцветить" },
  { key: "bleak", value: "мрачный" },
  { key: "bleed (bled, bled)", value: "кровоточить" },
  { key: "blend", value: "смешивать" },
  { key: "bless", value: "благословлять" },
  { key: "blind", value: "слепой" },
  { key: "blink", value: "мерцать, мигать" },
  { key: "bliss", value: "блаженство" },
  { key: "blizzard", value: "метель, буран" },
  { key: "bloat", value: "раздуваться" },
  { key: "block", value: ["кусок, глыба и т. д.", "квартал"] },
  { key: "block out", value: "блокировать, не пускать" },
  { key: "block up", value: "забиться (о канале)" },
  { key: "blonde", value: "блондинка" },
  { key: "bloom", value: "расцвет, расцветать" },
  { key: "blossom", value: "цвести, цвет" },
  { key: "blouse", value: "блузка" },
  { key: "blow (blew blown)", value: ["дуть", "удар"] },
  { key: "blow ", value: "задуть (свечу)" },
  { key: "blow over", value: "пройти, утихнуть" },
  { key: "blow up", value: ["взорвать", "накачивать, надувать"] },
  { key: "bluff", value: "блеф" },
  { key: "blunt", value: "тупой, притуплять" },
  { key: "blur", value: "размывать, смазывать" },
  { key: "blush", value: "румянец, краснеть" },
  { key: "board", value: ["совет, коллегия", "доска", "борт, подниматься на борт"] },
  { key: "boast", value: "хвастать, хвастовство" },
  { key: "boat", value: "лодка, судно" },
  { key: "bog", value: "болото, трясина" },
  { key: "boil", value: "кипеть, кипятить, варить" },
  { key: "bold", value: "смелый, дерзкий, безрассудный" },
  { key: "bolster", value: "укреплять, поддерживать" },
  { key: "bond", value: ["связь, узы, соединение", "обязательство, облигация"] },
  { key: "bone", value: "кость" },
  { key: "bonfire", value: "костер" },
  { key: "boobs", value: "титьки" },
  { key: "book", value: "купить, забронировать" },
  { key: "boom", value: "заграждение, пояс" },
  { key: "boost", value: "повышать, усиливать" },
  { key: "boot", value: "сапог, ботинок" },
  { key: "booth", value: "будка, кабина" },
  { key: "booze", value: "выпивка" },
  { key: "border", value: "граница, край" },
  { key: "bore", value: "надоедать" },
  { key: "borough", value: "район, место" },
  { key: "borrow", value: "брать взаймы" },
  { key: "both", value: "оба" },
  { key: "bother", value: "беспокоить" },
  { key: "bottom", value: "дно" },
  { key: "boulder", value: "валун" },
  { key: "bounce", value: "отскакивать, прыгать" },
  { key: "bound", value: "обязан" },
  { key: "boundary", value: "граница, черта" },
  { key: "bounds", value: "границы, рамки (перен.)" },
  { key: "bounty", value: "вознаграждение" },
  { key: "bout", value: ["всплеск, приступ", "бой, поединок"] },
  { key: "bow", value: ["бант, бабочка", "лук", "поклон, наклоняться"] },
  { key: "bow out", value: "откланяться, уйти" },
  { key: "bowel", value: "кишка" },
  { key: "bowl", value: "миска" },
  { key: "brace", value: "скоба, распорка, скрепа" },
  { key: "bracket", value: "скобка" },
  { key: "brag", value: "хвастаться, кичиться" },
  { key: "braid", value: "коса или оплётка" },
  { key: "brake", value: "тормоз" },
  { key: "branch", value: ["ветвь", "филиал, ответвление"] },
  { key: "brass", value: "латунь" },
  { key: "brassiere (bra)", value: "бюстгальтер" },
  { key: "brave", value: "храбрый" },
  { key: "brawl", value: "шумная драка, скандал" },
  { key: "brazen", value: "наглый" },
  { key: "breach", value: "брешь, прорывать, пробивать" },
  { key: "breadth", value: "ширина, широта" },
  { key: "break", value: "перерыв, перемена" },
  { key: "break (broke, broken)", value: "нарушать" },
  { key: "break away", value: "отделяться" },
  { key: "break down", value: "ломаться" },
  { key: "break into (break in)", value: "проникнуть, вломиться" },
  { key: "break out", value: ["вспыхнуть, разразиться", "сбежать, вырваться"] },
  { key: "break up", value: "разорвать отношения" },
  { key: "breakthrough", value: "прорыв, достижение" },
  { key: "breast", value: "грудь" },
  { key: "breath", value: "дыхание, вздох" },
  { key: "breathe", value: "дышать" },
  { key: "breed", value: "порода, поколение и т д." },
  { key: "breed (bred, bred)", value: "разводить, выращивать" },
  { key: "brew", value: "заваривать, варить напиток" },
  { key: "bribe", value: "взятка" },
  { key: "brick", value: "кирпич" },
  { key: "bride", value: "невеста" },
  { key: "bridge", value: "мост" },
  { key: "brief", value: "краткий" },
  { key: "briefcase", value: "портфель" },
  { key: "bright", value: "яркий" },
  { key: "brilliant", value: "блестящий" },
  { key: "brim", value: "край сосуда" },
  { key: "bring (brought, brought)", value: "принести" },
  { key: "bring along", value: "взять с собой" },
  { key: "bring around", value: "убедить" },
  { key: "bring back", value: "вернуть" },
  { key: "bring down", value: "сбрасывать, свергать" },
  { key: "bring in", value: "привлечь" },
  { key: "bring out", value: "выпустить (новинку и т.д.)" },
  { key: "bring up", value: ["поднять тему", "воспитывать"] },
  { key: "brink", value: "грань, край" },
  { key: "brisk", value: "энергичный, оживлённый" },
  { key: "bristle", value: "щетина" },
  { key: "brittle", value: "ломкий" },
  { key: "broad", value: "широкий" },
  { key: "broadcast", value: "транслировать, трансляция" },
  { key: "broom", value: "метла, веник" },
  { key: "broth", value: "бульон, отвар" },
  { key: "bruise", value: "синяк, ушиб" },
  { key: "brush", value: "кисть, щётка, чистить" },
  { key: "brute", value: "животное, зверь, грубый" },
  { key: "bubble", value: "пузырь" },
  { key: "buck", value: "самец, обычно рогатых" },
  { key: "bucket", value: "ведро, бадья" },
  { key: "buckle", value: "пряжка" },
  { key: "buckle up", value: "пристегнуться" },
  { key: "bud", value: "бутон или почка растения" },
  { key: "buddy", value: "дружище, парень" },
  { key: "budge", value: "сдвинуть" },
  { key: "buffalo", value: "буйвол или бизон" },
  { key: "bug", value: "жук" },
  { key: "build on", value: "нарастить, развить" },
  { key: "built-in", value: "встроенный" },
  { key: "bulb", value: "лампа, колба" },
  { key: "bulge", value: "бугор, выпуклость" },
  { key: "bulk", value: "основная масса" },
  { key: "bullet", value: "пуля" },
  { key: "bullshit", value: "ерунда, чушь" },
  { key: "bully", value: "задира, задирать" },
  { key: "bum", value: "бомж или бездельник" },
  { key: "bump", value: ["шишка, выпуклость", "удар, ударять"] },
  { key: "bun", value: "булочка" },
  { key: "bunch", value: "связка, пучок, группа" },
  { key: "bundle", value: "связка, пучок, пачка" },
  { key: "bunk", value: "койка, спальное место" },
  { key: "bunny", value: "кролик (разг, детск.)" },
  { key: "burden", value: "бремя, нагружать" },
  { key: "burglar", value: "вор взломщик" },
  { key: "burn", value: "жечь" },
  { key: "burn down", value: "сгореть, сжечь (полностью)" },
  { key: "burn out", value: "выгореть, перегореть" },
  { key: "burrow", value: "нора, зарываться" },
  { key: "burst", value: "взрыв, всплеск и т. д." },
  { key: "bury", value: "хоронить" },
  { key: "bush", value: "куст" },
  { key: "bustle", value: "суета, суматоха" },
  { key: "busy", value: "занятый" },
  { key: "butcher", value: "мясник" },
  { key: "butt", value: ["торец, зад", "задница"] },
  { key: "butt in", value: "встревать, вмешиваться" },
  { key: "butter", value: "масло сливочное" },
  { key: "butterfly", value: "бабочка" },
  { key: "button", value: "пуговица, застёгивать" },
  { key: "buy", value: "верить, соглашаться (разг.)" },
  { key: "buy up", value: "скупить" },
  { key: "buzz", value: "жужжать" },
  { key: "by chance", value: "случайно" },
  { key: "by far", value: "безусловно" },
  { key: "by heart", value: "наизусть" },
  { key: "by oneself", value: "один, сам" },
  { key: "by the way", value: "кстати" },
  { key: "bypass", value: "обходить, обход" },
]
