import { TDictionaryItem } from "../types"
export const c_arr: TDictionaryItem[] = [
  { key: "cab", value: "такси" },
  { key: "cabbage", value: "капуста" },
  { key: "cabin", value: "хижина" },
  { key: "cable", value: "канат, кабель, трос и т.д." },
  { key: "cage", value: "клетка" },
  { key: "calf (pl:calves)", value: "теленок" },
  { key: "call back", value: "перезвонить" },
  { key: "call for", value: "требовать, взывать" },
  { key: "call off", value: "отменить" },
  { key: "call on", value: "обратиться, попросить" },
  { key: "calm", value: "спокойный, успокоить" },
  { key: "calm down", value: "успокоиться" },
  { key: "camp", value: "лагерь" },
  { key: "can", value: "банка" },
  { key: "cancel", value: "отменять" },
  { key: "cancer", value: "рак (болезнь)" },
  { key: "candid", value: "честный, беспристрастный" },
  { key: "candle", value: "свеча" },
  { key: "candy", value: "конфеты" },
  { key: "cane", value: "трость" },
  { key: "cannon", value: "пушка" },
  { key: "canopy", value: "навес, тент, полог" },
  { key: "canvas", value: "холст" },
  { key: "cap", value: "кепка, шляпа, колпачок" },
  { key: "capable", value: "способный к ч-л." },
  { key: "capacity", value: ["ёмкость, вместимость", "способность, возможность"] },
  { key: "cape", value: "мыс" },
  { key: "capital", value: "главный, большой, высший" },
  { key: "captive", value: "пленник" },
  { key: "capture", value: "захватить" },
  { key: "carbohydrate", value: "углевод" },
  { key: "carbon", value: "углерод, уголь, графит" },
  { key: "carcass", value: "туша" },
  { key: "cardboard", value: "картон" },
  { key: "care", value: ["забота, уход", "переживать, интересоваться"] },
  { key: "career", value: "карьера" },
  { key: "caress", value: "ласкать, гладить" },
  { key: "cargo", value: "груз, грузовой" },
  { key: "carpenter", value: "плотник" },
  { key: "carpet", value: "ковер" },
  { key: "carriage", value: "каретка" },
  { key: "carrot", value: "морковь" },
  { key: "carry", value: "носить" },
  { key: "carry out", value: "выполнить" },
  { key: "cart", value: "телега" },
  { key: "cartoon", value: "мультфильм" },
  { key: "carve", value: "вырезать (напр. из дерева)" },
  { key: "case", value: ["случай, дело", "ящик, футляр, чехол"] },
  { key: "cash", value: "наличка, обналичить" },
  { key: "casket", value: "шкатулка или гроб (амер.)" },
  { key: "cast (cast, cast)", value: ["бросать, метать", "отливать"] },
  { key: "casual", value: "случайный" },
  { key: "casualty", value: "жертва, потери" },
  { key: "catch", value: "расслышать, уловить" },
  { key: "catch (caught, caught)", value: "ловить" },
  { key: "catch on", value: ["становиться популярным", "внезапно понять"] },
  { key: "catch up on", value: "следить быть в курсе" },
  { key: "catch up with", value: "догнать" },
  { key: "cater", value: "обслуживать, угождать" },
  { key: "catering", value: "общественное питание" },
  { key: "cathedral", value: "собор" },
  { key: "cattle", value: "крупный рогатый скот" },
  { key: "cause", value: "причина, быть причиной" },
  { key: "caution", value: "предосторожность, предостережение" },
  { key: "cave", value: "пещера, полость" },
  { key: "caviar", value: "икра" },
  { key: "cavity", value: "полость, впадина" },
  { key: "cease", value: "прекращать" },
  { key: "cedar", value: "кедр" },
  { key: "ceiling", value: "потолок, перекрытие" },
  { key: "celebrate", value: "праздновать" },
  { key: "celebrity", value: "знаменитость" },
  { key: "celestial", value: "астрономический, небесный" },
  { key: "cell", value: "ячейка, клетка" },
  { key: "cellar", value: "подвал" },
  { key: "cellular", value: "сотовый" },
  { key: "cemetery", value: "кладбище" },
  { key: "censorship", value: "цензура" },
  { key: "census", value: "перепись" },
  { key: "century", value: "век" },
  { key: "cereal", value: "злак, каша, хлопья" },
  { key: "certain", value: "определённый, уверенный" },
  { key: "chain", value: "цепь" },
  { key: "chair", value: "стул" },
  { key: "chairman", value: "председатель" },
  { key: "chalk", value: "мел" },
  { key: "challenge", value: "вызов, необычная задача" },
  { key: "chamber", value: "кабинет, зал, палата, камера" },
  { key: "chancellor", value: "канцлер" },
  { key: "change", value: "сдача, мелочь" },
  { key: "chant", value: "петь, скандировать, песнопение" },
  { key: "chaos", value: "хаос" },
  { key: "chap", value: "парень" },
  { key: "chapel", value: "часовня" },
  { key: "chapter", value: "глава" },
  { key: "character", value: "персонаж" },
  { key: "charge", value: ["заряжать, нагружать", "обвинять", "плата"] },
  { key: "charity", value: "благотворительность" },
  { key: "charm", value: "обаяние, очаровывать" },
  { key: "chart", value: "схема, график, таблица" },
  { key: "chase", value: "погоня, гнаться" },
  { key: "chat", value: "болтать" },
  { key: "chatter", value: "болтать, болтовня" },
  { key: "cheat", value: "жульничать" },
  { key: "cheat on", value: "изменять" },
  { key: "check", value: "проверить" },
  { key: "check in", value: "вселиться (в отель)" },
  { key: "check into", value: "лечь (в больницу)" },
  { key: "check on", value: "проверить, что всё норм" },
  { key: "check out", value: ["посмотреть, заценить", "освободить номер"] },
  { key: "checkup", value: "медосмотр" },
  { key: "cheek", value: "щека" },
  { key: "cheer", value: "аплодировать, радостно встречать" },
  { key: "cheer on", value: "болеть (за спорт)" },
  { key: "cheer up", value: "взбодриться" },
  { key: "cheerful", value: "весёлый, неунывающий" },
  { key: "chef", value: "шеф-повар" },
  { key: "chemistry", value: "химия" },
  { key: "cherish", value: "лелеять, хранить" },
  { key: "chess", value: "шахматы" },
  { key: "chest", value: ["грудь (грудная клетка)", "сундук"] },
  { key: "chestnut", value: "каштан" },
  { key: "chew", value: "жевать" },
  { key: "chief", value: "вождь, начальник, главный" },
  { key: "childhood", value: "детство" },
  { key: "chill", value: "холод, охлаждать" },
  { key: "chill out", value: "расслабиться" },
  { key: "chimney", value: "дымовая труба" },
  { key: "chin", value: "подбородок" },
  { key: "chip", value: "щепка, стружка" },
  { key: "choice", value: "выбор" },
  { key: "choir", value: "хор" },
  { key: "choke", value: "задыхаться,  давиться" },
  { key: "chop", value: "рубить" },
  { key: "chop down", value: "срубить (дерево)" },
  { key: "chop up", value: "порезать (на кусочки)" },
  { key: "chord", value: "аккорд" },
  { key: "chore", value: "скучная неприятная работа" },
  { key: "chorus", value: "припев" },
  { key: "Christmas", value: "рождество" },
  { key: "chuck", value: "бросать (небрежно)" },
  { key: "chuckle", value: "посмеиваться" },
  { key: "chunk", value: "кусок" },
  { key: "church", value: "церковь" },
  { key: "cinema", value: "кино, кинотеатр" },
  { key: "cinnamon", value: "корица" },
  { key: "circle", value: "круг, окружность" },
  { key: "circuit", value: "схема, цепь, контур" },
  { key: "circumstance", value: "обстоятельство" },
  { key: "circus", value: "цирк" },
  { key: "cite", value: "упоминать, цитировать" },
  { key: "citizen", value: "гражданин" },
  { key: "civic", value: "гражданский" },
  { key: "civil", value: "гражданский" },
  { key: "civilian", value: "гражданский" },
  { key: "claim", value: ["требовать, претендовать", "утверждать, претендовать"] },
  { key: "clam", value: "моллюск" },
  { key: "clamour", value: "шум, ропот, протесты" },
  { key: "clamp", value: "зажимать, зажим" },
  { key: "clap", value: "хлопать в ладоши" },
  { key: "clarify", value: "прояснять" },
  { key: "clash", value: "столкновение" },
  { key: "clasp", value: "застёжка, застёгивать" },
  { key: "clause", value: "пункт, статья документа" },
  { key: "claw", value: "коготь, клешня" },
  { key: "clay", value: "глина" },
  { key: "clean up", value: "убрать (мусор)" },
  { key: "cleanse", value: "очищать" },
  { key: "clear", value: "ясный, чистый (пр. и перен.)" },
  { key: "clear off", value: "убраться вон" },
  { key: "clear out", value: "убирать, забирать" },
  { key: "clear up", value: "прояснить(ся)" },
  { key: "cleave", value: "раскалывать" },
  { key: "clench", value: "стиснуть, сжать" },
  { key: "clergy", value: "духовенство" },
  { key: "clerical", value: "канцелярский, административный" },
  { key: "clever", value: "умный" },
  { key: "click", value: "щёлкать, щелчок" },
  { key: "cliff", value: "утес" },
  { key: "climax", value: "кульминация, разгар" },
  { key: "climb", value: "взбираться" },
  { key: "cling (clung, clung)", value: "цепляться" },
  { key: "clip", value: ["отсекать, обрезать", "зажим, зажимать"] },
  { key: "cloak", value: "плащ, мантия, покров" },
  { key: "clockwise", value: "по часовой стрелке" },
  { key: "clog", value: "загромождать" },
  { key: "close down", value: "закрыться (насовсем)" },
  { key: "close in on", value: "приближаться" },
  { key: "closet", value: "стенной шкаф" },
  { key: "closure", value: "закрытие, завершение" },
  { key: "cloth", value: "ткань, тряпка" },
  { key: "clothe", value: "одевать, покрывать" },
  { key: "cloud", value: "облако" },
  { key: "clout", value: "влияние, влиятельность" },
  { key: "clove", value: "гвоздика" },
  { key: "clue", value: "ключ, нить, улика" },
  { key: "clump", value: "комок, кучка, клок" },
  { key: "clumsy", value: "неловкий, неуклюжий" },
  { key: "clutch", value: "сцеплять, сцепление" },
  { key: "clutter", value: "беспорядок, куча всего" },
  { key: "coach", value: ["автобус, вагон, телега", "тренер"] },
  { key: "coal", value: "уголь" },
  { key: "coarse", value: "грубый, крупный, шероховатый" },
  { key: "coast", value: "побережье" },
  { key: "coaster", value: "подставка" },
  { key: "coat", value: ["покрывать", "пальто"] },
  { key: "coax", value: "убедить, соблазнить сделать" },
  { key: "coconut", value: "кокос" },
  { key: "coerce", value: "принуждать" },
  { key: "coffin", value: "гроб" },
  { key: "coherent", value: "согласованный, связный" },
  { key: "cohesion", value: "единство, согласие" },
  { key: "coil", value: "катушка, моток, наматывать" },
  { key: "coincide", value: "совпасть" },
  { key: "coincidence", value: "совпадение" },
  { key: "cold", value: "простуда" },
  { key: "collaborate", value: "сотрудничать" },
  { key: "collapse", value: "обрушиться, сложиться" },
  { key: "collar", value: "воротник или ошейник" },
  { key: "collect", value: "собирать" },
  { key: "collide", value: "сталкиваться" },
  { key: "colon", value: "двоеточие" },
  { key: "colonel", value: "полковник" },
  { key: "column", value: "столб, колонна" },
  { key: "comb", value: "расческа, причёсывать" },
  { key: "combat", value: "бой" },
  { key: "combine", value: "соединять(ся)" },
  { key: "come about", value: "произойти" },
  { key: "come across", value: "встретить (случайно)" },
  { key: "come along", value: ["идти вместе", "продвигаться (о работе)"] },
  { key: "come by", value: ["найти, заполучить", "зайти"] },
  { key: "come down", value: "сводиться" },
  { key: "come from", value: "быть из" },
  { key: "come into", value: "унаследовать" },
  { key: "come off", value: ["выйти, получиться", "отвалиться"] },
  { key: "come on", value: "включаться" },
  { key: "come out", value: ["выступить, заявить", "выходить (напр. об альбоме)"] },
  { key: "come over", value: "заходить (в гости)" },
  { key: "come through", value: "пережить, перенести" },
  { key: "come to", value: ["очнуться", "доходить до"] },
  { key: "come to life", value: "оживать, приходить в себя" },
  { key: "come true", value: "сбываться" },
  { key: "come under", value: "подвегрнуться" },
  { key: "come up", value: ["произойти или появиться", "приближаться (о событии)"] },
  { key: "come up to", value: "подойти к кому-л." },
  { key: "come up with", value: "придумать" },
  { key: "come with", value: "прилагаться" },
  { key: "comedian", value: "комик" },
  { key: "comfort", value: "утешать, утешение" },
  { key: "commemorate", value: "отметить, почтить" },
  { key: "commence", value: "начинать" },
  { key: "commend", value: "высоко оценивать" },
  { key: "commercial", value: "реклама (на ТВ)" },
  { key: "commission", value: "поручение, полномочие" },
  { key: "commit", value: "совершить (напр. ошибку)" },
  { key: "commitment", value: ["приверженность", "обязательство"] },
  { key: "commodity", value: "товар, сырьё" },
  { key: "common", value: ["общий", "обычный, распространённый"] },
  { key: "commonplace", value: "обычное дело, банальность" },
  { key: "commonwealth", value: "содружество" },
  { key: "communicate", value: "общаться" },
  { key: "community", value: "община, сообщество" },
  { key: "commute", value: "ходить, курсировать" },
  { key: "compact", value: "договор" },
  { key: "compare", value: "сравнить" },
  { key: "comparison", value: "сравнение" },
  { key: "compartment", value: "отсек, отделение, купе" },
  { key: "compassion", value: "сочуствие, сострадание" },
  { key: "compatible", value: "совместимый" },
  { key: "compel", value: "вынуждать, заставлять" },
  { key: "compete", value: "соперничать" },
  { key: "complain", value: "жаловаться" },
  { key: "complement", value: ["допонять, дополнение", "набор, состав, комплект"] },
  { key: "complete", value: "завершить, выполнить" },
  { key: "complex", value: "сложный" },
  { key: "complicate", value: "усложнять" },
  { key: "comply", value: "соблюдать, соответствовать" },
  { key: "compose", value: "составлять, сочинять" },
  { key: "compound", value: "состав, составной" },
  { key: "comprehend", value: "понять, вникнуть" },
  { key: "comprehensive", value: "исчерпывающий, всесторонний" },
  { key: "compress", value: "сжимать, прессовать" },
  { key: "comprise", value: "состоять из, охватывать" },
  { key: "compulsory", value: "принудительный, обязательный" },
  { key: "comrade", value: "товарищ" },
  { key: "conceal", value: "скрывать" },
  { key: "concede", value: "уступить" },
  { key: "conceive", value: "помыслить, представить" },
  { key: "concept", value: "понятие, идея" },
  { key: "concern", value: "забота, тревожить" },
  { key: "conclude", value: "заключать, завершать" },
  { key: "concrete", value: "бетон, бетонировать" },
  { key: "concur", value: "соглашаться" },
  { key: "condemn", value: "осуждать" },
  { key: "condition", value: ["состояние", "условие"] },
  { key: "conduct", value: "вести, поведение" },
  { key: "cone", value: "конус" },
  { key: "confer", value: ["дать, принести, присудить", "совещаться"] },
  { key: "confess", value: "признаваться" },
  { key: "confide", value: "доверить, вверить" },
  { key: "confident", value: "уверенный" },
  { key: "confine", value: "ограничить (ся)" },
  { key: "confirm", value: "подтвердить" },
  { key: "conform", value: "соответствовать" },
  { key: "confront", value: "противостоять, сталкиваться" },
  { key: "confuse", value: "путать" },
  { key: "congestion", value: "загруженность, запор" },
  { key: "congratulate", value: "поздравлять" },
  { key: "conjunction", value: "соединение, связь" },
  { key: "connect", value: "соединять" },
  { key: "conquer", value: "завоевать" },
  { key: "conquest", value: "завоевание" },
  { key: "conscience", value: "совесть, сознательность" },
  { key: "conscious", value: "сознательный, сознающий" },
  { key: "consecutive", value: "последующий по времени" },
  { key: "consent", value: "согласие, разрешение" },
  { key: "consequence", value: "последствие" },
  { key: "consequent", value: "последующий, вытекающий" },
  { key: "conserve", value: "беречь, экономить" },
  { key: "consider", value: ["рассматривать, учитывать", "считать чем-либо"] },
  { key: "considerable", value: "крупный, значительный" },
  { key: "consist of", value: "состоять (из)" },
  { key: "consistent", value: "последовательный" },
  { key: "console", value: "утешать" },
  { key: "conspicuous", value: "заметный" },
  { key: "conspire", value: "сговариваться" },
  { key: "constant", value: "постоянный" },
  { key: "constellation", value: "созвездие" },
  { key: "constitute", value: "составлять, образовывать" },
  { key: "constrain", value: "ограничивать (препятствием)" },
  { key: "construct", value: "соорудить" },
  { key: "construction (site)", value: "стройка" },
  { key: "consult", value: "советоваться" },
  { key: "consume", value: "потреблять" },
  { key: "contain", value: "содержать" },
  { key: "contaminate", value: "загрязнять" },
  { key: "contemplate", value: "созерцать или размышлять" },
  { key: "contemporary", value: "современный, современник" },
  { key: "contempt", value: "презрение, презирать" },
  { key: "contend", value: "бороться, соперничать" },
  { key: "content", value: "содержимое" },
  { key: "content with", value: "довольный, довольство" },
  { key: "contest", value: "соревнование, конкурс" },
  { key: "contingency", value: "непредвиденные обстоятельства" },
  { key: "continue", value: "продолжить" },
  { key: "contract", value: "сокращаться" },
  { key: "contradict", value: "противоречить" },
  { key: "contrary", value: "противоположный, вопреки" },
  { key: "contribute", value: "способствовать, вносить вклад" },
  { key: "controversy", value: "спор, разногласие, дискуссия" },
  { key: "convene", value: "созывать, собирать" },
  { key: "convenient", value: "удобный" },
  { key: "conventional", value: "стандартный, общепринятый" },
  { key: "converge", value: "сходиться, сближаться" },
  { key: "converse", value: "разговаривать" },
  { key: "convert", value: "преобразовывать" },
  { key: "convey", value: "перевозить, передавать" },
  { key: "convict", value: "осуждённый, осуждать" },
  { key: "conviction", value: "убеждение, убеждённость" },
  { key: "convince", value: "убеждать" },
  { key: "cookie", value: "печенье" },
  { key: "cool", value: "прохладный, свежий" },
  { key: "cool down", value: "остыть" },
  { key: "cooperate", value: "сотрудничать" },
  { key: "cope with", value: "совладать, справиться" },
  { key: "copper", value: "медь" },
  { key: "cord", value: "верёвка, шнур" },
  { key: "core", value: "ядро, сердцевина, сущность" },
  { key: "cork", value: "пробка" },
  { key: "corn", value: "кукуруза, зерно" },
  { key: "corner", value: "угол" },
  { key: "corps", value: "корпус" },
  { key: "corpse", value: "труп" },
  { key: "correct", value: "правильный, исправлять" },
  { key: "correlate", value: "соотносить" },
  { key: "correspond", value: "соответствовать" },
  { key: "corrupt", value: "развращать, разлагать" },
  { key: "cost (cost, cost)", value: "стоить, стоимость" },
  { key: "cotton", value: "хлопок" },
  { key: "couch", value: "диван" },
  { key: "cough", value: "кашель" },
  { key: "council", value: "совет (орган)" },
  { key: "counsel", value: "совет, консультация" },
  { key: "count", value: ["считаться, иметь значение", "считать"] },
  { key: "count on", value: "рассчитывать на" },
  { key: "counter", value: ["противостоять, противоположный", "стойка, прилавок"] },
  { key: "counterfeit", value: "подделка, фальшивый" },
  { key: "counterpart", value: "аналог, коллега, и т. д." },
  { key: "countryside", value: "сельская местность" },
  { key: "county", value: "графство, округ" },
  { key: "coup", value: "переворот" },
  { key: "couple", value: "пара" },
  { key: "courage", value: "мужество" },
  { key: "court", value: ["суд", "двор (королевский)", "игровая площадка"] },
  { key: "courtesy", value: "учтивость, этикет" },
  { key: "courtyard", value: "внутренний двор" },
  { key: "cover", value: "накрывать, покрывать" },
  { key: "coverage", value: "освещение" },
  { key: "covet", value: "желать, вожделеть" },
  { key: "coward", value: "трус" },
  { key: "co-worker", value: "сотрудник" },
  { key: "cozy", value: "уютный" },
  { key: "crack", value: "трескаться, трещина" },
  { key: "crackle", value: "потрескивание" },
  { key: "cradle", value: "колыбель" },
  { key: "craft", value: "ремесло, мастерство" },
  { key: "cram", value: "втискивать, впихивать" },
  { key: "cramp", value: "судорога" },
  { key: "crane", value: "подъёмный кран" },
  { key: "crank", value: "чудак, фрик" },
  { key: "crap", value: "дерьмо" },
  { key: "crash", value: "горохот, крушение, разбивать и т. д." },
  { key: "crate", value: "ящик" },
  { key: "crave", value: "желать, жаждать, требовать" },
  { key: "crawl", value: "ползать" },
  { key: "crayon", value: "цветной карандаш, мелок" },
  { key: "creak", value: "скрипеть" },
  { key: "cream", value: "крем, сливки" },
  { key: "crease", value: "складка, сминать" },
  { key: "create", value: "создавать" },
  { key: "creature", value: "существо" },
  { key: "credential", value: "удостоверение, аккредитация" },
  { key: "credible", value: "заслуживающий доверия" },
  { key: "creed", value: "вероисповедание, убеждение" },
  { key: "creek", value: "ручей" },
  { key: "creep", value: "гад, урод (разг)" },
  { key: "creep  (crept, crept)", value: "ползти, красться" },
  { key: "creepy", value: "жуткий" },
  { key: "crest", value: "гребень" },
  { key: "crew", value: "команда, экипаж" },
  { key: "crib", value: "раскладушка или дет. кроватка" },
  { key: "crime", value: "преступление" },
  { key: "criminal", value: "преступник" },
  { key: "crimson", value: "малиновый, багряный" },
  { key: "cringe", value: "съёживаться" },
  { key: "cripple", value: "калека, калечить" },
  { key: "crisp", value: "хрустящий" },
  { key: "crook", value: "сгибать, искривлять" },
  { key: "crop", value: "урожай" },
  { key: "cross", value: "пересекать, пересечение, крест" },
  { key: "cross out", value: "вычеркнуть" },
  { key: "crossroads", value: "перекрёсток, перепутье" },
  { key: "crouch", value: "присесть, припасть к земле" },
  { key: "crow", value: "ворона" },
  { key: "crowd", value: "толпа" },
  { key: "crown", value: "корона, короновать" },
  { key: "crucial", value: "решающий, критический" },
  { key: "crude", value: "сырой, грубый, необработанный" },
  { key: "cruel", value: "жестокий" },
  { key: "crumb", value: "крошка, крупица" },
  { key: "crumble", value: "крошить, рушиться" },
  { key: "crumple", value: "смять" },
  { key: "crunch", value: "хрустеть" },
  { key: "crusade", value: "крестовый поход" },
  { key: "crush", value: "раздавливать, дробить" },
  { key: "crust", value: "кора, корка" },
  { key: "cry out", value: "закричать (от страха, боли)" },
  { key: "cub", value: "детеныш" },
  { key: "cubicle", value: "отсек, кабинка" },
  { key: "cucumber", value: "огурец" },
  { key: "cuddle", value: "обнимать, прижимать" },
  { key: "cue", value: "сигнал, намёк" },
  { key: "cuisine", value: "кухня" },
  { key: "cup", value: "чашка, кружка, кубок" },
  { key: "cupboard", value: "шкаф, буфет" },
  { key: "curb", value: ["узда, обуздать, сдержать", "бордюр или обочина"] },
  { key: "cure", value: "лечить" },
  { key: "curious", value: "любопытный" },
  { key: "curl", value: "скручивать, клубиться, завиток" },
  { key: "currency", value: "валюта" },
  { key: "current", value: ["текущий, актуальный", "ток, поток, течение"] },
  { key: "curriculum vitae", value: "резюме, биография" },
  { key: "curse", value: "проклятие" },
  { key: "curtain", value: "занавеска, занавес" },
  { key: "curve", value: "изгибать, кривая" },
  { key: "cushion", value: "подушка (маленькая)" },
  { key: "custody", value: "охрана, стража или опека" },
  { key: "custom", value: ["заказной, индивидуальный", "обычай, привычка"] },
  { key: "customer", value: "клиент" },
  { key: "customs", value: "таможня" },
  { key: "cut across", value: "пересечь, срезать путь" },
  { key: "cut down", value: "урезать, уменьшить" },
  { key: "cut off", value: "отрезать, отключить" },
  { key: "cute", value: "привлекательный, милый" },
]
