import { TDictionaryItem } from "../types"
export const d_arr: TDictionaryItem[] = [
  { key: "dagger", value: "кинжал" },
  { key: "daily", value: "ежедневно" },
  { key: "dairy", value: "молочные продукты" },
  { key: "dam", value: "плотина" },
  { key: "damage", value: "вред, повреждать" },
  { key: "damn", value: "проклятый, проклинать" },
  { key: "damp", value: "сырой, сырость" },
  { key: "dangle", value: "мотаться" },
  { key: "dare", value: "осмелиться" },
  { key: "darling", value: "дорогой/ая (устар.) " },
  { key: "darn", value: "штопать" },
  { key: "dash", value: ["тире, чёрточка", "бросать, бросаться", "разрушить (перен.)"] },
  { key: "data", value: "данные" },
  { key: "database", value: "база данных" },
  { key: "date", value: "свидание, встречаться" },
  { key: "daunt", value: "пугать, обескураживать" },
  { key: "dawn", value: "рассвет" },
  { key: "dawn on", value: "осенить" },
  { key: "day off", value: "выходной" },
  { key: "daze", value: "ошеломить" },
  { key: "dazzle", value: "ослепить" },
  { key: "dead end", value: "тупик" },
  { key: "deaf", value: "глухой" },
  { key: "deal", value: "сделка" },
  { key: "deal in", value: "заниматься (напр. торговать)" },
  { key: "deal with", value: "иметь дело с" },
  { key: "debate", value: "обсуждать, спорить" },
  { key: "debris", value: "мусор, обломки, завалы" },
  { key: "debt", value: "долг" },
  { key: "decade", value: "десятилетие или десяток" },
  { key: "decay", value: "распад, упадок, разлагаться" },
  { key: "deceased", value: "покойный, усопший" },
  { key: "deceive", value: "обманывать" },
  { key: "decent", value: "приличный, достойный" },
  { key: "deception", value: "обман" },
  { key: "decide", value: "решить" },
  { key: "decisive", value: "решающий, решительный" },
  { key: "deck", value: "палуба, крышка, настил" },
  { key: "declare", value: "объявлять" },
  { key: "decline", value: ["отказаться, отклонить", "снижаться, снижение"] },
  { key: "decorate", value: "украшать" },
  { key: "decrease", value: "уменьшать(ся), уменьшение" },
  { key: "decree", value: "постановление, декрет, указ" },
  { key: "dedicate", value: "посвящать" },
  { key: "deduct", value: "вычитать (об. про деньги)" },
  { key: "deed", value: "дело, поступок" },
  { key: "deem", value: "считать (чем-либо)" },
  { key: "deep", value: "глубокий" },
  { key: "deer (pl:deer)", value: "олень" },
  { key: "defeat", value: "поражение, наносить поражение" },
  { key: "defence (defense)", value: "защита, защитный" },
  { key: "defend", value: "защитить" },
  { key: "deficient", value: "недостаточный, неполный" },
  { key: "define", value: "определять" },
  { key: "definite", value: "определённый" },
  { key: "deflect", value: "отклонять, преломлять" },
  { key: "deft", value: "ловкий, проворный" },
  { key: "defy", value: "пренебрегать, отрицать" },
  { key: "degree", value: ["степень (во всех значениях)", "градус"] },
  { key: "deity", value: "божество" },
  { key: "delay", value: "задерживать(ся)" },
  { key: "deliberate", value: "обдуманный, преднамеренный" },
  { key: "delicate", value: "тонкий, нежный, хрупкий" },
  { key: "delicious", value: "восхитительный (о еде)" },
  { key: "delight", value: "восторг" },
  { key: "delinquent", value: "правонарушитель" },
  { key: "deliver", value: ["доставлять", "рожать"] },
  { key: "delusion", value: "наваждение, заблуждение" },
  { key: "demand", value: ["требовать", "спрос"] },
  { key: "demise", value: "кончина, конец" },
  { key: "demolish", value: "сносить" },
  { key: "den", value: "логово, берлога" },
  { key: "denote", value: "обозначать" },
  { key: "denounce", value: "осуждать, разоблачать" },
  { key: "dense", value: "густой" },
  { key: "dent", value: "вмятина" },
  { key: "dental", value: "зубной, стоматологический" },
  { key: "deny", value: "отрицать" },
  { key: "depart", value: "отправляться, отходить" },
  { key: "department", value: "отдел" },
  { key: "depend", value: "зависеть" },
  { key: "dependent", value: "зависимый" },
  { key: "depict", value: "изображать, описывать" },
  { key: "deplete", value: "истощать" },
  { key: "deploy", value: "развёртывать" },
  { key: "depot", value: "хранилище, база, склад" },
  { key: "depress", value: "угнетать, подавлять" },
  { key: "deprive", value: "лишать" },
  { key: "depth", value: "глубина" },
  { key: "deputy", value: "депутат, представитель" },
  { key: "derive", value: "выводить, извлекать" },
  { key: "descend", value: "спускаться" },
  { key: "descend from", value: "происходить от" },
  { key: "describe", value: "описать" },
  { key: "desert", value: ["пустыня", "бросать, оставлять"] },
  { key: "deserve", value: "заслуживать" },
  { key: "designate", value: "обозначать, называть" },
  { key: "desire", value: "желание, желать" },
  { key: "desk", value: "письменный стол" },
  { key: "desktop", value: "настольный" },
  { key: "desolate", value: "пустынный, безлюдный" },
  { key: "despair", value: "отчаяние, безнадёжность" },
  { key: "desperate", value: "отчаянный, безвыходный" },
  { key: "despise", value: "презирать" },
  { key: "despite", value: "несмотря на" },
  { key: "destination", value: "место назначения" },
  { key: "destiny", value: "судьба, предназначение" },
  { key: "destroy", value: "разрушать" },
  { key: "detach", value: "отделить, оторвать" },
  { key: "detain", value: "задерживать" },
  { key: "detect", value: "обнаружить, выявить" },
  { key: "detention", value: "задержание, арест" },
  { key: "deter", value: "удерживать (от действия)" },
  { key: "deteriorate", value: "ухудшать" },
  { key: "determine", value: "определить" },
  { key: "determined", value: "решителен" },
  { key: "detriment", value: "ущерб, вред" },
  { key: "devastate", value: "опустошать, разорять" },
  { key: "develop", value: "развивать, разрабатывать" },
  { key: "deviate", value: "отклоняться" },
  { key: "devise", value: "придумывать, изобретать" },
  { key: "devoid", value: "лишенный" },
  { key: "devote", value: "посвятить, уделить" },
  { key: "devour", value: "пожирать" },
  { key: "dial", value: "набирать номер" },
  { key: "diamond", value: "бриллиант обычно алмаз" },
  { key: "diary", value: "дневник" },
  { key: "dice (pl: dice)", value: "кубик (игральный)" },
  { key: "dictionary", value: "словарь" },
  { key: "die down", value: "утихнуть" },
  { key: "die out", value: "вымереть" },
  { key: "differ", value: "отличаться" },
  { key: "different", value: "разный, отличающийся" },
  { key: "difficulty", value: "трудность" },
  { key: "diffuse", value: "рассеивать, распылять" },
  { key: "dig (dug, dug)", value: "копать" },
  { key: "dig up", value: "откопать" },
  { key: "digest", value: "переваривать" },
  { key: "digit", value: "цифра" },
  { key: "dignity", value: "достоинство" },
  { key: "diligent", value: "усердный, старательный" },
  { key: "dilute", value: "разбавлять, разводить" },
  { key: "dim", value: "тусклый" },
  { key: "dimension", value: "измерение, размер" },
  { key: "diminish", value: "уменьшаться" },
  { key: "dine", value: "ужинать" },
  { key: "dip", value: "окунать, погружать" },
  { key: "dire", value: "страшный, тяжёлый" },
  { key: "direct", value: ["прямой (обычн. перен.знач.)", "направлять"] },
  { key: "directory", value: "справочник" },
  { key: "disable", value: "отключить, нейтрализовать" },
  { key: "disabled", value: "инвалид (прил.)" },
  { key: "disappoint", value: "разочаровывать" },
  { key: "disaster", value: "бедствие" },
  { key: "discard", value: "отбросить, отказаться" },
  { key: "discern", value: "различить, распознать" },
  { key: "disciple", value: "ученик, последователь" },
  { key: "disclose", value: "раскрывать, обнаруживать" },
  { key: "discount", value: "скидка" },
  { key: "discourage", value: "отговорить, демотивировать" },
  { key: "discourse", value: "речь, рассуждение" },
  { key: "discover", value: "открыть (новое)" },
  { key: "discreet", value: "сдержанный" },
  { key: "discrepancy", value: "несоответствие, расхождение" },
  { key: "discrete", value: "отдельный, разрозненный" },
  { key: "discretion", value: "благоразумие, усмотрение" },
  { key: "discriminate", value: "различать, разделять" },
  { key: "discuss", value: "обсуждать" },
  { key: "disdain", value: "пренебрегать, презирать" },
  { key: "disease", value: "болезнь" },
  { key: "disgrace", value: "бесчестие, позор" },
  { key: "disguise", value: "маскировать, маскировка" },
  { key: "disgust", value: "отвращение" },
  { key: "dish", value: ["тарелка или миска", "блюдо"] },
  { key: "disillusion", value: "разочаровывать" },
  { key: "dislocate", value: "вывихнуть, сместить" },
  { key: "dismantle", value: "разобрать, демонтировать" },
  { key: "dismay", value: "испуг, тревога, потрясение" },
  { key: "dismiss", value: ["прогонять, посылать, увольнять", "отклонить, отбросить"] },
  { key: "disorder", value: "беспорядок" },
  { key: "disparity", value: "неравенство" },
  { key: "dispatch", value: "отправлять, отправка" },
  { key: "dispel", value: "развеяться, исчезнуть" },
  { key: "dispense", value: "распределять, раздавать" },
  { key: "dispense with", value: "обойтись без, избавиться" },
  { key: "disperse", value: "рассеиваться" },
  { key: "displace", value: "вытеснять, смещать" },
  { key: "display", value: "показ(ывать), демонстрировать" },
  { key: "dispose of", value: ["располагать, распоряжаться", "избавиться"] },
  { key: "dispute", value: "спор, спорить" },
  { key: "disrupt", value: "нарушить, сорвать" },
  { key: "dissent", value: "несогласие, не соглашаться" },
  { key: "dissipate", value: "рассеивать" },
  { key: "dissolve", value: "растворять, растворяться" },
  { key: "distant", value: "отдалённый" },
  { key: "distinct", value: "чёткий, различимый" },
  { key: "distinguish", value: "выделять, отличать" },
  { key: "distort", value: "искажать" },
  { key: "distract", value: "отвлекать" },
  { key: "distress", value: "несчастье, страдание" },
  { key: "distribute", value: "распределять" },
  { key: "district", value: "район, округ и т. п." },
  { key: "disturb", value: "тревожить" },
  { key: "ditch", value: "ров" },
  { key: "dive", value: "нырять" },
  { key: "diverge", value: "расходиться" },
  { key: "diverse", value: "разнообразный" },
  { key: "divert", value: "отвлечь, развлечь" },
  { key: "divide", value: "делить" },
  { key: "divine", value: "божественный" },
  { key: "divorce", value: "развод, разводиться" },
  { key: "dizzy", value: "головокружительный" },
  { key: "do about", value: "сделать (с чем-то)" },
  { key: "do away with", value: "покончить, избавиться" },
  { key: "do up", value: "привести в порядок" },
  { key: "do without", value: "обойтись без" },
  { key: "dock", value: "причал, док" },
  { key: "dodge", value: "уворачиваться, уклоняться, уловка" },
  { key: "dole", value: "пособие по безработице" },
  { key: "doll", value: "кукла" },
  { key: "domain", value: "область, сфера, владение" },
  { key: "dome", value: "купол, свод" },
  { key: "domestic", value: ["домашний", "внутренний (о политике)"] },
  { key: "donate", value: "жертвовать, скидываться" },
  { key: "donkey", value: "осел" },
  { key: "doom", value: "гибель, рок, обречённость и т. д." },
  { key: "doorway", value: "дверной проем" },
  { key: "dope", value: "наркотик, дурман" },
  { key: "dormitory", value: "общежитие" },
  { key: "dot", value: "точка" },
  { key: "double", value: "удваивать, двойной" },
  { key: "doubt", value: "сомневаться, сомнение" },
  { key: "dough", value: "тесто" },
  { key: "doughnut", value: "пончик" },
  { key: "downtown", value: "центр города" },
  { key: "downturn", value: "спад" },
  { key: "dozen", value: "дюжина" },
  { key: "draft", value: ["тяга, сквозняк", "проект, черновик, набросок"] },
  { key: "drag", value: "тащить, волочить" },
  { key: "drag on", value: "тянуться долго" },
  { key: "drain", value: "слив, водосток" },
  { key: "drastic", value: "радикальный, резкий" },
  { key: "draw (drew, drawn)", value: "тянуть, влечь" },
  { key: "draw up", value: "составить (документ)" },
  { key: "drawback", value: "недостаток" },
  { key: "drawer", value: "выдвижной ящик" },
  { key: "dread", value: "страх, бояться" },
  { key: "dream", value: "сон (видение)" },
  { key: "dream up", value: "придумать (в деталях)" },
  { key: "dress", value: "одеваться" },
  { key: "dress up", value: "нарядиться" },
  { key: "drift", value: "дрейфовать или дрифтовать" },
  { key: "drill", value: "сверло, сверлить" },
  { key: "drills", value: "тренировка, учение" },
  { key: "drip", value: "капля, капать" },
  { key: "drive (drove, driven)", value: ["водить машину", "двигать, гнать"] },
  { key: "drive out", value: "выгнать" },
  { key: "drizzle", value: "моросить, морось" },
  { key: "drop", value: ["падать, ронять", "капля"] },
  { key: "drop by", value: "зайти (по пути)" },
  { key: "drop off", value: "завезти, высадить" },
  { key: "drop out of", value: "бросить (учёбу)" },
  { key: "drought", value: "засуха" },
  { key: "drown", value: "тонуть" },
  { key: "drug", value: "лекарство или наркотик" },
  { key: "drum", value: "барабан, барабанить" },
  { key: "dry", value: "сухой, сушить, засуха" },
  { key: "dry up", value: "пересохнуть, иссякнуть" },
  { key: "dual", value: "парный, двоякий" },
  { key: "dub", value: "дублировать" },
  { key: "dubious", value: "сомнительный" },
  { key: "duckling", value: "утёнок" },
  { key: "dude", value: "чувак" },
  { key: "due", value: "должный, положенный" },
  { key: "due to", value: "из-за, в связи" },
  { key: "duke", value: "герцог" },
  { key: "dull", value: "скучный, унылый" },
  { key: "dumb", value: ["немой", "тупой"] },
  { key: "dummy", value: "манекен, чучело" },
  { key: "dump", value: ["сваливать, сбрасывать свалка", "бросать (парня/девушку)"] },
  { key: "duo", value: "дуэт" },
  { key: "duplicate", value: "дублировать, дубликат" },
  { key: "durable", value: "прочный, долговечный" },
  { key: "duration", value: "продолжительность" },
  { key: "during", value: "во время" },
  { key: "dusk", value: "смеркаться" },
  { key: "dust", value: "пыль" },
  { key: "duty", value: "обязанность, служба" },
  { key: "dwarf", value: "карлик, гном" },
  { key: "dwell", value: "обитать, проживать" },
  { key: "dwell on", value: "остановиться (подробно)" },
  { key: "dwindle", value: "постепенно уменьшаться" },
  { key: "dye", value: "краска, краситель" },
]
