import { TDictionaryItem } from "../types"
export const e_arr: TDictionaryItem[] = [
  { key: "eager", value: "сильно желающий" },
  { key: "early", value: "рано, ранний" },
  { key: "earn", value: "зарабатывать" },
  { key: "earnest", value: "серьёзный, ревностный" },
  { key: "earring", value: "серьга" },
  { key: "earth", value: "Земля" },
  { key: "earthquake (quake)", value: "землетрясение" },
  { key: "ease", value: "лёгкость, облегчать" },
  { key: "east", value: "восток" },
  { key: "Easter", value: "Пасха" },
  { key: "eat out", value: "есть не дома" },
  { key: "eat up", value: "съесть полностью" },
  { key: "echo", value: "эхо, отголосок, отражаться" },
  { key: "eclipse", value: "затмение" },
  { key: "edge", value: "край" },
  { key: "edible", value: "съедобный" },
  { key: "edit", value: "редактировать, монтировать" },
  { key: "educate", value: "воспитывать, обучать" },
  { key: "efficacy", value: "результативность" },
  { key: "efficient", value: "оптимальный, эффективный" },
  { key: "effort", value: "усилие, старание" },
  { key: "either", value: ["либо", "тоже (не)", "любой из двух"] },
  { key: "eject", value: "выталкивать" },
  { key: "elaborate", value: "разработать, хорошо проработанный" },
  { key: "elbow", value: "локоть" },
  { key: "elder", value: "старший" },
  { key: "elect", value: "избирать" },
  { key: "elevate", value: "поднимать, повышать" },
  { key: "elicit", value: "добиться, извлечь" },
  { key: "eligible", value: "имеющий право" },
  { key: "eliminate", value: "устранять, ликвидировать" },
  { key: "elk", value: "лось" },
  { key: "eloquent", value: "красноречивый, выразительный" },
  { key: "elude", value: "ускользнуть, увернуться" },
  { key: "embark on", value: "начать (что-то серьёзное)" },
  { key: "embarrass", value: "смущать, стеснять" },
  { key: "embassy", value: "посольство" },
  { key: "embed", value: "встроить, вставить" },
  { key: "embody", value: "олицетворять" },
  { key: "embrace", value: "обхватить, обнять, обхват" },
  { key: "emerge", value: "появляться" },
  { key: "emergency", value: "чрезвычайная ситуация" },
  { key: "eminent", value: "видный, уважаемый" },
  { key: "emit", value: "испускать, издавать" },
  { key: "emperor", value: "император" },
  { key: "emphasis", value: "акцент, внимание, ударение" },
  { key: "empire", value: "империя" },
  { key: "employ", value: ["использовать", "нанимать на работу"] },
  { key: "empower", value: "давать возможность, право" },
  { key: "empty", value: "пустой, опустошать" },
  { key: "enable", value: "давать возможность" },
  { key: "enact", value: "вводить (напр. закон)" },
  { key: "enchant", value: "околдовать, очаровать" },
  { key: "enclose", value: "окружать, заключать" },
  { key: "encompass", value: "охватывать, заключать" },
  { key: "encounter", value: "встретиться, столкнуться" },
  { key: "encourage", value: "поддерживать, поощрять" },
  { key: "end up", value: "заканчивать чем-либо" },
  { key: "endanger", value: "подвергать опасности" },
  { key: "endeavor (endeavour)", value: "стремиться, стараться, попытка" },
  { key: "endorse", value: "одобрять, поддерживать" },
  { key: "endow", value: "наделять, даровать" },
  { key: "endure", value: "выдерживать" },
  { key: "enforce", value: "внедрить, навязать" },
  { key: "engage in", value: "заниматься, вступать, вовлекать" },
  { key: "engaged", value: "помолвленный (-ая)" },
  { key: "engender", value: "зарождать, порождать" },
  { key: "engine", value: "двигатель или машина" },
  { key: "enhance", value: "повысить, усилить, расширить" },
  { key: "enlarge", value: "увеличить, расширить" },
  { key: "enlighten", value: "просветить" },
  { key: "enlist", value: "привлечь (к делу)" },
  { key: "enormous", value: "огромный" },
  { key: "enrich", value: "обогащать" },
  { key: "enrol (enroll)", value: "записать (в члены), набрать" },
  { key: "ensemble", value: "ансамбль" },
  { key: "ensue", value: "следовать, вытекать" },
  { key: "ensure", value: "обеспечить, гарантировать" },
  { key: "entail", value: "влечь за собой, подразумевать" },
  { key: "enter", value: "войти" },
  { key: "enterprise", value: "предприятие, предпринимательство" },
  { key: "entertain", value: "развлекать" },
  { key: "entice", value: "соблазнять" },
  { key: "entire", value: "весь, целый" },
  { key: "entitle", value: ["давать название", "давать право (по заслугам)"] },
  { key: "entity", value: "сущность" },
  { key: "entrepreneur", value: "предприниматель" },
  { key: "envelope", value: "конверт" },
  { key: "environment", value: "среда, окружение" },
  { key: "envision", value: "воображать" },
  { key: "envy", value: "зависть" },
  { key: "equal", value: "равный, равняться" },
  { key: "equation", value: "уравнение" },
  { key: "equip", value: "оснащать, снаряжать" },
  { key: "equity", value: "равноправие, справедливость" },
  { key: "eradicate", value: "уничтожить, искоренить" },
  { key: "erase", value: "стирать" },
  { key: "erect", value: "воздвигнуть, соорудить" },
  { key: "erode", value: "размывать, выветривать" },
  { key: "errand", value: "поручение" },
  { key: "error", value: "ошибка" },
  { key: "erupt", value: "извергаться" },
  { key: "escape", value: "избежать, спастись" },
  { key: "essence", value: "сущность" },
  { key: "essential", value: "необходимый" },
  { key: "establish", value: "установить, учредить" },
  { key: "esteem", value: "уважать, почитать, почтение" },
  { key: "estimate", value: "примерно оценивать" },
  { key: "eternal", value: "вечный" },
  { key: "evade", value: "уклоняться" },
  { key: "evaluate", value: "дать оценку" },
  { key: "evaporate", value: "испаряться" },
  { key: "eve", value: "канун" },
  { key: "even", value: "ровный" },
  { key: "event", value: "событие" },
  { key: "eventual", value: "конечный, возможный" },
  { key: "ever", value: "когда-либо" },
  { key: "evidence", value: "доказательство (неисчисл.)" },
  { key: "evident", value: "очевидный" },
  { key: "evil", value: "злой, зло" },
  { key: "evoke", value: "вызывать" },
  { key: "evolve", value: "развиваться, эволюционировать" },
  { key: "exact", value: "точный" },
  { key: "exaggerate", value: "преувеличивать" },
  { key: "examine", value: "осмотреть, изучить" },
  { key: "example", value: "пример" },
  { key: "excavate", value: "рыть, выкапывать" },
  { key: "exceed", value: "превышать" },
  { key: "excel", value: "преуспеть" },
  { key: "excellent", value: "превосходный" },
  { key: "except", value: "кроме, исключая" },
  { key: "excerpt", value: "выдержка, отрывок" },
  { key: "excess", value: "избыток, чрезмерный" },
  { key: "exchange", value: "обмен" },
  { key: "excite", value: "волновать, возбуждать" },
  { key: "exclaim", value: "восклицать" },
  { key: "exclude", value: "исключать" },
  { key: "excuse", value: "оправдание, отмазка" },
  { key: "execute", value: ["исполнить", "казнить"] },
  { key: "exempt", value: "освободить (от), освобождение" },
  { key: "exercise", value: "упражнение, тренироваться" },
  { key: "exert", value: "приложить, оказать" },
  { key: "exhale", value: "выдыхать" },
  { key: "exhaust", value: ["исчерпывать, истощать", "выхлопные газы"] },
  { key: "exhibit", value: "выставлять, показывать" },
  { key: "exile", value: "ссылка, изгнание" },
  { key: "exist", value: "существовать" },
  { key: "exit", value: "выход, выходить" },
  { key: "expand", value: "расширять, распространять" },
  { key: "expanse", value: "пространство, простор" },
  { key: "expect", value: "ожидать (события)" },
  { key: "expel", value: "высылать, изгонять" },
  { key: "expenditure", value: "расходы" },
  { key: "expense", value: "расходы" },
  { key: "experience", value: "опыт" },
  { key: "expertise", value: "опыт, компетенция" },
  { key: "expire", value: "истекать" },
  { key: "explain", value: "объяснять" },
  { key: "explicit", value: "явный, откровенный" },
  { key: "explode", value: "взрываться" },
  { key: "exploit", value: "использовать, эксплуатировать" },
  { key: "explore", value: "изучать" },
  { key: "expose", value: "выставлять, обнажать" },
  { key: "express", value: "выражать" },
  { key: "exquisite", value: "утончённый, изысканный" },
  { key: "extend", value: "расширять, удлиннять" },
  { key: "extent", value: "степень, мера" },
  { key: "exterior", value: "внешний, внешняя сторона" },
  { key: "external", value: "внешний" },
  { key: "extinct", value: "вымерший" },
  { key: "extinguish", value: "погасить" },
  { key: "extort", value: "вымогать" },
  { key: "extra", value: "дополнительный" },
  { key: "extract", value: "извлекать" },
  { key: "extreme", value: "крайний" },
  { key: "exuberant", value: "буйный, энергичный" },
  { key: "eyebrow", value: "бровь" },
  { key: "eyelid", value: "веко" },
]
