import { TDictionaryItem } from "../types"
export const f_arr: TDictionaryItem[] = [
  { key: "fable", value: "басня" },
  { key: "fabric", value: "ткань, материал" },
  { key: "fabulous", value: "невероятный, легендарный" },
  { key: "face", value: "столкнуться (перен)" },
  { key: "face up to", value: "принять (обстоятельства)" },
  { key: "facet", value: "грань, в т. ч. перен. (аспект)" },
  { key: "facial", value: "лицевой" },
  { key: "facilitate", value: "облегчать, способствовать" },
  { key: "facility", value: ["сооружение, объект", "лёгкость, удобство"] },
  { key: "faction", value: "группировка, фракция" },
  { key: "factory", value: "фабрика, завод" },
  { key: "faculty", value: "дар, способность" },
  { key: "fade", value: "увядать, блекнуть" },
  { key: "fail", value: "потерпеть неудачу" },
  { key: "failure", value: "неудача, провал" },
  { key: "faint", value: ["слабый, неуловимый", "обморок, падать в обморок"] },
  { key: "fair", value: ["светлый", "справедливый, честный"] },
  { key: "fairly", value: "довольно, вполне" },
  { key: "fairy", value: "фея" },
  { key: "faith", value: "вера" },
  { key: "fall", value: "осень (амер.)" },
  { key: "fall apart", value: "разваливаться" },
  { key: "fall asleep", value: "уснуть" },
  { key: "fall back on", value: "опереться, прибегнуть" },
  { key: "fall behind", value: "отставать" },
  { key: "fall for", value: ["вестись", "влюбляться"] },
  { key: "fall in love with", value: "влюбиться" },
  { key: "fall out", value: "ссориться" },
  { key: "fall over", value: "упасть, перевернуться" },
  { key: "fall through", value: "провалиться" },
  { key: "false", value: "ложный, неверный" },
  { key: "falter", value: "колебаться, дрогнуть" },
  { key: "fame", value: "известность, слава" },
  { key: "familiar", value: "знакомый" },
  { key: "famine", value: "голод" },
  { key: "famous", value: "знаменитый" },
  { key: "fan", value: "вентилятор" },
  { key: "fancy", value: ["необычный, причудливый, модный", "представлять, полагать"] },
  { key: "faraway", value: "далёкий" },
  { key: "fare", value: "плата за проезд" },
  { key: "farewell", value: "прощальный, прощание" },
  { key: "farm", value: "ферма" },
  { key: "fascinate", value: "очаровывать" },
  { key: "fashion", value: ["мода", "стиль, образ, манер"] },
  { key: "fasten", value: "закрепить" },
  { key: "fat", value: "жир, жирный" },
  { key: "fate", value: "судьба, участь" },
  { key: "fatigue", value: "усталость, утомление" },
  { key: "faucet", value: "кран" },
  { key: "fault", value: ["недостаток, неисправность", "вина, ошибка"] },
  { key: "favor", value: "благоприятствовать" },
  { key: "favor (favour)", value: "услуга" },
  { key: "fear", value: "страх, бояться" },
  { key: "feasible", value: "выполнимый, осуществимый" },
  { key: "feast", value: "праздник, пир" },
  { key: "feat", value: "подвиг, свершение" },
  { key: "feather", value: "перо" },
  { key: "feature", value: "черта, особенность" },
  { key: "fee", value: "плата" },
  { key: "feeble", value: "слабый, немощный" },
  { key: "feed (fed, fed)", value: "кормить" },
  { key: "feed on", value: "питаться" },
  { key: "feedback", value: "обратная связь" },
  { key: "feel (felt, felt)", value: "трогать, щупать" },
  { key: "feel for", value: "сочувствовать" },
  { key: "feel like", value: "хотеть" },
  { key: "fellow", value: ["парень, человек", "товарищ по чему-либо"] },
  { key: "felon", value: "преступник, уголовник" },
  { key: "female", value: "женский" },
  { key: "feminine", value: "женский" },
  { key: "fence", value: "забор, огораживать" },
  { key: "fend for (oneself)", value: "позаботиться о (себе)" },
  { key: "fend off", value: "защищаться" },
  { key: "ferocious", value: "свирепый" },
  { key: "ferry", value: "переправа, паром" },
  { key: "fertile", value: "плодородный" },
  { key: "fetch", value: "сходить принести" },
  { key: "fetus", value: "плод, эмбрион" },
  { key: "fever", value: "лихорадка, жар" },
  { key: "fibre", value: "волокно" },
  { key: "fiction", value: "вымысел, худ.литература" },
  { key: "fiddle", value: "скрипка" },
  { key: "fidelity", value: "верность" },
  { key: "field", value: "поле, область" },
  { key: "fierce", value: "свирепый" },
  { key: "fight back", value: "отбиваться" },
  { key: "fight off", value: "отбить" },
  { key: "figure", value: "полагать, думать" },
  { key: "figure out", value: "понять, придумать" },
  { key: "fill in", value: "заполнить" },
  { key: "fill in on", value: "посвятить (в подробности)" },
  { key: "fill up", value: "наполнить целиком" },
  { key: "film", value: "снимать кино" },
  { key: "filth", value: "грязь, гадость" },
  { key: "fin", value: "плавник" },
  { key: "find out", value: "выяснить" },
  { key: "fine", value: ["штраф", "тонкий", "хороший"] },
  { key: "fingertip", value: "кончик пальца" },
  { key: "fir", value: "ель" },
  { key: "firefighter", value: "пожарник" },
  { key: "fireplace", value: "камин" },
  { key: "firework", value: "фейерверк, петарда" },
  { key: "firm", value: "твёрдый" },
  { key: "fisherman", value: "рыбак" },
  { key: "fishing", value: "рыбалка" },
  { key: "fist", value: "кулак" },
  { key: "fit", value: "приступ, припадок" },
  { key: "fit (fit, fit)", value: "подходить, помещаться" },
  { key: "fit in with", value: "вписаться (в коллектив)" },
  { key: "fix", value: "исправить, наладить" },
  { key: "fixture", value: "крепление, стойка и т.д." },
  { key: "flair", value: "чутьё, талант" },
  { key: "flake", value: "слоиться, крошиться" },
  { key: "flakes", value: "хлопья" },
  { key: "flame", value: "пламя, пылать" },
  { key: "flank", value: "бок, фланг" },
  { key: "flap", value: "створка, клапан, хлопать" },
  { key: "flare", value: "вспышка, вспыхивать" },
  { key: "flash", value: "вспышка, вспыхнуть" },
  { key: "flashlight", value: "фонарик" },
  { key: "flat", value: ["плоский, ровный", "квартира"] },
  { key: "flatter", value: "льстить" },
  { key: "flavor", value: "вкус, приправлять" },
  { key: "flaw", value: "изъян" },
  { key: "flea", value: "блоха" },
  { key: "flee (fled, fled)", value: "спасаться бегством" },
  { key: "fleet", value: "флот" },
  { key: "fleeting", value: "мимолётный, скоротечный" },
  { key: "flesh", value: "плоть, мясо" },
  { key: "flex", value: "сгибать" },
  { key: "flick", value: ["короткое резкое движение", "фильм (разг.)"] },
  { key: "flick through", value: "просмотреть, пролистать" },
  { key: "flicker", value: "мерцать" },
  { key: "flight", value: ["полёт, рейс", "бегство"] },
  { key: "flight attendant", value: "бортпроводник" },
  { key: "flinch", value: "дёрнуться, дрогнуть" },
  { key: "fling (flung, flung)", value: "швырнуть" },
  { key: "flip", value: "переворачивать, перевёрнутый" },
  { key: "float", value: "плыть" },
  { key: "flock", value: "стадо, стая" },
  { key: "flood", value: "потоп, наводнение, наводнять" },
  { key: "flood in", value: "наплыть, валить потоком" },
  { key: "floor", value: ["пол", "этаж"] },
  { key: "flop", value: "провал, неудача" },
  { key: "flour", value: "мука" },
  { key: "flourish", value: "процветать" },
  { key: "flow", value: "поток, течь" },
  { key: "flu", value: "грипп" },
  { key: "fluctuate", value: "колебаться" },
  { key: "fluent", value: "беглый" },
  { key: "fluffy", value: "пушистый" },
  { key: "fluid", value: "жидкий, текучий" },
  { key: "flurry", value: "поток, шквал" },
  { key: "flush", value: ["промывать, смывать", "румянец, порозоветь"] },
  { key: "flute", value: "флейта" },
  { key: "flutter", value: "трепетать, развеваться, порхать" },
  { key: "fly", value: "муха" },
  { key: "foam", value: "пена" },
  { key: "focus", value: "сосредоточить (ся)" },
  { key: "foe", value: "недруг" },
  { key: "fog", value: "туман" },
  { key: "foil", value: ["расстаривать, разрушать", "фольга"] },
  { key: "fold", value: "сворачивать, складывать" },
  { key: "folder", value: "папка" },
  { key: "foliage", value: "листва" },
  { key: "folk", value: "люди, народ" },
  { key: "follow", value: "следовать, следить" },
  { key: "folly", value: "глупость, безумие" },
  { key: "fond of", value: "любящий" },
  { key: "fool", value: "дурак, дурачить" },
  { key: "fool around", value: "придуриваться" },
  { key: "footage", value: "запись, кадры видео" },
  { key: "footing", value: "опора, основа" },
  { key: "footprint", value: "след" },
  { key: "for real", value: "правда, серьёзно" },
  { key: "for sure", value: "наверняка, точно" },
  { key: "for the sake of", value: "ради" },
  { key: "forbid (forbade, forbidden)", value: "запрещать" },
  { key: "forcible", value: "насильственный" },
  { key: "forecast", value: "прогноз" },
  { key: "forehead", value: "лоб" },
  { key: "foreign", value: "иностранный" },
  { key: "foreman", value: "мастер, бригадир" },
  { key: "foremost", value: "передовой, первоочередной" },
  { key: "foresee", value: "предвидеть" },
  { key: "forge", value: ["ковать", "подделывать"] },
  { key: "forgive (forgave, forgiven)", value: "простить" },
  { key: "fork", value: "развилка, раздваиваться" },
  { key: "former", value: ["бывший", "первый (из названных)"] },
  { key: "formidable", value: "внушительный, грозный" },
  { key: "forth", value: "дальше, вперёд" },
  { key: "forthcoming", value: "предстоящий" },
  { key: "fortify", value: "укреплять, поддерживать" },
  { key: "fortunate", value: "удачный" },
  { key: "fortune", value: ["состояние (деньги)", "счастье, удача, судьба"] },
  { key: "fossil", value: "ископаемое" },
  { key: "foster", value: ["приёмный (ребёнок)", "способствовать, питать и т.д."] },
  { key: "foul", value: "гадкий, скверный, грязный" },
  { key: "found", value: "основать, учредить" },
  { key: "foundation", value: "фундамент" },
  { key: "fountain", value: "фонтан" },
  { key: "foyer", value: "фойе" },
  { key: "fraction", value: "доля, часть, дробь" },
  { key: "fracture", value: "перелом, разрушение" },
  { key: "fragile", value: "хрупкий" },
  { key: "fragrant", value: "душистый, ароматный" },
  { key: "frail", value: "хилый" },
  { key: "frame", value: "рамка, каркас и т.п." },
  { key: "framework", value: "каркас, основа, рамки" },
  { key: "frank", value: "откровенный" },
  { key: "frantic", value: "неистовый, бешеный" },
  { key: "fraud", value: "обман, мошенничество" },
  { key: "fray", value: "драка, бой, соревнование" },
  { key: "frayed", value: "потрёпанный" },
  { key: "freak", value: "урод" },
  { key: "freak out", value: "пугать или бесить" },
  { key: "free", value: "свободный или бесплатный" },
  { key: "free up", value: "высвободить" },
  { key: "freeway", value: "автострада" },
  { key: "freeze (froze, frozen)", value: "замораживать" },
  { key: "freight", value: "грузовой" },
  { key: "frenzy", value: "неистовство, безумие" },
  { key: "frequent", value: "частый" },
  { key: "freshen up", value: "освежить(ся)" },
  { key: "fret", value: "волновать (ся)" },
  { key: "friction", value: "трение" },
  { key: "friendly", value: "дружелюбный" },
  { key: "fright", value: "испуг" },
  { key: "frighten off", value: "отпугивать" },
  { key: "fringe", value: "край, крайний" },
  { key: "frog", value: "лягушка" },
  { key: "front", value: "перед, передний" },
  { key: "frontier", value: "граница" },
  { key: "frost", value: "мороз" },
  { key: "frown", value: "хмуриться" },
  { key: "fruitless", value: "бесплодный" },
  { key: "frustrate", value: "расстраивать (план, схему)" },
  { key: "fry", value: "жарить" },
  { key: "fuck with", value: "дразнить, шутить, злить" },
  { key: "fuel", value: "топливо, заправлять" },
  { key: "fugitive", value: "беглец" },
  { key: "fulfil", value: "исполнить" },
  { key: "fumble", value: "щупать, лапать, мять и т. д." },
  { key: "fume", value: "дым, испарение" },
  { key: "fund", value: "фонд, финансировать" },
  { key: "funeral", value: "похороны, похоронный" },
  { key: "fungus", value: "гриб, грибок" },
  { key: "funnel", value: "воронка" },
  { key: "fur", value: "мех" },
  { key: "furnace", value: "печь" },
  { key: "furnish", value: ["предоставлять", "обставлять, меблировать"] },
  { key: "furniture", value: "мебель" },
  { key: "further", value: "дальнейший, далее" },
  { key: "fury", value: "ярость, бешенство" },
  { key: "fuse", value: "плавиться, сливаться" },
  { key: "fuss", value: "суетиться" },
  { key: "futile", value: "тщетный, напрасный" },
  { key: "future", value: "будущий, будущее" },
  { key: "fuzzy", value: "пушистый, ворсистый" },
]
