import { TDictionaryItem } from "../types"
export const g_arr: TDictionaryItem[] = [
  { key: "gain", value: "получать, выигрывать" },
  { key: "gait", value: "походка" },
  { key: "gala", value: "праздник, торжество" },
  { key: "gamble", value: "азартная игра, играть" },
  { key: "gang", value: "банда, шайка" },
  { key: "gap", value: "разрыв, пробел" },
  { key: "garbage", value: "мусор (особ. пищевой)" },
  { key: "garden", value: "сад" },
  { key: "garlic", value: "чеснок" },
  { key: "garment", value: "предмет одежды" },
  { key: "garnish", value: "гарнир, украшение" },
  { key: "gas", value: "бензин" },
  { key: "gasp", value: "задыхаться, ловить воздух" },
  { key: "gates", value: "ворота" },
  { key: "gather", value: "собирать (ся)" },
  { key: "gauge", value: "измерить, изм. прибор" },
  { key: "gaze", value: "пристально глядеть" },
  { key: "gear", value: "механизм, привод, передача" },
  { key: "geared to", value: "направлен на" },
  { key: "gem", value: "(полу)драгоценный камень" },
  { key: "gender", value: "пол" },
  { key: "gene", value: "ген" },
  { key: "general", value: "общий" },
  { key: "generation", value: "поколение" },
  { key: "generous", value: "великодушный, щедрый" },
  { key: "gentle", value: "мягкий, тихий, нежный и т. д." },
  { key: "genuine", value: "подлинный, настоящий" },
  { key: "germ", value: "микроб или зародыш" },
  { key: "gesture", value: "жест, жестикулировать" },
  { key: "get", value: "становиться" },
  { key: "get about", value: "передвигаться (на чём-то)" },
  { key: "get ahead", value: "преуспевать, продвигаться" },
  { key: "get ahead of", value: "обогнать" },
  { key: "get along", value: "ладить" },
  { key: "get at", value: "клонить, намекать" },
  { key: "get away with", value: "безнаказанно сделать" },
  { key: "get back at", value: "отомстить" },
  { key: "get by", value: "обойтись, протянуть" },
  { key: "get down", value: "приступить" },
  { key: "get in", value: "прибывать (о транспорте)" },
  { key: "get lost", value: "пропасть" },
  { key: "get off", value: "выходить (из транспорта)" },
  { key: "get off with", value: "отделаться чем-либо" },
  { key: "get on", value: "быть, делать" },
  { key: "get out of", value: "избежать, отмазаться" },
  { key: "get over", value: "пережить, принять" },
  { key: "get rid of", value: "избавиться от" },
  { key: "get stuck", value: "застрять" },
  { key: "get through", value: "дозвониться" },
  { key: "get together", value: "собираться" },
  { key: "get used to", value: "привыкнуть" },
  { key: "ghost", value: "привидение" },
  { key: "giant", value: "гигантский" },
  { key: "gift", value: "подарок" },
  { key: "giggle", value: "хихикать, хихиканье" },
  { key: "give a ride", value: "подвезти" },
  { key: "give away", value: ["раздавать, дарить", "выдать (раскрыть)"] },
  { key: "give birth to", value: "родить" },
  { key: "give off", value: "издавать, испускать" },
  { key: "give out", value: "раздать, выдать" },
  { key: "give up", value: ["отказаться, сдаться", "бросить (привычку)"] },
  { key: "glacier", value: "ледник" },
  { key: "glamour", value: "очарование, привлекательность" },
  { key: "glance", value: "взгляд" },
  { key: "glare", value: "яркий свет, ослеплять" },
  { key: "glass", value: "стекло или стакан" },
  { key: "glasses", value: "очки" },
  { key: "glaze", value: "глазурь, глянец" },
  { key: "gleam", value: "блеск, отблеск" },
  { key: "glide", value: "скользить, планировать" },
  { key: "glimpse", value: "вид (мельком или уголком)" },
  { key: "glint", value: "вспыхнуть, сверкнуть (слегка)" },
  { key: "glitter", value: "блеск, блестеть, сверкать" },
  { key: "globe", value: "мир, земной шар" },
  { key: "gloom", value: "сумрак, уныние" },
  { key: "glory", value: "слава, сияние" },
  { key: "gloss", value: "глянец, лоск" },
  { key: "glove", value: "перчатка" },
  { key: "glow", value: "сияние, свечение" },
  { key: "glue", value: "клей, клеить" },
  { key: "gnaw on", value: "грызть, обгладывать" },
  { key: "go  about", value: "заниматься (делами)" },
  { key: "go  against", value: "противоречить" },
  { key: "go  ahead", value: "взять (и сделать)" },
  { key: "go  along", value: "поддерживать, соглашаться" },
  { key: "go  bad", value: "испортиться" },
  { key: "go  down", value: "быть принятым" },
  { key: "go  for", value: ["быть проданным за", "выбирать, предпочитать"] },
  { key: "go  into", value: "вдаваться" },
  { key: "go  off", value: ["сработать", "отключиться"] },
  { key: "go  on", value: ["происходить", "продолжаться"] },
  { key: "go  out", value: "погаснуть" },
  { key: "go  over", value: "просмотреть, изучить" },
  { key: "go  through", value: "просмотреть, перебрать" },
  { key: "go  together", value: "сочетаться" },
  { key: "go under", value: "разориться" },
  { key: "goal", value: "цель" },
  { key: "goat", value: "козел, коза" },
  { key: "goddess", value: "богиня" },
  { key: "goods", value: "товары" },
  { key: "goof", value: "балбес, придурок (амер.)" },
  { key: "gorgeous", value: "шикарный" },
  { key: "gospel", value: "евангелие" },
  { key: "gossip", value: "слухи" },
  { key: "govern", value: "управлять" },
  { key: "gown", value: "платье" },
  { key: "grab", value: "схватить, нахапать и т.д." },
  { key: "grace", value: "благодать, милость" },
  { key: "grade", value: ["оценка", "класс, уровень"] },
  { key: "gradual", value: "постепенный" },
  { key: "graduate", value: "выпускник, выпускаться" },
  { key: "grain", value: "зерно, крупица" },
  { key: "grand", value: "большой, великий" },
  { key: "grant", value: "давать, дарить" },
  { key: "grape", value: "виноград (ягода)" },
  { key: "graph", value: "график" },
  { key: "grapple", value: "сцепиться, бороться" },
  { key: "grasp", value: "схватывать" },
  { key: "grate", value: "решетка" },
  { key: "grateful", value: "благодарный" },
  { key: "gratify", value: "удовлетворять, радовать" },
  { key: "gratitude", value: "благодарность" },
  { key: "grave", value: ["могила", "серьёзный"] },
  { key: "gravel", value: "гравий" },
  { key: "gravy", value: "подливка, соус" },
  { key: "graze", value: "пасти(сь)" },
  { key: "grease", value: "смазка, жир" },
  { key: "greed", value: "жадность" },
  { key: "greenhouse", value: "теплица, оранжерея" },
  { key: "greet", value: "приветствовать" },
  { key: "grid", value: "сетка, решётка" },
  { key: "grief", value: "горе" },
  { key: "grievance", value: "обида" },
  { key: "grieve", value: "горевать" },
  { key: "grim", value: "мрачный, зловещий" },
  { key: "grin", value: "ухмыляться, ухмылка, оскал" },
  { key: "grind (ground, groud)", value: "молоть, измельчать" },
  { key: "grip", value: "хватать, захват, хватка" },
  { key: "grit", value: ["крошка, песок, гравий", "твёрдость, стойкость"] },
  { key: "groan", value: "стон, стонать" },
  { key: "grocery", value: "продуктовый" },
  { key: "groom", value: "жених" },
  { key: "groove", value: "канавка, желоб" },
  { key: "grope", value: "щупать, искать вслепую" },
  { key: "gross", value: ["валовой, грязный", "грубый (во всех смыслах)"] },
  { key: "grove", value: "лесок" },
  { key: "grow (grew, grown)", value: ["становиться", "расти или выращивать"] },
  { key: "grow up", value: "вырастать" },
  { key: "growl", value: "рычать" },
  { key: "grudge", value: "обида, злоба" },
  { key: "grumble", value: "ворчать, жаловаться" },
  { key: "grunt", value: "хрюкать" },
  { key: "guard", value: "сторожить, стража" },
  { key: "guess", value: "угадывать, догадываться" },
  { key: "guest", value: "гость" },
  { key: "guide", value: "вести, направлять" },
  { key: "guideline", value: "общее правило, принцип" },
  { key: "guilt", value: "вина" },
  { key: "guise", value: "облик, личина" },
  { key: "gulf", value: ["разрыв, пропасть", "залив"] },
  { key: "gulp", value: "большой глоток, заглатывать" },
  { key: "gum", value: "жвачка" },
  { key: "gun", value: "огнестрельное оружие" },
  { key: "gust", value: "порыв" },
  { key: "gut", value: "кишка" },
  { key: "gutter", value: "желоб, сток" },
  { key: "gym", value: "спортзал" },
  { key: "Gypsy", value: "цыган, цыганский" },
]
