import { TDictionaryItem } from "../types"
export const h_arr: TDictionaryItem[] = [
  { key: "habit", value: "привычка, обычай" },
  { key: "habitat", value: "среда, место обитания" },
  { key: "hack", value: "рубить, кромсать" },
  { key: "hail", value: ["град", "окликнуть, привлечь внимание", "приветствовать"] },
  { key: "haircut", value: "стрижка, причёска" },
  { key: "hall", value: "зал, вестибюль" },
  { key: "hallmark", value: "характерная черта" },
  { key: "halt", value: "останавливаться" },
  { key: "halve", value: "делить пополам" },
  { key: "ham", value: "ветчина" },
  { key: "hammer", value: "молоток" },
  { key: "hamper", value: "затруднять, ограничивать" },
  { key: "hand down", value: "передать (по наследству)" },
  { key: "hand in", value: "сдать" },
  { key: "hand over", value: "передать" },
  { key: "handbook", value: "руководство, справочник" },
  { key: "handcuffs", value: "наручники" },
  { key: "handful", value: "горсть" },
  { key: "handicap", value: "помеха, недостаток" },
  { key: "handkerchief", value: "носовой платок" },
  { key: "handle", value: ["рукоятка", "управляться, обращаться"] },
  { key: "handsome", value: "красивый (обычно о мужчинах)" },
  { key: "handwriting", value: "почерк" },
  { key: "handy", value: "удобный" },
  { key: "hang (hung, hung)", value: "висеть, вешать" },
  { key: "hang around", value: "зависать, слоняться" },
  { key: "hang out", value: "тусоваться где-то" },
  { key: "hangover", value: "похмелье" },
  { key: "happen", value: "случиться, происходить" },
  { key: "harass", value: "тревожить, изводить" },
  { key: "harbor (harbour)", value: "гавань, порт" },
  { key: "hardly", value: "едва" },
  { key: "hardware", value: "аппаратные средства" },
  { key: "hardy", value: "выносливый" },
  { key: "harm", value: "вред, вредить" },
  { key: "harness", value: "запрягать, обуздывать" },
  { key: "harp", value: "арфа" },
  { key: "harsh", value: "резкий, суровый, грубый" },
  { key: "harvest", value: "урожай, собирать урожай" },
  { key: "hassle", value: "трудность, неудобство" },
  { key: "haste", value: "спешка" },
  { key: "hat", value: "шляпа" },
  { key: "hatch", value: "люк" },
  { key: "hatred", value: "ненависть" },
  { key: "haul", value: "тащить, тянуть, буксировать" },
  { key: "haunt", value: "являться, преследовать (перен.)" },
  { key: "hawk", value: "ястреб" },
  { key: "hay", value: "сено" },
  { key: "hazard", value: "опасность, риск, угроза" },
  { key: "haze", value: "дымка, туман" },
  { key: "head for", value: "направляться" },
  { key: "head off", value: "выйти, отправиться" },
  { key: "headlight", value: "передняя фара" },
  { key: "headline", value: "заголовок" },
  { key: "headquarters", value: "штаб-квартира" },
  { key: "heal", value: "лечить, заживать" },
  { key: "health", value: "здоровье" },
  { key: "healthcare", value: "здравоохранение" },
  { key: "heap", value: "куча" },
  { key: "heat", value: "тепло, нагревать" },
  { key: "heat up", value: "разогреть" },
  { key: "heave", value: "вздыматься" },
  { key: "heaven", value: "небеса" },
  { key: "hebrew", value: "еврейский" },
  { key: "hectic", value: "беспокойный, напряжённый" },
  { key: "hedge", value: "живая изгородь" },
  { key: "heed", value: "прислушиваться, учитывать" },
  { key: "heel", value: "каблук, пятка" },
  { key: "hefty", value: "большой и тяжёлый" },
  { key: "height", value: "высота, рост" },
  { key: "heir", value: "наследник" },
  { key: "helicopter", value: "вертолёт" },
  { key: "helm", value: "руль, штурвал" },
  { key: "helmet (helm)", value: "шлем" },
  { key: "help out", value: "выручить" },
  { key: "helpful", value: "полезный" },
  { key: "helpless", value: "беспомощный" },
  { key: "hemisphere", value: "полушарие" },
  { key: "hen", value: "курица" },
  { key: "hence", value: "отсюда (следует, происходит)" },
  { key: "herald", value: "возвестить, вестник" },
  { key: "herb", value: "трава" },
  { key: "herd", value: "стадо, пасти" },
  { key: "heritage", value: "наследие" },
  { key: "hero", value: "герой" },
  { key: "hesitate", value: "колебаться, медлить" },
  { key: "hide (hid, hidden)", value: "скрывать" },
  { key: "hideous", value: "отвратительный, ужасный" },
  { key: "hierarchy", value: "иерархия" },
  { key: "high-end", value: "высококлассный, лидирующий" },
  { key: "highlight", value: "выделить, подсветить" },
  { key: "highway", value: "шоссе" },
  { key: "hijack", value: "угонять" },
  { key: "hike", value: "поход, ходить в поход" },
  { key: "hilarious", value: "веселый, забавный, смешной" },
  { key: "hill", value: "холм" },
  { key: "hinder", value: "мешать, затруднять" },
  { key: "hinge", value: "петля, шарнир" },
  { key: "hint", value: "намёк, намекать" },
  { key: "hip", value: "таз, поясница" },
  { key: "hire", value: "нанимать" },
  { key: "hiss", value: "шипеть" },
  { key: "hit (hit, hit)", value: ["ударить, удар", "попасть, достичь"] },
  { key: "hit back", value: "отыграться, отбиться" },
  { key: "hit on", value: "клеить, подкатывать" },
  { key: "hitch", value: "заминка, помеха" },
  { key: "hoard", value: "копить, накопление, клад" },
  { key: "hobble", value: "прихрамывать" },
  { key: "hog", value: "большой свин, боров" },
  { key: "hoist", value: "поднимать" },
  { key: "hold back", value: "сдерживать" },
  { key: "hold on", value: ["оставаться на линии", "держаться"] },
  { key: "hold up", value: "задержать, затормозить" },
  { key: "hole", value: "дыра" },
  { key: "holler", value: "крикнуть, окликнуть" },
  { key: "hollow", value: "полый" },
  { key: "holy", value: "святой, священный" },
  { key: "homeland", value: "родина" },
  { key: "homicide", value: "убийство" },
  { key: "honest", value: "честный" },
  { key: "honey", value: "мёд" },
  { key: "honor (honour)", value: "честь, чтить" },
  { key: "hood", value: ["капот, кожух", "капюшон"] },
  { key: "hoof", value: "копыто" },
  { key: "hook", value: "крюк, зацеплять" },
  { key: "hook up", value: ["потрахаться", "подключить, смонтировать"] },
  { key: "hoop", value: "обруч, обод" },
  { key: "hop", value: "прыгать, скакать" },
  { key: "hopeful", value: "внушающий надежды" },
  { key: "horizon", value: "горизонт, кругозор" },
  { key: "horn", value: "рог" },
  { key: "horrible", value: "ужасный, отвратительный" },
  { key: "horrify", value: "ужасать" },
  { key: "horseback", value: "верхом" },
  { key: "hose", value: "шланг" },
  { key: "hospitality", value: "гостеприимство" },
  { key: "host", value: ["хозяин, быть хозяином", "множество"] },
  { key: "hostage", value: "заложник" },
  { key: "hostile", value: "враждебный, неприязненный" },
  { key: "hound", value: "охотничья собака, об. гончая" },
  { key: "household", value: "домашний, домохозяйство" },
  { key: "housewife", value: "домохозяйка" },
  { key: "hover", value: "зависнуть, парить" },
  { key: "however", value: "однако" },
  { key: "howl", value: "выть" },
  { key: "huddle", value: "столпиться, скучиться" },
  { key: "hue", value: "цвет, оттенок" },
  { key: "hug", value: "объятие, обнимать" },
  { key: "huge", value: "огромный" },
  { key: "hull", value: "корпус, оболочка" },
  { key: "hum", value: "гудеть, жужжать" },
  { key: "human", value: "человек, человеческий" },
  { key: "humble", value: "скромный, смиренный" },
  { key: "humid", value: "влажный" },
  { key: "humiliate", value: "унижать" },
  { key: "hump", value: "горб" },
  { key: "hunch", value: ["горб, горбиться", "догадка, предчуствие"] },
  { key: "hunger", value: "голод" },
  { key: "hunk", value: "ломоть, лакомый кусок" },
  { key: "hurdle", value: "препятствие" },
  { key: "hurl", value: "метать, бросать с силой" },
  { key: "hurricane", value: "ураган" },
  { key: "hurry", value: "спешить, торопиться" },
  { key: "hurt (hurt, hurt)", value: "причинять боль или болеть" },
  { key: "hush", value: "молчать" },
  { key: "hustle", value: ["толкаться, торопиться", "нечестно добыть (амер.)"] },
  { key: "hut", value: "хижина, лачуга, барак" },
  { key: "hydrogen", value: "водород" },
  { key: "hypocrite", value: "лицемер" },
]
