import { TDictionaryItem } from "../types"
export const i_arr: TDictionaryItem[] = [
  { key: "ID", value: "удостоверение личности" },
  { key: "idle", value: "праздный, бездействующий" },
  { key: "ignite", value: "воспламеняться" },
  { key: "ignorant", value: "невежественный" },
  { key: "ill", value: ["больной", "дурной, нехороший"] },
  { key: "illicit", value: "незаконный, запрещённый" },
  { key: "illuminate", value: "освещать" },
  { key: "image", value: "изображение, образ" },
  { key: "imagine", value: "вообразить" },
  { key: "immediate", value: "немедленный, непосредственный" },
  { key: "immense", value: "огромный" },
  { key: "immerse", value: "погружаться (в т. ч. перен)" },
  { key: "imminent", value: "неизбежный" },
  { key: "impact", value: "воздействие, удар" },
  { key: "impair", value: "ухудшать, ослаблять и т.д." },
  { key: "impede", value: "затруднять" },
  { key: "impending", value: "предстоящий, грозящий" },
  { key: "imperative", value: "обязательный, необходимый" },
  { key: "implement", value: "осуществлять" },
  { key: "implicate", value: "указать на причастность" },
  { key: "implicit", value: "подразумеваемый, неявный" },
  { key: "imply", value: "подразумевать" },
  { key: "importance", value: "важность" },
  { key: "impose", value: "навязывать, налагать" },
  { key: "imposing", value: "внушительный, импозантный" },
  { key: "impress", value: "впечатлить" },
  { key: "imprint", value: "отпечаток, отпечатывать" },
  { key: "improve", value: "улучшить" },
  { key: "in a row", value: "подряд" },
  { key: "in advance", value: "заранее" },
  { key: "in charge", value: "во главе" },
  { key: "in spite of", value: "несмотря на" },
  { key: "incentive", value: "стимул, мотив" },
  { key: "inch", value: "дюйм" },
  { key: "incidence", value: "частотность, распространённость" },
  { key: "incline", value: "наклонять, склонять (втч. перен)" },
  { key: "include", value: "включать, содержать в себе" },
  { key: "income", value: "доход" },
  { key: "incoming", value: "входящий" },
  { key: "incorporate", value: "вобрать, соединить" },
  { key: "increase", value: "увеличивать(ся), увеличение" },
  { key: "incredible", value: "невероятный" },
  { key: "incumbent", value: "возложенный" },
  { key: "incur", value: "навлечь, повлечь" },
  { key: "indeed", value: "в самом деле" },
  { key: "indicate", value: "указывать, означать" },
  { key: "indifferent", value: "безразличный" },
  { key: "indigenous", value: "коренной, местный" },
  { key: "induce", value: "вызывать, побуждать" },
  { key: "indulge", value: "баловать, потворствовать" },
  { key: "industry", value: "отрасль" },
  { key: "inevitable", value: "неизбежный" },
  { key: "inexplicable", value: "необъяснимый" },
  { key: "infamous", value: "печально известный, постыдный" },
  { key: "infant", value: "ребёнок" },
  { key: "infantry", value: "пехота" },
  { key: "infect", value: "заражать" },
  { key: "infer", value: "делать вывод" },
  { key: "inferior", value: "низший" },
  { key: "infinite", value: "бесконечный" },
  { key: "inflame", value: "разжигать (в осн. перен.)" },
  { key: "inflate", value: "надувать" },
  { key: "inflict", value: "причинять, наносить" },
  { key: "influence", value: "влиять, влияние" },
  { key: "infuse", value: "вливать, настаивать" },
  { key: "ingenious", value: "изобретательный" },
  { key: "inhabit", value: "населять, обитать в" },
  { key: "inhale", value: "вдыхать" },
  { key: "inherent", value: "свойственный, присущий" },
  { key: "inherit", value: "унаследовать, перенять" },
  { key: "inhibit", value: "препятствовать, затруднять" },
  { key: "initial", value: "первоначальный" },
  { key: "inject", value: "впрыскивать, вкачивать" },
  { key: "injure", value: "ранить, наносить ущерб" },
  { key: "ink", value: "чернила" },
  { key: "inland", value: "внутренний, вглубь страны" },
  { key: "inmate", value: "обитатель" },
  { key: "inn", value: "гостиница" },
  { key: "inner", value: "внутренний" },
  { key: "innocent", value: "невинный, невиновный" },
  { key: "input", value: "вход, ввод" },
  { key: "inquire", value: "узнавать, интересоваться" },
  { key: "insect", value: "насекомое" },
  { key: "insert", value: "вставить" },
  { key: "inside", value: "внутри" },
  { key: "inside out", value: "наизнанку" },
  { key: "insight", value: "понимание, догадка" },
  { key: "insist", value: "настаивать" },
  { key: "inspect", value: "проверять, осматривать" },
  { key: "inspire", value: "вдохновить, внушить" },
  { key: "install", value: "устанавливать" },
  { key: "instance", value: "пример, случай" },
  { key: "instant", value: "мгновенние, мгновенный" },
  { key: "instead", value: "вместо" },
  { key: "insulate", value: "изолировать, оградить" },
  { key: "insult", value: "оскорбление, оскорблять" },
  { key: "insure", value: "страховать, гарантировать" },
  { key: "insurgent", value: "повстанец, мятежник" },
  { key: "intact", value: "неповрежденный" },
  { key: "intake", value: "потребление, приём" },
  { key: "integral", value: "составной, неотъемлемый" },
  { key: "integrity", value: ["честность, порядочность", "целостность"] },
  { key: "intelligence", value: "разведка" },
  { key: "intelligent", value: "умный" },
  { key: "intelligible", value: "вразумительный, понятный" },
  { key: "intend", value: "намереваться" },
  { key: "intended", value: "предназначенный" },
  { key: "interact", value: "взаимодействовать" },
  { key: "intercept", value: "перехватить, перехватить" },
  { key: "intercourse", value: "отношения или пол. сношение" },
  { key: "interfere", value: "вмешиваться, мешать" },
  { key: "interim", value: "промежуточный, временный" },
  { key: "interior", value: "внутренность, внутренний" },
  { key: "intermediate", value: "промежуточный" },
  { key: "intern", value: "стажёр" },
  { key: "internal", value: "внутренний" },
  { key: "interpret", value: "истолковывать" },
  { key: "interpreter", value: "переводчик" },
  { key: "interrogate", value: "допрашивать" },
  { key: "interrupt", value: "прерывать, перебивать" },
  { key: "intersect", value: "пересекаться" },
  { key: "intervene", value: "вмешиваться" },
  { key: "intestine", value: "кишечник" },
  { key: "intimate", value: "близкий" },
  { key: "intimidate", value: "запугивать" },
  { key: "intricate", value: "сложный, запутанный" },
  { key: "intrinsic", value: "присущий, внутренний" },
  { key: "introduce", value: ["представить, познакомить", "ввести (в употребление)"] },
  { key: "intrude on", value: "вторгаться, вмешиваться" },
  { key: "invade", value: "вторгаться" },
  { key: "invent", value: "изобретать" },
  { key: "inventory", value: "опись, учёт" },
  { key: "invert", value: "переворачивать, опрокидывать" },
  { key: "investigate", value: "расследовать" },
  { key: "invite", value: "приглашать" },
  { key: "invoke", value: "взывать, призывать" },
  { key: "involve", value: ["вовлекать, увлекать", "содержать в себе (процесс)"] },
  { key: "inward", value: "внутрь" },
  { key: "iron", value: ["утюг, гладить", "железо, железный"] },
  { key: "irritate", value: "раздражать" },
  { key: "island", value: "остров" },
  { key: "issue", value: ["издать, выпустить, выпуск", "вопрос, проблема"] },
  { key: "itch", value: "зуд" },
  { key: "item", value: "пункт, номер, предмет" },
  { key: "ivory", value: "слоновая кость" },
  { key: "ivy", value: "плющ" },
]
