import { TDictionaryItem } from "../types"
export const j_arr: TDictionaryItem[] = [
  { key: "jab", value: "ударять, пихать" },
  { key: "jacket", value: "куртка, пиджак" },
  { key: "jail", value: "тюрьма" },
  { key: "janitor", value: "дворник, уборщик" },
  { key: "jar", value: "банка, кувшин и т. д." },
  { key: "jaw", value: "челюсть" },
  { key: "jealous", value: "ревнивый" },
  { key: "jelly", value: "желе" },
  { key: "jeopardy", value: "опасность (серьёзная)" },
  { key: "jerk", value: ["дёргать, резкое движение", "придурок"] },
  { key: "jet", value: ["струя", "реактивный двигатель/самолёт"] },
  { key: "Jew", value: "еврей" },
  { key: "jewel", value: "драгоценности" },
  { key: "jingle", value: "звенеть, звон" },
  { key: "jog", value: "бегать трусцой" },
  { key: "join", value: "присоединить (ся)" },
  { key: "joint", value: ["сустав, шарнир, стык и т. д.", "совместный, объединённый"] },
  { key: "jolly", value: "веселый" },
  { key: "jolt", value: "толчок, встряска" },
  { key: "journalism", value: "журналистика" },
  { key: "journey", value: "путешествие" },
  { key: "joy", value: "радость" },
  { key: "judge", value: "судья, судить (втч. перен)" },
  { key: "judicial", value: "судебная" },
  { key: "jug", value: "кувшин" },
  { key: "jumble", value: "перемешивать" },
  { key: "jump at", value: "ухватиться (за возможность)" },
  { key: "jump in", value: "вмешаться" },
  { key: "jumper", value: "джемпер" },
  { key: "junction", value: "стык, узел, пересечение" },
  { key: "junior", value: "младший" },
  { key: "junk", value: "барахло, хлам" },
  { key: "junkie", value: "наркоман" },
  { key: "jury", value: "жюри или присяжные" },
  { key: "just", value: "справедливый, беспристрастный" },
  { key: "justice", value: "правосудие, справедливость" },
  { key: "justify", value: "оправдывать, обосновывать" },
  { key: "jut", value: "выступать, выдаваться" },
]
