import { TDictionaryItem } from "../types"
export const k_arr: TDictionaryItem[] = [
  { key: "keen", value: "острый (часто перен.)" },
  { key: "keep away", value: "держать (ся) подальше" },
  { key: "keep off", value: "избегать, не трогать" },
  { key: "keep on", value: "продолжать делать" },
  { key: "keep out of", value: "не влезать" },
  { key: "keep up", value: "успевать за чем-л." },
  { key: "kernel", value: "ядро" },
  { key: "kettle", value: "чайник" },
  { key: "kick", value: "пинать" },
  { key: "kick around", value: "обсудить (разг.)" },
  { key: "kick back", value: "расслабиться" },
  { key: "kid", value: ["шутить, разыгрывать", "ребёнок"] },
  { key: "kidnap", value: "похищать" },
  { key: "kidney", value: "почка" },
  { key: "kin (pl:kin)", value: "родственник" },
  { key: "kind", value: ["добрый", "тип, вид"] },
  { key: "kindergarten", value: "детский сад" },
  { key: "kit", value: "комплект, набор" },
  { key: "kite", value: "коршун или воздушный змей" },
  { key: "kitten", value: "котенок" },
  { key: "knack", value: "умение, сноровка" },
  { key: "knee", value: "колено" },
  { key: "kneel", value: "стать на колени (колено)" },
  { key: "knight", value: "рыцарь" },
  { key: "knit", value: "вязать" },
  { key: "knob", value: "ручка (круглая)" },
  { key: "knock", value: "стучать" },
  { key: "knock down", value: "снести, сбить" },
  { key: "knock out", value: "вырубить (ударом)" },
  { key: "knock together", value: "слепить, соорудить" },
  { key: "knot", value: "узел" },
  { key: "knowledge", value: "знания" },
]
