import { TDictionaryItem } from "../types"
export const l_arr: TDictionaryItem[] = [
  { key: "label", value: "метка, ярлык, метить" },
  { key: "labour", value: "труд, трудиться" },
  { key: "lace", value: "шнурок, шнуровать" },
  { key: "lack", value: "недостаток, нуждаться" },
  { key: "lad", value: "парень" },
  { key: "ladder", value: "лестница" },
  { key: "laden", value: "груженный" },
  { key: "lag", value: "запаздывание" },
  { key: "lamb", value: "ягненок" },
  { key: "lame", value: "хромой" },
  { key: "lament", value: "оплакивать, сожалеть" },
  { key: "land", value: "приземляться, высаживаться" },
  { key: "landlord", value: "арендодатель, домовладелец" },
  { key: "landmark", value: "ориентир" },
  { key: "landscape", value: "пейзаж" },
  { key: "lane", value: "полоса дороги" },
  { key: "lantern", value: "фонарь" },
  { key: "lap", value: "колени" },
  { key: "lapse", value: ["упущение, оплошность", "промежуток времени"] },
  { key: "laptop", value: "ноутбук" },
  { key: "large", value: "большой, широкий" },
  { key: "lash (eyelash)", value: "ресница" },
  { key: "lash out", value: "нападать, ругаться" },
  { key: "last", value: "длиться" },
  { key: "latch", value: "защёлка, засов" },
  { key: "late", value: ["поздний", "покойный"] },
  { key: "lateral", value: "боковой" },
  { key: "latter", value: "последний (из названных)" },
  { key: "laugh", value: "смеяться" },
  { key: "laughter", value: "смех" },
  { key: "launch", value: "начать, запустить, запуск" },
  { key: "laundry", value: "прачечная" },
  { key: "lavish", value: "щедрый, роскошный" },
  { key: "law", value: "закон" },
  { key: "lawn", value: "газон" },
  { key: "lawsuit", value: "тяжба, судебное дело" },
  { key: "lay (laid, laid)", value: "класть, укладывать" },
  { key: "lay down", value: "установить (правило, норму)" },
  { key: "lay off", value: "уволить, сократить" },
  { key: "lay out", value: "выложить, разложить" },
  { key: "layer", value: "слой" },
  { key: "layout", value: "макет, расположение" },
  { key: "lazy", value: "ленивый" },
  { key: "lead", value: "вести" },
  { key: "lead ", value: "предшествовать" },
  { key: "leaf (pl: leaves)", value: "лист" },
  { key: "leak", value: "утечка, просачиваться, протекать" },
  { key: "lean", value: "худой" },
  { key: "lean against", value: "опереться, прислонить" },
  { key: "lean over", value: "наклониться над, через" },
  { key: "leap", value: "прыгать, прыжок" },
  { key: "lease", value: "сдавать в аренду" },
  { key: "leash", value: "привязь, поводок" },
  { key: "leather", value: "кожаный, кожа" },
  { key: "leave (left, left)", value: "уйти, покинуть" },
  { key: "leave behind", value: "оставить, забыть" },
  { key: "ledge", value: "уступ" },
  { key: "leek", value: "лук-порей" },
  { key: "leftover", value: "остаток" },
  { key: "leg", value: "нога" },
  { key: "legacy", value: "наследие, наследство" },
  { key: "legal", value: "законный, правовой" },
  { key: "legislation", value: "законодательство" },
  { key: "legitimate", value: "законный, обоснованный" },
  { key: "leisure", value: "досуг, отдых" },
  { key: "lend (lent, lent)", value: "давать в долг" },
  { key: "length", value: "длина" },
  { key: "lens", value: "линза, объектив" },
  { key: "lessen", value: "уменьшать(ся)" },
  { key: "lest", value: "чтобы не, иначе" },
  { key: "let in on", value: "посвящать (в секрет, план)" },
  { key: "let off", value: "отпустить, дать отделаться" },
  { key: "let smb down", value: "подвести" },
  { key: "let smb in", value: "впустить" },
  { key: "let up", value: "прекратиться, стихнуть" },
  { key: "letter", value: "письмо" },
  { key: "lettuce", value: "салат (латук)" },
  { key: "level", value: "уровень" },
  { key: "lever", value: "рычаг, ручка" },
  { key: "liable", value: "подлежащий" },
  { key: "liaison", value: "связь" },
  { key: "liberate", value: "освобождать" },
  { key: "liberty", value: "свобода" },
  { key: "library", value: "библиотека" },
  { key: "licence (license)", value: "разрешение" },
  { key: "lick", value: "лизать" },
  { key: "lid", value: "крышка" },
  { key: "lie", value: "лгать, ложь" },
  { key: "lie (lay, lain)", value: "лежать" },
  { key: "lifelong", value: "пожизненный" },
  { key: "lift", value: "поднимать" },
  { key: "light (lit, lit)", value: "зажигать" },
  { key: "light up", value: "осветить или загореться" },
  { key: "lightning", value: "молния" },
  { key: "like", value: "как" },
  { key: "like that", value: "так" },
  { key: "likely", value: "вероятно" },
  { key: "likewise", value: "также" },
  { key: "limb", value: "конечность" },
  { key: "limit", value: "ограничивать, ограничение" },
  { key: "limp", value: "хромать" },
  { key: "line", value: ["строка", "линия, ряд"] },
  { key: "line up", value: "встать в очередь" },
  { key: "lineage", value: "родословная" },
  { key: "linen", value: ["бельё", "льняная ткань"] },
  { key: "lineup", value: "расстановка, расположение" },
  { key: "linger", value: "задерживаться, медлить" },
  { key: "link", value: "связь, звено, ссылка" },
  { key: "lip", value: "губа" },
  { key: "lipstick", value: "губная помада" },
  { key: "liquid", value: "жидкость, жидкий" },
  { key: "list", value: "список, перечислять" },
  { key: "listen in on", value: "подслушивать" },
  { key: "literal", value: "буквальный" },
  { key: "literary", value: "литературный, книжный" },
  { key: "literate", value: "грамотность" },
  { key: "litter", value: "мусор (на улице)" },
  { key: "live up to", value: "соответствовать, дотягивать" },
  { key: "livelihood", value: "средства к существованию" },
  { key: "liven up", value: "оживить, взбодрить" },
  { key: "liver", value: "печень" },
  { key: "livestock", value: "скот" },
  { key: "lizard", value: "ящерица" },
  { key: "load", value: "грузить, груз" },
  { key: "loaf", value: "буханка, булка" },
  { key: "loan", value: "заём, ссуда" },
  { key: "loathe", value: "ненавидеть, питать отвращение" },
  { key: "lobby", value: "вестибюль, фойе, прихожая" },
  { key: "lobster", value: "омар" },
  { key: "local", value: "местный" },
  { key: "locate", value: "определить местоположение" },
  { key: "lock", value: "замок, запирать" },
  { key: "lock up", value: "посадить в тюрьму или дурку" },
  { key: "locker", value: "ящик, шкаф (закрывающийся)" },
  { key: "locus", value: "местоположение" },
  { key: "lodge", value: ["домик, поселиться, остановиться", "подавать (документ)"] },
  { key: "loft", value: "чердак, верхний нежилой этаж" },
  { key: "log", value: "бревно" },
  { key: "lone", value: "одинокий" },
  { key: "long ago", value: "давно" },
  { key: "long for", value: "желать или скучать" },
  { key: "longevity", value: "долговечность, долголетие" },
  { key: "look", value: "выглядеть" },
  { key: "look after", value: "присматривать" },
  { key: "look around", value: "посмотреть, оглядеть" },
  { key: "look at", value: "рассмотреть, обдумать" },
  { key: "look for", value: "искать" },
  { key: "look forward", value: "ожидать, предвкушать" },
  { key: "look into", value: "посмотреть, изучить" },
  { key: "look out", value: "смотреть (опасность!)" },
  { key: "look smb up", value: "найти (в списке и т. п.)" },
  { key: "look up", value: "улучшаться, налаживаться" },
  { key: "look up to", value: "уважать, восхищаться" },
  { key: "loom", value: "маячить, виднеться" },
  { key: "loop", value: "петля" },
  { key: "loose", value: "свободный, болтающийся" },
  { key: "loot", value: "грабить, добыча" },
  { key: "lord", value: "господин, господь (бог)" },
  { key: "loss", value: "потеря" },
  { key: "lot", value: "жребий, судьба" },
  { key: "loud", value: "громкий" },
  { key: "lounge", value: ["гостиная, холл, комната отдыха", "расслабляться, бездельничать"] },
  { key: "lousy", value: "паршивый" },
  { key: "lovely", value: "чудесный, милый" },
  { key: "lower", value: "нижний" },
  { key: "loyal", value: "верный, преданный" },
  { key: "lucrative", value: "прибыльный, выгодный" },
  { key: "ludicrous", value: "нелепый, смехотворный" },
  { key: "luggage", value: "багаж" },
  { key: "lumber", value: "пиломатериалы" },
  { key: "lump", value: "кусок, глыба, ком" },
  { key: "lunar", value: "лунный" },
  { key: "luncheon", value: "завтрак" },
  { key: "lung", value: "легкое" },
  { key: "lurch", value: "крениться, шататься" },
  { key: "lure", value: "приманка, манить" },
  { key: "lurk", value: "таиться" },
  { key: "lush", value: "пышный" },
  { key: "lust", value: "вожделение, страсть" },
  { key: "luxury", value: "роскошь" },
  { key: "lyrics", value: "текст песни" },
]
