import { TDictionaryItem } from "../types"
export const m_arr: TDictionaryItem[] = [
  { key: "magazine", value: "журнал" },
  { key: "magician", value: "волшебник, фокусник" },
  { key: "magnificent", value: "великолепный, величественный" },
  { key: "magnify", value: "увеличивать" },
  { key: "magnitude", value: "величина, сила" },
  { key: "maid", value: "служанка, горничная" },
  { key: "maiden", value: "дева, девственница" },
  { key: "mainland", value: "материк или большой остров" },
  { key: "maintain", value: "поддерживать, сохранять" },
  { key: "majesty", value: "величие, величество" },
  { key: "major", value: "главный, большой" },
  { key: "make fun of", value: "смеяться, издеваться" },
  { key: "make into", value: "переделать в" },
  { key: "make of", value: "извлечь, получить" },
  { key: "make out", value: ["разобрать, понять", "целоваться"] },
  { key: "make sure", value: "убедиться" },
  { key: "make up", value: ["выдумать", "помириться"] },
  { key: "make up for", value: "компенсировать, наверстать" },
  { key: "makeup", value: "макияж" },
  { key: "male", value: "мужской" },
  { key: "mall", value: "торговый центр" },
  { key: "mammal", value: "млекопитающее" },
  { key: "mammoth", value: "мамонт" },
  { key: "manage", value: "справляться, управлять" },
  { key: "mandatory", value: "обязательный" },
  { key: "manifest", value: "проявить, явный" },
  { key: "mankind", value: "человечество" },
  { key: "mansion", value: "особняк, здание" },
  { key: "mantle", value: "мантия" },
  { key: "manual", value: ["руководство, учебник", "ручной"] },
  { key: "manufacture", value: "производить, производство" },
  { key: "manure", value: "навоз" },
  { key: "map out", value: "запланировать, расписать" },
  { key: "maple", value: "клён" },
  { key: "marble", value: "мрамор" },
  { key: "margin", value: ["край, граница", "маржа, накрутка"] },
  { key: "marine", value: "морской" },
  { key: "marital", value: "супружеский" },
  { key: "maritime", value: "морской" },
  { key: "mark", value: "метка, отмечать" },
  { key: "mark down", value: "снижать ценник" },
  { key: "marry", value: "жениться, выйти замуж" },
  { key: "marsh", value: "болото" },
  { key: "martial", value: "боевой, военный" },
  { key: "martyr", value: "мученик" },
  { key: "marvel", value: "диво, удивляться" },
  { key: "mash", value: "разминать, месиво" },
  { key: "massacre", value: "резня" },
  { key: "master", value: ["хозяин", "овладеть (напр. искусством)"] },
  { key: "masterpiece", value: "шедевр" },
  { key: "mat", value: "коврик, циновка" },
  { key: "match", value: ["соответствие, нечто соответствующее", "спичка"] },
  { key: "mate", value: "товарищ, компаньон" },
  { key: "maternal", value: "материнский" },
  { key: "matter", value: ["вещество, материя", "дело, вопрос", "иметь значение"] },
  { key: "mature", value: "зрелый, зреть" },
  { key: "may", value: "пусть" },
  { key: "mayor", value: "мэр" },
  { key: "maze", value: "лабиринт" },
  { key: "meadow", value: "луг" },
  { key: "meager", value: "скудный, недостаточный" },
  { key: "meal", value: "еда" },
  { key: "mean", value: "неважный, посредственный" },
  { key: "mean (meant, meant)", value: ["иметь в виду", "означать", "предназначать"] },
  { key: "means", value: "средство" },
  { key: "meantime", value: "тем временем" },
  { key: "meanwhile", value: "тем временем" },
  { key: "measure", value: ["мера, мероприятие", "измерять, измерение"] },
  { key: "mediate", value: "посредничать" },
  { key: "medicine", value: "лекарство" },
  { key: "medieval", value: "средневековый" },
  { key: "mediocre", value: "посредственный" },
  { key: "meditate", value: "обдумывать или созерцать" },
  { key: "medium", value: "средство, способ" },
  { key: "meet (met, met)", value: "встретить или познакомиться" },
  { key: "melon", value: "дыня" },
  { key: "melt", value: "таять, плавить(ся)" },
  { key: "member", value: "член" },
  { key: "memoirs", value: "мемуары" },
  { key: "memories", value: "воспоминания" },
  { key: "memory", value: "память" },
  { key: "menace", value: "угроза, угрожать" },
  { key: "mend", value: "чинить, поправлять" },
  { key: "mental", value: "умственный" },
  { key: "mention", value: "упоминать" },
  { key: "mentor", value: "наставник" },
  { key: "merchandise", value: "товар" },
  { key: "merchant", value: "торговец, купец" },
  { key: "mercury", value: "ртуть" },
  { key: "mercy", value: "милость, милосердие" },
  { key: "mere", value: "всего лишь" },
  { key: "merge", value: "соединять, сливать" },
  { key: "merit", value: "заслуга, заслуживать" },
  { key: "merry", value: "веселый" },
  { key: "mesh", value: "сетка" },
  { key: "mess", value: "беспорядок, путаница" },
  { key: "mess up", value: "испортить, накосячить" },
  { key: "mess with", value: "возиться, связываться и т.д." },
  { key: "metropolitan", value: "столичный" },
  { key: "mid", value: "середина, полу-" },
  { key: "middle", value: "середина, средний" },
  { key: "midnight", value: "полночь" },
  { key: "midst", value: "середина, среда" },
  { key: "midwife", value: "акушерка" },
  { key: "might", value: "мощь" },
  { key: "mild", value: "мягкий" },
  { key: "mileage", value: "пробег" },
  { key: "military", value: "военный" },
  { key: "mill", value: "мельница или фабрика" },
  { key: "millennium", value: "тысячелетие" },
  { key: "mimic", value: "передразнивать, копировать" },
  { key: "mince", value: "фарш, крошить, рубить" },
  { key: "mind", value: "возражать" },
  { key: "mindful", value: "внимательный, помнящий" },
  { key: "mine", value: ["мина", "шахта, рудник"] },
  { key: "mingle", value: "смешиваться" },
  { key: "minor", value: ["второстепенный, незначительный", "несовершеннолетний"] },
  { key: "mint", value: "мята" },
  { key: "miracle", value: "чудо" },
  { key: "mischief", value: "вред, безобразие" },
  { key: "miserable", value: "несчастный, жалкий" },
  { key: "misery", value: ["нищета", "несчастье, страдание"] },
  { key: "miss", value: ["скучать", "пропускать, упустить"] },
  { key: "missile", value: "ракета" },
  { key: "missing", value: "пропавший, отсутствующий" },
  { key: "mist", value: "туман" },
  { key: "mistake", value: "ошибка" },
  { key: "mistake for", value: "принимать за" },
  { key: "mistress", value: ["госпожа, хозяйка", "любовница"] },
  { key: "mitigate", value: "смягчить, сгладить" },
  { key: "mix up", value: "перепутать" },
  { key: "mixture", value: "смесь" },
  { key: "moan", value: "стонать" },
  { key: "mob", value: "толпа (неуправляемая)" },
  { key: "mock", value: "издеваться, насмехаться" },
  { key: "mode", value: "режим, способ, вид" },
  { key: "moderate", value: "умеренный, средний" },
  { key: "modest", value: "скромный, умеренный" },
  { key: "modify", value: "видоизменять" },
  { key: "moist", value: "влажный" },
  { key: "mold (mould)", value: ["плесень", "форма, формировать"] },
  { key: "mole", value: ["крот", "родинка"] },
  { key: "molest", value: "приставать, досаждать" },
  { key: "monastery", value: "монастырь" },
  { key: "monetary", value: "валютный, денежный" },
  { key: "monk", value: "монах" },
  { key: "mood", value: "настроение" },
  { key: "moose", value: "лось" },
  { key: "mop", value: "швабра, мыть пол" },
  { key: "moreover", value: "более того" },
  { key: "moron", value: "дебил" },
  { key: "mortal", value: "смертельный, смертный" },
  { key: "mortgage", value: "ипотека" },
  { key: "mosque", value: "мечеть" },
  { key: "mosquito", value: "комар" },
  { key: "moss", value: "мох" },
  { key: "mostly", value: "в основном" },
  { key: "moth", value: "мотылёк или моль" },
  { key: "motion", value: "движение" },
  { key: "motto", value: "девиз" },
  { key: "mound", value: "насыпь, бугор" },
  { key: "mount", value: ["монтировать, устанавливать", "подниматься, забираться", "гора"] },
  { key: "mountain", value: "гора, горный" },
  { key: "mourn", value: "скорбеть, носить траур" },
  { key: "move", value: "переезжать" },
  { key: "move out", value: "съехать, выселиться" },
  { key: "move over", value: "подвинуться" },
  { key: "movie", value: "кино" },
  { key: "mow", value: "косить" },
  { key: "muck", value: "грязь, мусор, навоз" },
  { key: "mud", value: "грязь" },
  { key: "mug", value: "кружка" },
  { key: "multiple", value: "множественный, неединичный" },
  { key: "multiply", value: "умножать или размножаться" },
  { key: "multitude", value: "множество" },
  { key: "mumble", value: "бормотать, бубнить" },
  { key: "mural", value: "стенная роспись, фреска" },
  { key: "murder", value: "убийство, убивать" },
  { key: "murky", value: "мутный, тёмный" },
  { key: "murmur", value: "шум, ропот, журчание" },
  { key: "muscle", value: "мышца" },
  { key: "mushroom", value: "гриб" },
  { key: "Muslim", value: "мусульманин, мусульманский" },
  { key: "mustache (moustache)", value: "усы" },
  { key: "mustard", value: "горчица" },
  { key: "muster", value: "собрать, согнать, мобилизовать" },
  { key: "mute", value: "беззвучный, не говорящий" },
  { key: "mutter", value: "бормотать, бурчать" },
  { key: "mutual", value: "взаимный" },
  { key: "muzzle", value: "морда или намордник" },
  { key: "mystery", value: "тайна" },
]
