import { TDictionaryItem } from "../types"
export const n_arr: TDictionaryItem[] = [
  { key: "nail", value: ["гвоздь, прибивать", "ноготь"] },
  { key: "naked", value: "голый" },
  { key: "name after", value: "назвать в честь" },
  { key: "nanny", value: "няня" },
  { key: "nap", value: "вздремнуть, дремота" },
  { key: "napkin", value: "салфетка" },
  { key: "narrate", value: "повествовать, рассказывать" },
  { key: "narrow", value: "узкий" },
  { key: "nasty", value: "противный" },
  { key: "native", value: ["родной", "местный, туземный"] },
  { key: "natural", value: "естественный" },
  { key: "naughty", value: "непослушный" },
  { key: "nausea", value: "тошнота" },
  { key: "navigate", value: "ориентироваться, ходить по курсу" },
  { key: "navy", value: "военно-морской флот" },
  { key: "neat", value: "аккуратный, опрятный" },
  { key: "necessary", value: "необходимый" },
  { key: "neck", value: "шея" },
  { key: "necklace", value: "ожерелье" },
  { key: "needle", value: "игла" },
  { key: "neglect", value: "пренебрегать, не следить" },
  { key: "negligent", value: "небрежный, халатный" },
  { key: "negotiate", value: "вести переговоры" },
  { key: "neighbour", value: "сосед" },
  { key: "neither", value: ["ни один из двух", "тоже не"] },
  { key: "neither ...nor", value: "ни" },
  { key: "nephew", value: "племянник" },
  { key: "nerd", value: "ботан, задрот" },
  { key: "nerve", value: "смелость" },
  { key: "nest", value: "гнездо, гнездиться" },
  { key: "net", value: "чистый, конечный, без вычетов" },
  { key: "network", value: "сеть" },
  { key: "never", value: "так и не" },
  { key: "nevertheless", value: "тем не менее" },
  { key: "newcomer", value: "новичок" },
  { key: "newspaper", value: "газета" },
  { key: "nibble on", value: "покусывать, обгрызать" },
  { key: "niche", value: "ниша" },
  { key: "niece", value: "племянница" },
  { key: "nightmare", value: "кошмар" },
  { key: "nipple", value: "сосок" },
  { key: "nitrogen", value: "азот" },
  { key: "no matter", value: "неважно" },
  { key: "noble", value: "благородный" },
  { key: "nod", value: "кивать, склонять" },
  { key: "noise", value: "шум" },
  { key: "nominate", value: "выдвигать, номинировать" },
  { key: "none", value: "никакой, ни один" },
  { key: "nonetheless", value: "тем не менее" },
  { key: "noodles", value: "лапша" },
  { key: "noon", value: "полдень" },
  { key: "north", value: "север, северный" },
  { key: "nose around", value: "рыскать, вынюхивать" },
  { key: "nostril", value: "ноздря" },
  { key: "notch", value: "выемка" },
  { key: "note", value: "заметка, запись" },
  { key: "notice", value: "заметить" },
  { key: "notify", value: "известить" },
  { key: "notion", value: "понятие, представление" },
  { key: "notorious", value: "известный, пресловутый" },
  { key: "notwithstanding", value: "несмотря на" },
  { key: "noun", value: "существительное" },
  { key: "nourish", value: "питать, кормить, удобрять" },
  { key: "novel", value: "роман" },
  { key: "novelty", value: "новинка" },
  { key: "nuclear", value: "ядерный" },
  { key: "nude", value: "обнаженный" },
  { key: "nudge", value: "подталкивать" },
  { key: "nuisance", value: "неприятность, неудобство" },
  { key: "numb", value: "онемелый, окоченевший" },
  { key: "numeric (numerical)", value: "числовой, цифровой" },
  { key: "numerous", value: "многочисленные" },
  { key: "nun", value: "монахиня" },
  { key: "nurse", value: "медсестра, нянька" },
  { key: "nurture", value: "растить, питать" },
  { key: "nut", value: "орех" },
  { key: "nutrient", value: "питательный, пит. вещество" },
  { key: "nutrition", value: "питание" },
  { key: "nuts", value: "чокнутый" },
]
