import { TDictionaryItem } from "../types"
export const o_arr: TDictionaryItem[] = [
  { key: "oak", value: "дуб" },
  { key: "oath", value: "клятва, присяга" },
  { key: "oats", value: "овес, овсянка" },
  { key: "obedience", value: "покорность" },
  { key: "obese", value: "страдающий ожирением" },
  { key: "obey", value: "подчиняться, слушаться" },
  { key: "object", value: "возражать" },
  { key: "objective", value: "цель" },
  { key: "oblige", value: "обязывать" },
  { key: "oblique", value: "косой, наклонный" },
  { key: "obscene", value: "непристойный" },
  { key: "obscure", value: "неясный, тёмный" },
  { key: "observe", value: "наблюдать" },
  { key: "obsess", value: "овладеть (разумом)" },
  { key: "obsolete", value: "устарелый" },
  { key: "obstacle", value: "препятствие" },
  { key: "obstruct", value: "препятствовать, загромождать" },
  { key: "obtain", value: "получить, обрести" },
  { key: "obvious", value: "очевидный" },
  { key: "occasion", value: "случай, событие" },
  { key: "occupation", value: "профессия, род деятельности" },
  { key: "occupy", value: "занимать" },
  { key: "occur", value: "случиться" },
  { key: "occur to", value: "прийти в голову" },
  { key: "odd", value: "необычный, неправильный" },
  { key: "odds", value: "шансы" },
  { key: "odor (odour)", value: "запах" },
  { key: "offence", value: "обида" },
  { key: "offence (offense)", value: "преступление, нарушение" },
  { key: "offend", value: "обидеть, оскорбить" },
  { key: "offer", value: "предлагать, предложение" },
  { key: "officer", value: "служащий, должностное лицо" },
  { key: "offset", value: "смещение" },
  { key: "offspring", value: "отпрыск или всё потомство" },
  { key: "oil", value: ["масло", "нефть"] },
  { key: "ominous", value: "зловещий" },
  { key: "omit", value: "пропускать" },
  { key: "on account of", value: "в связи" },
  { key: "on behalf of", value: "от имени" },
  { key: "on foot", value: "пешком" },
  { key: "on purpose", value: "нарочно" },
  { key: "on the contrary", value: "наоборот" },
  { key: "once", value: "однажды, когда-либо" },
  { key: "ongoing", value: "происходящий, продолжающий" },
  { key: "onion", value: "лук, луковица" },
  { key: "onset", value: "начало, наступление" },
  { key: "onward (onwards)", value: "далее" },
  { key: "opaque", value: "непрозрачный" },
  { key: "opening", value: "отверстие" },
  { key: "operate", value: "управлять, работать с" },
  { key: "opinion", value: "мнение" },
  { key: "opportunity", value: "возможность" },
  { key: "oppose", value: "противостоять" },
  { key: "opposite", value: "противоположный" },
  { key: "oppress", value: "угнетать, притеснять" },
  { key: "opt for", value: "выбирать из вариантов" },
  { key: "option", value: "выбор, вариант" },
  { key: "oral", value: "устный, ротовой" },
  { key: "orchard", value: "фруктовый сад" },
  { key: "order", value: ["порядок, упорядочивать", "заказ, заказывать", "приказ"] },
  { key: "ordinary", value: "обычный" },
  { key: "oriental", value: "восточный, азиатский" },
  { key: "origin", value: "происхождение, начало" },
  { key: "original", value: "первоначальный, первоисточник" },
  { key: "orphan", value: "сирота" },
  { key: "ostensibly", value: "по видимости, якобы" },
  { key: "otherwise", value: "иначе, иным образом" },
  { key: "ought", value: "должен, обязан" },
  { key: "ounce", value: "унция" },
  { key: "out loud", value: "вслух" },
  { key: "outcome", value: "результат, исход" },
  { key: "outdated", value: "устаревший" },
  { key: "outdoor (outdoors)", value: "на улице" },
  { key: "outer", value: "внешний" },
  { key: "outfit", value: "наряд, комплект, набор" },
  { key: "outgoing", value: "уходящий" },
  { key: "outing", value: "прогулка, пикник и т. д." },
  { key: "outlaw", value: "преступник (особ. на свободе)" },
  { key: "outlet", value: "выход  (отверстие)" },
  { key: "outline", value: "контур, очертание, очертить" },
  { key: "outlook", value: "перспектива, вид,  кругозор" },
  { key: "outnumber", value: "превосходить численно" },
  { key: "output", value: "выпуск, выход" },
  { key: "outrage", value: "произвол, насилие, поругание" },
  { key: "outright", value: "прямой, откровенный" },
  { key: "outset", value: "начало" },
  { key: "outskirts", value: "окраина, окрестности" },
  { key: "outstanding", value: ["выдающийся", "неоплаченный, нерешённый"] },
  { key: "outweigh", value: "перевешивать" },
  { key: "oven", value: "печь, духовка" },
  { key: "over", value: "заново" },
  { key: "overall", value: "общий, целый" },
  { key: "overcome", value: "преодолеть, побороть" },
  { key: "overflow", value: "переполняться, разлиться" },
  { key: "overhead", value: "над головой" },
  { key: "overhear", value: "подслушать, нечаянно услышать" },
  { key: "overlap", value: "перекрываться" },
  { key: "overlook", value: "не заметить" },
  { key: "overnight", value: "ночной, с ночёвкой" },
  { key: "override", value: "перекрывать, отменять" },
  { key: "overseas", value: "за рубежом, особ. за морем" },
  { key: "oversee", value: "контролировать, надзирать" },
  { key: "oversight", value: "надзор" },
  { key: "overt", value: "явный, открытый" },
  { key: "overtake", value: "обгонять" },
  { key: "overthrow", value: "свергнуть" },
  { key: "overtime", value: "сверхурочная работа" },
  { key: "overturn", value: "опрокинуть (ся)" },
  { key: "overview", value: "обзор" },
  { key: "overwhelm", value: "завалить, подавить" },
  { key: "owe", value: ["задолжать", "быть обязанным чем-л."] },
  { key: "owl", value: "сова" },
  { key: "own", value: "владеть" },
  { key: "oxygen", value: "кислород" },
  { key: "oyster", value: "устрица" },
]
