import { TDictionaryItem } from "../types"
export const p_arr: TDictionaryItem[] = [
  { key: "pace", value: "шаг, шагать" },
  { key: "pack", value: ["пачка, связка, колода, и т. д.", "упаковывать, собирать"] },
  { key: "pad", value: ["подушечка пальца, лапы", "блокнот", "панель, клавиатура"] },
  { key: "paddle", value: "грести, весло" },
  { key: "pagan", value: "язычник" },
  { key: "pain", value: "боль" },
  { key: "pair", value: "пара" },
  { key: "pal", value: "приятель" },
  { key: "palace", value: "дворец" },
  { key: "pale", value: "бледный" },
  { key: "palm", value: "ладонь" },
  { key: "pan", value: "сковорода" },
  { key: "pancake", value: "блин, оладья" },
  { key: "pant", value: "пыхтеть, задыхаться" },
  { key: "pants", value: "штаны" },
  { key: "paper", value: "бумага, документ" },
  { key: "paperwork", value: "оформление бумаг" },
  { key: "paragraph", value: "абзац, пункт" },
  { key: "parcel", value: "посылка" },
  { key: "pardon", value: "извинять, извинение" },
  { key: "parlor", value: "приёмная, салон" },
  { key: "parrot", value: "попугай" },
  { key: "parsley", value: "петрушка" },
  { key: "part", value: ["роль", "часть, разделять(ся)"] },
  { key: "participate", value: "участвовать" },
  { key: "particle", value: "частица" },
  { key: "particular", value: "частный, конкретный" },
  { key: "partisan", value: "сторонник" },
  { key: "partition", value: "раздел" },
  { key: "part-time", value: "неполная занятость" },
  { key: "pass", value: "пройти" },
  { key: "pass away", value: "умереть" },
  { key: "pass by", value: "проходить мимо" },
  { key: "pass off as", value: "сойти, прокатить за" },
  { key: "pass out", value: "вырубиться" },
  { key: "pass smth on", value: "отдать (другому)" },
  { key: "pass up", value: "не воспользоваться шансом" },
  { key: "passage", value: "проход, коридор" },
  { key: "passenger", value: "пассажир" },
  { key: "passion", value: "страсть" },
  { key: "past", value: ["мимо", "прошлый, прошедший"] },
  { key: "pastime", value: "времяпрепровождение" },
  { key: "pastry", value: "выпечка, тесто" },
  { key: "pasture", value: "пастбище" },
  { key: "pat", value: "похлопать, потрепать" },
  { key: "patch", value: "заплатка, накладка, латать" },
  { key: "path", value: "путь" },
  { key: "pathetic", value: "жалкий" },
  { key: "patient", value: "терпеливый" },
  { key: "patio", value: "внутренний дворик" },
  { key: "patrol", value: "патруль" },
  { key: "patron", value: "покровитель" },
  { key: "pattern", value: "шаблон, образец" },
  { key: "pause", value: "приостанавливать" },
  { key: "pave", value: "вымостить" },
  { key: "paw", value: "лапа" },
  { key: "pay back", value: "вернуть деньги" },
  { key: "pay off", value: "расплатиться (с долгом)" },
  { key: "pay out", value: "выплатить (крупную сумму)" },
  { key: "payment", value: "оплата" },
  { key: "pea", value: "горошина" },
  { key: "peaceful", value: "мирный" },
  { key: "peacekeeper", value: "миротворец" },
  { key: "peach", value: "персик" },
  { key: "peanut", value: "арахис" },
  { key: "pear", value: "груша" },
  { key: "pearl", value: "жемчуг, жемчужина" },
  { key: "peasant", value: "крестьянин" },
  { key: "pebble", value: "морской камень" },
  { key: "peck", value: "клевать" },
  { key: "peculiar", value: "своеобразный, особый" },
  { key: "peddle", value: "торговать вразнос, по мелочи" },
  { key: "pedestrian", value: "пешеход" },
  { key: "pee", value: "писать" },
  { key: "peek", value: "вгзлянуть, подсмотреть" },
  { key: "peel", value: "кожура, очищать" },
  { key: "peer", value: ["ровня, ровесник", "вглядываться"] },
  { key: "peg", value: "колышек, фиксатор" },
  { key: "penalty", value: "наказание" },
  { key: "pending", value: "в ожидании, на рассмотрении" },
  { key: "penetrate", value: "проникать" },
  { key: "peninsula", value: "полуостров" },
  { key: "pepper", value: "перец" },
  { key: "per", value: "(кол-во) на (единицу)" },
  { key: "perceive", value: "воспринимать, ощущать" },
  { key: "perception", value: "восприятие" },
  { key: "perennial", value: "многолетний, вечный" },
  { key: "perfect", value: "совершенный" },
  { key: "perform", value: "выполнить, исполнить" },
  { key: "perhaps", value: "возможно" },
  { key: "peril", value: "опасность, угроза" },
  { key: "period", value: "точка (в предложении)" },
  { key: "perish", value: "погибать" },
  { key: "perk", value: "привилегия, преимущество" },
  { key: "perk up", value: "воспрянуть, оживиться" },
  { key: "permanent", value: "постоянный" },
  { key: "permit", value: "разрешать" },
  { key: "perpetual", value: "вечный, постоянный" },
  { key: "perplex", value: "смутить, озадачить" },
  { key: "persecute", value: "преследовать, травить" },
  { key: "persist", value: ["сохраниться", "упорствовать"] },
  { key: "personnel", value: "персонал, личный состав" },
  { key: "persuade", value: "убеждать" },
  { key: "pervasive", value: "расширяющийся, всепроникающий" },
  { key: "pervert", value: "извращать, извращенец" },
  { key: "pest", value: "паразит, вредитель" },
  { key: "pet", value: "домашний питомец" },
  { key: "petal", value: "лепесток" },
  { key: "petroleum", value: "нефть" },
  { key: "petty", value: "мелкий, мелочный" },
  { key: "phony", value: "фальшивый" },
  { key: "physician", value: "врач" },
  { key: "pick", value: "подбирать, собирать" },
  { key: "pick on", value: "дразнить, докучать" },
  { key: "pick out", value: "выбрать или выделить из" },
  { key: "pick up", value: ["прибрать", "подобрать"] },
  { key: "pickle", value: "мариновать, солить" },
  { key: "pie", value: "пирог" },
  { key: "piece", value: "предмет, часть, кусок" },
  { key: "pier", value: "пристань, пирс" },
  { key: "pierce", value: "проколоть" },
  { key: "pigeon", value: "голубь" },
  { key: "pile", value: "куча, стопка" },
  { key: "pile up", value: "сложить, навалить" },
  { key: "pill", value: "пилюля" },
  { key: "pillar", value: "столб, опора, колонна" },
  { key: "pillow", value: "подушка" },
  { key: "pin", value: "булавка, штырь, прикалывать" },
  { key: "pinch", value: "зажать, ущипнуть" },
  { key: "pine", value: "сосна" },
  { key: "pineapple", value: "ананас" },
  { key: "pipe", value: ["трубка", "труба"] },
  { key: "piss", value: "писать, моча" },
  { key: "piss about", value: "страдать хернёй" },
  { key: "piss off", value: "бесить" },
  { key: "pit", value: "яма" },
  { key: "pitch", value: ["подавать (мяч)", "ставить (напр. палатку)"] },
  { key: "pity", value: "жалость" },
  { key: "pivot", value: "стержень, ось, точка опоры" },
  { key: "placement", value: "размещение" },
  { key: "placid", value: "тихий, спокойный" },
  { key: "plague", value: "чума" },
  { key: "plain", value: ["ясный, очевидный", "ровный, равнина", "простой, незамысловатый"] },
  { key: "plane", value: "самолёт" },
  { key: "plank", value: "доска, планка" },
  { key: "plant", value: ["растение, сажать", "завод, производство"] },
  { key: "plaque", value: "бляшка, металлический знак" },
  { key: "plaster", value: "штукатурка или гипс" },
  { key: "plate", value: "плита, пластина" },
  { key: "plausible", value: "правдоподобный" },
  { key: "playground", value: "детская площадка" },
  { key: "plea", value: "просьба, требование, иск" },
  { key: "please", value: "радовать" },
  { key: "pleasure", value: "удовольствие, наслаждение" },
  { key: "pledge", value: ["залог, оставлять в залог", "обещание, обязательство"] },
  { key: "plenty", value: "множество, масса, достаток" },
  { key: "plight", value: "тяжёлое положение, участь" },
  { key: "plot", value: ["план, чертёж", "сюжет"] },
  { key: "plow", value: "пахать, плуг" },
  { key: "pluck", value: "сорвать, выдернуть" },
  { key: "plug", value: "штепсель, включать" },
  { key: "plug in", value: "включать" },
  { key: "plum", value: "слива" },
  { key: "plumbing", value: "водопровод" },
  { key: "plump", value: "пухлый" },
  { key: "plunge", value: "окунуться, нырнуть" },
  { key: "plural", value: "множественное число" },
  { key: "pocket", value: "карман, карманный" },
  { key: "point", value: ["смысл, суть", "точка", "очко", "острие, кончик", "пункт"] },
  { key: "point out", value: "указать" },
  { key: "poise", value: "равновесие, самообладание" },
  { key: "poison", value: "яд, травить" },
  { key: "poke", value: "совать, тыкать" },
  { key: "poke out", value: "высовывать" },
  { key: "pole", value: ["полюс", "шест, столб"] },
  { key: "policy", value: "политика, курс" },
  { key: "polish", value: "шлифовать, полировать" },
  { key: "polite", value: "вежливый" },
  { key: "poll", value: "опрос или голосование" },
  { key: "pollute", value: "загрязнять" },
  { key: "pond", value: "пруд" },
  { key: "ponder", value: "обдумывать" },
  { key: "pool", value: "бассейн" },
  { key: "poor", value: "бедный" },
  { key: "pope", value: "папа римский" },
  { key: "population", value: "население" },
  { key: "porcelain", value: "фарфор" },
  { key: "porch", value: "крыльцо, терраса, веранда" },
  { key: "pork", value: "свинина" },
  { key: "portable", value: "портативный, переносной" },
  { key: "porter", value: "носильщик или порьте" },
  { key: "portray", value: "изображать, показывать" },
  { key: "possess", value: "обладать" },
  { key: "possible", value: "возможный" },
  { key: "post", value: "почта, почтовый" },
  { key: "postpone", value: "отложить, задержать" },
  { key: "posture", value: "поза" },
  { key: "pot", value: "горшок, кастрюля" },
  { key: "potato", value: "картофель" },
  { key: "potent", value: "мощный, могущественный" },
  { key: "pouch", value: "сумочка, кошелёк" },
  { key: "poultry", value: "домашняя птица" },
  { key: "pound", value: ["фунт", "долбить, толочь"] },
  { key: "pour", value: "лить" },
  { key: "pour in (into)", value: "хлынуть, заполонить" },
  { key: "poverty", value: "бедность, нищета" },
  { key: "powder", value: "порошок" },
  { key: "powerful", value: "мощный, действенный" },
  { key: "practice", value: "практика, практиковать" },
  { key: "prairie", value: "степь, прерия" },
  { key: "praise", value: "хвалить, похвала" },
  { key: "pray", value: "молиться" },
  { key: "preach", value: "проповедовать" },
  { key: "precarious", value: "ненадёжный, шаткий" },
  { key: "precaution", value: "предосторожность" },
  { key: "precede", value: "предшествовать" },
  { key: "precious", value: "драгоценный" },
  { key: "precise", value: "точный" },
  { key: "preclude", value: "исключить, помешать" },
  { key: "predator", value: "хищник" },
  { key: "predecessor", value: "предшественник" },
  { key: "predict", value: "предсказывать" },
  { key: "predominant", value: "преобладающий" },
  { key: "prefer", value: "предпочитать" },
  { key: "pregnant", value: "беременная" },
  { key: "prejudice", value: "предубеждение, предрассудок" },
  { key: "preliminary", value: "предварительный" },
  { key: "premature", value: "преждевременный" },
  { key: "premise", value: "предпосылка" },
  { key: "premises", value: "помещение (-я)" },
  { key: "preoccupy", value: "занимать внимание" },
  { key: "prepare", value: "приготовить" },
  { key: "prescribe", value: "предписывать" },
  { key: "present", value: ["настоящее (время) ", "присутствующий, в наличии"] },
  { key: "preserve", value: "сохранять, беречь" },
  { key: "preside", value: "председательствовать" },
  { key: "press", value: "нажимать" },
  { key: "presume", value: "предполагать" },
  { key: "pretend", value: "притворяться" },
  { key: "pretext", value: "повод" },
  { key: "pretty", value: ["довольно-таки", "приятный"] },
  { key: "prevail", value: "преобладать, возобладать" },
  { key: "prevent", value: "предотвращать" },
  { key: "prevent smb from", value: "мешать" },
  { key: "previous", value: "предшествующий" },
  { key: "prey", value: "добыча" },
  { key: "prick", value: "колоть" },
  { key: "pride", value: "гордость" },
  { key: "priest", value: "жрец, священник" },
  { key: "primary", value: "первичный, главный" },
  { key: "prime", value: "важный, главный, первый" },
  { key: "primitive", value: "первобытный" },
  { key: "principal", value: "главный, основной" },
  { key: "prior", value: "предварительный, предшествующий" },
  { key: "prison", value: "тюрьма" },
  { key: "pristine", value: "нетронутый, первозданный" },
  { key: "privacy", value: "частная жизнь, конфиденциальность" },
  { key: "private", value: "частный, личный" },
  { key: "probable", value: "вероятный, возможный" },
  { key: "probe", value: ["исследовать, проверить", "датчик, зонд"] },
  { key: "procedure", value: "процедура" },
  { key: "proceed", value: "следовать, продолжать" },
  { key: "process", value: "обработать" },
  { key: "proclaim", value: "провозглашать" },
  { key: "procure", value: "достать, добыть, обеспечить" },
  { key: "prod", value: "ткнуть (чтобы сдвинуть)" },
  { key: "produce", value: "производить" },
  { key: "proficient", value: "опытный, умелый" },
  { key: "profit", value: "польза, извлекать пользу" },
  { key: "profound", value: "глубокий (перен.)" },
  { key: "prohibit", value: "запрещать" },
  { key: "prolong", value: "продлить" },
  { key: "prominent", value: "выдающийся, видный" },
  { key: "promise", value: "обещать, обещание" },
  { key: "promote", value: "поощрять, помогать" },
  { key: "prompt", value: ["побуждать, подстрекать", "быстрый, оперативный"] },
  { key: "prone", value: "склонный" },
  { key: "pronounce", value: "произносить" },
  { key: "proof", value: "доказательство (неисч.)" },
  { key: "prop", value: "подпирать, подпорка" },
  { key: "propagate", value: "размножать, распространять" },
  { key: "propel", value: "двигать, толкать" },
  { key: "proper", value: "правильный, надлежащий" },
  { key: "property", value: "собственность" },
  { key: "prophet", value: "пророк" },
  { key: "proponent", value: "сторонник, поборник" },
  { key: "propose", value: "предлагать" },
  { key: "prosecute", value: ["вести, осуществлять", "преследовать (законодательно)"] },
  { key: "prospect", value: "перспектива, вид будущего" },
  { key: "prosper", value: "процветать, преуспевать" },
  { key: "protect", value: "защищать" },
  { key: "proud", value: "гордый, гордящийся" },
  { key: "prove", value: "доказывать" },
  { key: "proverb", value: "пословица" },
  { key: "provide", value: "обеспечивать, снабжать" },
  { key: "provided", value: "при условии" },
  { key: "provisional", value: "предварительный, временный" },
  { key: "proximity", value: "близость" },
  { key: "prudent", value: "разумный, осторожный" },
  { key: "pry", value: "любопытствовать, совать нос" },
  { key: "publish", value: "публиковать, издавать" },
  { key: "puddle", value: "лужа" },
  { key: "puff", value: "дуновение, пых, клубы (дыма)" },
  { key: "pull back", value: "отступить, отвести войска" },
  { key: "pull off", value: "справиться, вытянуть" },
  { key: "pull over", value: "притормозить ненадолго" },
  { key: "pull through", value: "выжить, выкарабкаться" },
  { key: "pump", value: "насос, нагнетать" },
  { key: "pumpkin", value: "тыква" },
  { key: "punch", value: "удар (кулаком), бить" },
  { key: "punish", value: "наказывать" },
  { key: "pupil", value: "зрачок" },
  { key: "puppet", value: "кукла, марионетка" },
  { key: "puppy", value: "щенок" },
  { key: "purchase", value: "покупка, покупать" },
  { key: "pure", value: "чистый, незагрязнённый" },
  { key: "purge", value: "чистка, очищать" },
  { key: "purple", value: "пурпурный, фиолетовый" },
  { key: "purpose", value: "цель, причина" },
  { key: "purse", value: "кошелек, сумочка" },
  { key: "pursue", value: "преследовать, гнаться" },
  { key: "pursuit", value: "преследование" },
  { key: "put aside", value: "отложить" },
  { key: "put away", value: "посадить в тюрьму" },
  { key: "put in", value: "вложить" },
  { key: "put off", value: ["отвратить, отвлечь и т. д.", "откладывать"] },
  { key: "put on", value: ["надеть", "провести (мероприятие)"] },
  { key: "put out", value: ["потушить", "обременять, стеснять"] },
  { key: "put smb down", value: "подавлять, угнетать" },
  { key: "put smth down to", value: "объяснить, списать на" },
  { key: "put through", value: "подвергнуть" },
  { key: "put together", value: "собирать, соединять" },
  { key: "put up", value: "устроить (напр. драку)" },
  { key: "put up with", value: "принимать, мириться" },
  { key: "puzzle", value: "озадачить" },
]
