import { TDictionaryItem } from "../types"
export const r_arr: TDictionaryItem[] = [
  { key: "rabbit", value: "кролик" },
  { key: "race", value: ["раса", "гонка"] },
  { key: "rack", value: "стеллаж, вешалка, подставка" },
  { key: "radiate", value: "излучать" },
  { key: "raft", value: "плот" },
  { key: "rag", value: "тряпка" },
  { key: "rage", value: "ярость" },
  { key: "raid", value: "набег" },
  { key: "rail", value: "рельс, перила" },
  { key: "railway", value: "железная дорога" },
  { key: "rainbow", value: "радуга" },
  { key: "raise", value: ["растить (детей)", "поднять, повысить"] },
  { key: "raisin", value: "изюм" },
  { key: "rake", value: "грабли" },
  { key: "rally", value: ["собраться, созвать (напр. армию)", "оживать, приходить в себя"] },
  { key: "ram", value: "баран" },
  { key: "ramble", value: "бродить, блуждать" },
  { key: "ramp", value: "скат, съезд" },
  { key: "random", value: "выбранный наугад" },
  { key: "range", value: "диапазон, пределы" },
  { key: "rank", value: "ранг, разряд, звание" },
  { key: "ransom", value: "выкуп" },
  { key: "rape", value: "насиловать, изнасилование" },
  { key: "rapid", value: "быстрый" },
  { key: "rare", value: "редкий" },
  { key: "rash", value: "опрометчивый, необдуманный" },
  { key: "raspberry", value: "малина" },
  { key: "rate", value: ["курс, тариф, ставка", "показатель, уровень"] },
  { key: "rather", value: "скорее, предпочтительнее" },
  { key: "ratio", value: "соотношение, пропорции" },
  { key: "rationale", value: "основание, обоснование" },
  { key: "rattle", value: "греметь, погремушка" },
  { key: "ravage", value: "разорить, сильно повредить" },
  { key: "raw", value: "сырой, необработанный" },
  { key: "ray", value: "луч" },
  { key: "razor", value: "бритва" },
  { key: "reach", value: "достичь" },
  { key: "reach out", value: "потянуться (рукой)" },
  { key: "read out", value: "огласить, зачитать вслух" },
  { key: "read up on", value: "изучить вопрос" },
  { key: "real estate", value: "недвижимость" },
  { key: "realize", value: "понимать" },
  { key: "realm", value: "царство или область (перен.) " },
  { key: "reap", value: "пожинать" },
  { key: "rear", value: "задний" },
  { key: "reason", value: ["разум, благоразумие", "причина, мотив"] },
  { key: "rebel", value: "восставать" },
  { key: "rebound", value: "отскочить, рикошет" },
  { key: "recall", value: "вспоминать" },
  { key: "recede", value: "убывать" },
  { key: "receipt", value: ["квитанция", "получение"] },
  { key: "receive", value: "получить" },
  { key: "recent", value: "недавний, последний" },
  { key: "reception", value: "прием, приёмная" },
  { key: "recess", value: ["перерыв", "выемка, впадина"] },
  { key: "recipe", value: "рецепт" },
  { key: "recipient", value: "получатель" },
  { key: "reciprocal", value: "взаимный, ответный" },
  { key: "recite", value: "декламировать, рассказывать" },
  { key: "reckless", value: "опрометчивый, безрассудный" },
  { key: "reckon", value: "считать, рассчитывать" },
  { key: "recognize", value: "узнавать" },
  { key: "recollection", value: "воспоминание" },
  { key: "reconcile", value: "примириться" },
  { key: "record", value: "запись" },
  { key: "recount", value: "пересказать" },
  { key: "recover", value: "восстановиться, выздороветь" },
  { key: "recreation", value: "отдых и развлечения" },
  { key: "recruit", value: "набирать, вербовать" },
  { key: "rectangle", value: "прямоугольник" },
  { key: "recur", value: "повторяться, возвращаться" },
  { key: "recycle", value: "перерабатывать" },
  { key: "redeem", value: "выкупить, искупить" },
  { key: "reduce", value: "снижать" },
  { key: "redundant", value: "избыточный" },
  { key: "reed", value: "тростник, камыш" },
  { key: "reel", value: "катушка, наматывать" },
  { key: "refer", value: "сослаться, отослать" },
  { key: "refine", value: "очищать, усовершенствовать и т.д." },
  { key: "reflect", value: "отражать(ся)" },
  { key: "refrain", value: "воздерживаться" },
  { key: "refresh", value: "обновлять, освежить" },
  { key: "refrigerator", value: "холодильник" },
  { key: "refuge", value: "убежище, пристанище" },
  { key: "refugee", value: "беженец" },
  { key: "refund", value: "возврат, возмещение" },
  { key: "refuse", value: "отказаться" },
  { key: "refute", value: "опровергать" },
  { key: "regain", value: "восстановить, вернуть себе" },
  { key: "regard", value: ["внимание, уважение", "считать, рассматривать"] },
  { key: "regiment", value: "полк" },
  { key: "register", value: "касса (магазина)" },
  { key: "regret", value: "сожалеть, сожаление" },
  { key: "regular", value: "обычный" },
  { key: "rehearse", value: "репетировать" },
  { key: "reign", value: "царствовать" },
  { key: "rein", value: "сдерживать, держать в узде" },
  { key: "reinforce", value: "усилить, укрепить" },
  { key: "reject", value: "отвергать" },
  { key: "rejoice", value: "радоваться" },
  { key: "relate", value: "относиться, быть связанным" },
  { key: "relative", value: ["родственник", "относительный"] },
  { key: "relay", value: "передавать, ретранслировать" },
  { key: "release", value: "отпускать, выпускать" },
  { key: "relentless", value: "настойчивый, непрекращающийся" },
  { key: "relevant", value: "уместный, актуальный" },
  { key: "relief", value: "облегчение" },
  { key: "relieve", value: "облегчить, освободить" },
  { key: "relish", value: "наслаждаться" },
  { key: "reluctant", value: "неохотный, нежелающий" },
  { key: "rely", value: "полагаться" },
  { key: "remain", value: "оставаться" },
  { key: "remainder", value: "оставшаяся часть" },
  { key: "remains", value: "остатки, останки" },
  { key: "remark", value: "замечать, замечание" },
  { key: "remedy", value: "средство" },
  { key: "remind", value: "напомнить" },
  { key: "reminiscent", value: "напоминающий" },
  { key: "remnant", value: "остаток" },
  { key: "remorse", value: "раскаяние" },
  { key: "remote", value: "отдалённый, захолустный" },
  { key: "remove", value: "убрать, удалить" },
  { key: "render", value: ["делать, придавать свойство", "воздавать, оказывать"] },
  { key: "renew", value: "возобновлять" },
  { key: "renovate", value: "ремонтировать, обновлять" },
  { key: "renown", value: "известность, слава" },
  { key: "rent", value: "аренда, арендовать, сдавать" },
  { key: "repair", value: "ремонт, ремонтировать" },
  { key: "repay", value: "отплатить" },
  { key: "repeal", value: "отменить (закон)" },
  { key: "repel", value: "отталкивать, отражать" },
  { key: "replace", value: "заменить" },
  { key: "replicate", value: "воспроизвести" },
  { key: "reply", value: "ответ, отвечать" },
  { key: "report", value: "доклад, отчёт" },
  { key: "represent", value: "представлять" },
  { key: "repress", value: "подавлять" },
  { key: "reproduce", value: "воспроизводить" },
  { key: "request", value: "запрос, запрашивать" },
  { key: "require", value: "требовать" },
  { key: "rescue", value: "спасать, спасение" },
  { key: "research", value: "исследование, исследовать" },
  { key: "resemble", value: "походить" },
  { key: "resent", value: "огорчаться, возмущаться" },
  { key: "reserve", value: ["запас, запасной, запасать", "бронировать"] },
  { key: "reserved", value: "скрытный, замкнутый" },
  { key: "reside", value: "проживать (где-то)" },
  { key: "residue", value: "остаток" },
  { key: "resign", value: "отказываться, сдавать, уходить" },
  { key: "resilient", value: "стойкий, упругий" },
  { key: "resist", value: "сопротивляться" },
  { key: "resolute", value: "решительный, твёрдый" },
  { key: "resolve", value: ["решиться, решимость", "разрешить (ситуацию)"] },
  { key: "resort", value: "курорт" },
  { key: "resort to", value: "прибегать к" },
  { key: "respective", value: "соответственный" },
  { key: "respond", value: "отвечать" },
  { key: "response", value: "ответ, отклик" },
  { key: "responsible", value: "ответственный" },
  { key: "rest", value: ["остаток, остальное", "отдых, отдыхать", "покоиться"] },
  { key: "restore", value: "восстанавливать" },
  { key: "restrain", value: "ограничивать, удерживать" },
  { key: "restrict", value: "ограничивать" },
  { key: "result in", value: "привести к" },
  { key: "resume", value: "возобновить" },
  { key: "resurrect", value: "воскрешать" },
  { key: "retail", value: "розничная продажа" },
  { key: "retain", value: "сохранять, удерживать" },
  { key: "retaliate", value: "отплатить, отомстить" },
  { key: "retarded", value: "умственно отсталый" },
  { key: "retention", value: "удержание, сохранение" },
  { key: "retire", value: "уходить в отставку, на пенсию" },
  { key: "retract", value: "втягивать, брать обратно и т.д." },
  { key: "retreat", value: "отступать" },
  { key: "retrieve", value: "извлечь, вернуть" },
  { key: "retrospect", value: "взгляд в прошлое" },
  { key: "return", value: "возвращаться" },
  { key: "reveal", value: "раскрыть, выявить" },
  { key: "revenge", value: "месть" },
  { key: "revenue", value: "доход, выручка" },
  { key: "revere", value: "почитать" },
  { key: "reverse", value: "обратный, обратить" },
  { key: "review", value: "обзор, сделать обзор" },
  { key: "revise", value: "пересматривать, проверять" },
  { key: "revive", value: "возрождать, оживлять" },
  { key: "revolt", value: "восстание, бунт" },
  { key: "revolve", value: "вращаться" },
  { key: "reward", value: "награда, награждать" },
  { key: "rhyme", value: "рифма" },
  { key: "rib", value: "ребро" },
  { key: "ribbon", value: "лента" },
  { key: "rice", value: "рис" },
  { key: "rich", value: "богатый" },
  { key: "rid", value: "освобождать, избавлять" },
  { key: "riddle", value: "загадка" },
  { key: "ride", value: "ездить" },
  { key: "ridge", value: "хребет, ребро" },
  { key: "ridicule", value: "осмеяние" },
  { key: "ridiculous", value: "смешной, нелепый" },
  { key: "rifle", value: "винтовка" },
  { key: "rift", value: "разрыв, трещина" },
  { key: "rig", value: "установка, сооружение" },
  { key: "right away", value: "немедленно" },
  { key: "righteous", value: "праведный" },
  { key: "rigid", value: "жесткий" },
  { key: "rigorous", value: "строгий, тщательный" },
  { key: "rim", value: "край, обод" },
  { key: "ring (rang, rung)", value: "звонить, звонок" },
  { key: "rinse", value: "полоскать, полоскание" },
  { key: "riot", value: "бунт" },
  { key: "rip", value: "рвать" },
  { key: "rip off", value: "обмануть, ободрать" },
  { key: "ripe", value: "созревший" },
  { key: "ripple", value: "рябь или пульсация" },
  { key: "rise (rose, risen)", value: "подниматься, повышаться" },
  { key: "rite", value: "церемония, ритуал" },
  { key: "rival", value: "соперничающий, враждебный" },
  { key: "rivet", value: "заклёпка, приковывать, клепать" },
  { key: "roadside", value: "обочина, придорожный" },
  { key: "roadway", value: "проезжая часть" },
  { key: "roam", value: "бродить, блуждать" },
  { key: "roar", value: "рёв, реветь" },
  { key: "roast", value: "жарить" },
  { key: "rob", value: "грабить, отнимать" },
  { key: "robe", value: "халат, мантия, одеяние" },
  { key: "robust", value: "крепкий, надёжный, здоровый" },
  { key: "rock", value: ["камень, скала", "качать, трясти"] },
  { key: "rod", value: "стержень, прут" },
  { key: "rodent", value: "грызун" },
  { key: "rogue", value: "жулик, проходимец" },
  { key: "roll", value: ["рулон, клубок, свиток и т. д.", "катиться"] },
  { key: "roll up", value: "свернуть, скатать" },
  { key: "roof", value: "крыша" },
  { key: "room", value: "место, пространство" },
  { key: "root", value: "корень" },
  { key: "root out", value: "искоренить" },
  { key: "rope", value: "верёвка" },
  { key: "rope in (into)", value: "втянуть в занятие" },
  { key: "rot", value: "гнить" },
  { key: "rotate", value: ["сменять, чередовать", "вращать"] },
  { key: "rotten", value: "гнилой" },
  { key: "rough", value: "грубый, неровный, жёсткий" },
  { key: "rough up", value: "грубо обращаться, нападать" },
  { key: "round", value: "круг, круглый" },
  { key: "round down", value: "округлить (вниз)" },
  { key: "rouse", value: "будить" },
  { key: "route", value: "маршрут" },
  { key: "row", value: ["грести", "ряд"] },
  { key: "royal", value: "королевский" },
  { key: "rub", value: "тереть" },
  { key: "rubber", value: "резина, резиновый" },
  { key: "rubbish", value: "мусор (в осн. брит.)" },
  { key: "rubble", value: "щебень, обломки" },
  { key: "rude", value: "грубый, неприличный" },
  { key: "ruffle", value: "рябить, взъерошить" },
  { key: "rug", value: "коврик" },
  { key: "rugged", value: "неровный, грубый" },
  { key: "ruin", value: "разрушать, губить" },
  { key: "rule", value: ["правило", "править"] },
  { key: "ruler", value: "линейка" },
  { key: "rumble", value: "грохот, рокот" },
  { key: "rumor (rumour)", value: "слух" },
  { key: "run", value: "управлять" },
  { key: "run after", value: "гнаться за" },
  { key: "run away", value: "убежать" },
  { key: "run counter", value: "противоречить" },
  { key: "run into", value: "случайно встретить" },
  { key: "run out of", value: "исчерпать запас" },
  { key: "run over", value: "переехать машиной" },
  { key: "runaway", value: "беглый, беглец" },
  { key: "runway", value: "взлётная полоса" },
  { key: "rupture", value: "разрыв" },
  { key: "rural", value: "сельский" },
  { key: "rush", value: "торопиться, мчаться, броситься" },
  { key: "rust", value: "ржавчина" },
  { key: "rustic", value: "деревенский, простой, грубый" },
  { key: "rustle", value: "шелест" },
  { key: "rut", value: "борозда, колея, рутина" },
  { key: "ruthless", value: "беспощадный" },
]
