import { TDictionaryItem } from "../types"
export const s_arr: TDictionaryItem[] = [
  { key: "sack", value: "мешок" },
  { key: "sacred", value: "священный" },
  { key: "sacrifice", value: "жертва" },
  { key: "saddle", value: "седло" },
  { key: "safe", value: "надёжный, защищённый" },
  { key: "sail", value: "парус, плыть (о судне)" },
  { key: "saint", value: "святой" },
  { key: "salary", value: "зарплата" },
  { key: "sale", value: "продажа, сбыт" },
  { key: "salesperson", value: "продавец (в магазине)" },
  { key: "salient", value: "выступающий, заметный" },
  { key: "saliva", value: "слюна" },
  { key: "salmon", value: "лосось" },
  { key: "salt", value: "соль" },
  { key: "salvage", value: "спасти, уберечь от потери" },
  { key: "salvation", value: "спасение" },
  { key: "sample", value: "образец, часть" },
  { key: "sanctuary", value: "убежище или заповедник" },
  { key: "sand", value: "песок" },
  { key: "sane", value: "здравый, вменяемый" },
  { key: "satellite", value: "спутник" },
  { key: "satisfy", value: "удовлетворять" },
  { key: "saturated", value: "насыщенный" },
  { key: "saucepan", value: "кастрюля или сковорода" },
  { key: "saucer", value: "блюдце" },
  { key: "sausage", value: "колбаса" },
  { key: "savage", value: "дикарь, дикий (в т. ч. перен.)" },
  { key: "save up", value: "накопить" },
  { key: "savings", value: "сбережения" },
  { key: "savior", value: "спаситель" },
  { key: "savor", value: "вкус, смаковать" },
  { key: "scaffold", value: "помост" },
  { key: "scale", value: ["чешуя, шелуха", "взбираться", "масштаб, шкала"] },
  { key: "scales", value: "весы" },
  { key: "scant", value: "скудный" },
  { key: "scar", value: "шрам" },
  { key: "scarce", value: "редкий, скудный" },
  { key: "scare", value: "пугать" },
  { key: "scarf", value: "шарф" },
  { key: "scarlet", value: "алый" },
  { key: "scatter", value: "разбрасывать, рассеивать" },
  { key: "scent", value: "нюх или аромат" },
  { key: "schedule", value: "график, расписание" },
  { key: "scheme", value: "схема" },
  { key: "scholar", value: "учёный" },
  { key: "scholarship (money)", value: "стипендия" },
  { key: "science", value: "наука" },
  { key: "scissors", value: "ножницы" },
  { key: "scold", value: "ругать" },
  { key: "scoop", value: " совок, ковш, черпать" },
  { key: "scope", value: "пределы, район" },
  { key: "score", value: "счёт, очко, балл" },
  { key: "scorn", value: "презирать, презрение" },
  { key: "scour", value: "обыскать, прочесать" },
  { key: "scout", value: "разведчик" },
  { key: "scowl", value: "насупиться, рассердиться" },
  { key: "scramble", value: ["драка, схватка", "карабкаться, продираться"] },
  { key: "scrambled eggs", value: "яичница" },
  { key: "scrap", value: "обломок, обрывок" },
  { key: "scrape", value: "скрести" },
  { key: "scrape through", value: "с трудом пройти" },
  { key: "scrape together", value: "наскрести (денег)" },
  { key: "scratch", value: "царапать, царапина" },
  { key: "scream", value: "кричать, крик, вопль " },
  { key: "screech", value: "визг, скрип, хрип и т. д." },
  { key: "screenplay", value: "сценарий" },
  { key: "screw", value: ["винт, ввинчивать", "к чёрту"] },
  { key: "screw up", value: "завалить, просрать" },
  { key: "scribble", value: "криво написать, нацарапать" },
  { key: "scrub", value: "чистить, драить" },
  { key: "scrutiny", value: "внимательный осмотр, изучение" },
  { key: "scurry", value: "бежать, сновать, суетиться" },
  { key: "seal", value: ["печать, запечатывать", "тюлень"] },
  { key: "seam", value: "шов" },
  { key: "search", value: "поиски, искать" },
  { key: "seasoning", value: "приправа" },
  { key: "seat", value: "место, сиденье" },
  { key: "secular", value: "светский" },
  { key: "secure", value: "безопасный, надёжный" },
  { key: "sediment", value: "осадок" },
  { key: "seduce", value: "соблазнять" },
  { key: "see off", value: "провожать (в путь)" },
  { key: "see through", value: "довести до конца" },
  { key: "see to", value: "заняться, позаботиться" },
  { key: "seed", value: "семя, сеять" },
  { key: "seek (sought, sought)", value: "искать, стремиться" },
  { key: "seem", value: "казаться" },
  { key: "seep", value: "просачиваться, проникать" },
  { key: "segregate", value: "разделять" },
  { key: "seize", value: "схватить" },
  { key: "seldom", value: "редко" },
  { key: "select", value: "выбирать, отбирать" },
  { key: "selfish", value: "эгоистичный" },
  { key: "sell out of", value: "распродать (весь товар)" },
  { key: "send (sent, sent)", value: "отправить" },
  { key: "send out", value: "рассылать" },
  { key: "senior", value: "старший" },
  { key: "sensation", value: "ощущение" },
  { key: "sense", value: ["чувство, осознание", "смысл, значение"] },
  { key: "sensible", value: "разумный, имеющий смысл" },
  { key: "sensitive", value: "чувствительный" },
  { key: "sentence", value: ["предложение", "приговор"] },
  { key: "sentiment", value: "настроение, чувство" },
  { key: "separate", value: "отдельный, отделять" },
  { key: "sequence", value: "последовательность" },
  { key: "serene", value: "безмятежный, безоблачный" },
  { key: "series", value: "сериал" },
  { key: "sermon", value: "проповедь" },
  { key: "serve", value: ["служить", "сидеть (в тюрьме)", "подавать (блюдо)"] },
  { key: "set", value: "набор, комплект" },
  { key: "set (set, set)", value: "установить, наладить" },
  { key: "set about", value: "приступить, начать" },
  { key: "set down", value: "написать, установить" },
  { key: "set out", value: "разъяснять" },
  { key: "set out for", value: "отправиться" },
  { key: "set smb back", value: ["задержать", "обойтись в (сумму)"] },
  { key: "set smb up", value: "подставить" },
  { key: "set smb up with", value: ["устроить, организовать", "познакомить, свести"] },
  { key: "settle", value: ["уладить", "селиться"] },
  { key: "settle for", value: "согласиться на" },
  { key: "settle in", value: "освоиться" },
  { key: "settle on", value: "определиться с" },
  { key: "sever", value: "разрывать, разъединять" },
  { key: "several", value: "несколько" },
  { key: "severe", value: "серьёзный, суровый, жёсткий" },
  { key: "sew", value: "шить" },
  { key: "sewage", value: "канализация, сточные воды" },
  { key: "sex", value: "пол" },
  { key: "shabby", value: "облезлый, убогий" },
  { key: "shack", value: "лачуга, хибара, будка" },
  { key: "shade", value: ["тень", "оттенок (яркости)"] },
  { key: "shadow", value: "тень" },
  { key: "shaft", value: ["вал, ось, стержень", "шахта (напр. лифта)"] },
  { key: "shake (shook, shaken)", value: ["трясти", "пожать (руки)"] },
  { key: "shake off", value: "отделаться" },
  { key: "shake up", value: "встряхнуть, взбудоражить" },
  { key: "shallow", value: "мелкий" },
  { key: "shame", value: "стыд, позор" },
  { key: "shape", value: "форма, формировать" },
  { key: "share", value: ["делить, доля", "разделять (напр. мнение)"] },
  { key: "shareholder", value: "акционер" },
  { key: "shark", value: "акула" },
  { key: "sharp", value: "острый" },
  { key: "shatter", value: "разрушить, раздробить" },
  { key: "shave", value: "брить" },
  { key: "shed", value: "сарай, ангар и т.п." },
  { key: "shed (shed, shed)", value: "проливать, терять, сбрасывать" },
  { key: "sheep (pl:sheep)", value: "овца" },
  { key: "sheer", value: ["явный, полный, чистый", "отвесный"] },
  { key: "sheet", value: "лист" },
  { key: "shelf (pl: shelves)", value: "полка, уступ" },
  { key: "shell", value: "скорлупа, раковина, гильза" },
  { key: "shelter", value: "укрытие, убежище" },
  { key: "shepherd", value: "пастух" },
  { key: "shield", value: "щит, прикрывать" },
  { key: "shift", value: ["сменить, сдвинуть", "смена (на работе)"] },
  { key: "shimmer", value: "мерцать, переливаться" },
  { key: "shine (shone, shined)", value: "сиять, блестеть, светить" },
  { key: "ship", value: "доставлять" },
  { key: "shirt", value: "рубашка" },
  { key: "shiver", value: "дрожь, дрожать" },
  { key: "shoe", value: "туфля, ботинок (низкий)" },
  { key: "shoot (shot, shot)", value: ["стрелять", "снимать, фотографировать"] },
  { key: "shore", value: "берег" },
  { key: "shortage", value: "нехватка" },
  { key: "shoulder", value: "плечо" },
  { key: "shout", value: "кричать" },
  { key: "shove", value: "резко толкнуть, пихнуть" },
  { key: "shovel", value: "лопата или совок" },
  { key: "show around", value: "показать места" },
  { key: "show off", value: "показать всем, похвастаться" },
  { key: "show up", value: "прийти, появиться" },
  { key: "showcase", value: "витрина, демонстрировать" },
  { key: "shower", value: "душ" },
  { key: "shred", value: "мелко порубить" },
  { key: "shrewd", value: "проницательный" },
  { key: "shriek", value: "пронзительный крик, вскрикнуть" },
  { key: "shrimp", value: "креветка" },
  { key: "shrine", value: "святыня" },
  { key: "shrink (shrank, shrunk)", value: "сжаться, съёжиться" },
  { key: "shroud", value: "пелена, окутывать" },
  { key: "shrub", value: "куст" },
  { key: "shrug", value: "пожать плечами" },
  { key: "shudder", value: "содрогаться, дрожь" },
  { key: "shuffle", value: "перемешивать, тасовать" },
  { key: "shun", value: "избегать" },
  { key: "shut (shut, shut)", value: "закрыть" },
  { key: "shut out", value: "не впускать" },
  { key: "shut up", value: "заткнуться" },
  { key: "shy", value: "застенчивый" },
  { key: "siblings", value: "братья и сестры" },
  { key: "sick", value: "больной, плохо чувствующий" },
  { key: "sideline", value: "что-то вторичное" },
  { key: "sidewalk", value: "тротуар" },
  { key: "sideways", value: "вбок" },
  { key: "siege", value: "осада" },
  { key: "sift", value: "просеять" },
  { key: "sigh", value: "вздох" },
  { key: "sight", value: ["вид, поле зрения", "достопримечаетльность"] },
  { key: "sign", value: ["знак", "подпись, подписывать"] },
  { key: "sign up", value: "записаться, зарегистрироваться" },
  { key: "signature", value: "подпись" },
  { key: "significant", value: "значительный" },
  { key: "signify", value: "означать" },
  { key: "silent", value: "тихий, молчаливый" },
  { key: "silk", value: "шелк" },
  { key: "sill", value: "подоконник, порог" },
  { key: "silly", value: "глупый" },
  { key: "similar", value: "похожий" },
  { key: "simmer", value: "медленно кипятить" },
  { key: "simple", value: "простой, обычный" },
  { key: "simulate", value: "моделировать, имитировать" },
  { key: "simultaneous", value: "одновременный" },
  { key: "sin", value: "грех, грешить" },
  { key: "since", value: ["поскольку", "с (какого-то времени)"] },
  { key: "sincere", value: "искренний" },
  { key: "single", value: "один, отдельный, единый" },
  { key: "singular", value: "единственный, особый" },
  { key: "sinister", value: "зловещий" },
  { key: "sink", value: "раковина" },
  { key: "sink (sank, sunk)", value: "тонуть, топить" },
  { key: "sip", value: "глоток" },
  { key: "sit around", value: "просто сидеть" },
  { key: "sit back", value: "отсидеться" },
  { key: "sit out", value: "высидеть" },
  { key: "site", value: "местоположение" },
  { key: "situate", value: "располагать" },
  { key: "size up", value: "изучить, оценить" },
  { key: "skate", value: "конёк, кататься на коньках" },
  { key: "sketch", value: "набросок, эскиз" },
  { key: "ski", value: "ездить на лыжах" },
  { key: "skid", value: "заносить, скользить, буксовать" },
  { key: "skill", value: "умение, искусство и т. д." },
  { key: "skillet", value: "сковорода (глубокая)" },
  { key: "skim", value: "скользить (легко)" },
  { key: "skin", value: "кожа" },
  { key: "skinny", value: "тощий" },
  { key: "skip", value: "прыгать, перепрыгивать" },
  { key: "skirt", value: "юбка" },
  { key: "skull", value: "череп" },
  { key: "slab", value: "плита, блок" },
  { key: "slack", value: "расслабление, поблажка" },
  { key: "slam", value: "хлопать, ударять, захлопывать" },
  { key: "slant", value: "наклон, скос, наклонять" },
  { key: "slap", value: "шлёпать, пощечина" },
  { key: "slash", value: "рубить, хлестать, кромсать" },
  { key: "slate", value: "шифер или сланец" },
  { key: "slaughter", value: "бойня (в т. ч. перен.), забивать" },
  { key: "slave", value: "раб" },
  { key: "slay (slew, slain)", value: "умертвить" },
  { key: "sleek", value: "гладкий, лоснящийся" },
  { key: "sleep around", value: "трахаться, блудить" },
  { key: "sleeve", value: "рукав" },
  { key: "slender", value: "тонкий, стройный, изящный" },
  { key: "slice", value: "ломтик, нарезать" },
  { key: "slick", value: "скользкий" },
  { key: "slide (slid, slid)", value: "скользить" },
  { key: "slight", value: "лёгкий, слабый, незначительный" },
  { key: "slim", value: "стройный" },
  { key: "slime", value: "слизь" },
  { key: "slip", value: "скользнуть" },
  { key: "slipper", value: "тапок" },
  { key: "slippery", value: "скользкий" },
  { key: "slit", value: "щель" },
  { key: "slope", value: "склон, наклон" },
  { key: "sloppy", value: "небрежный, неряшливый" },
  { key: "slot", value: "разъём, паз, гнездо" },
  { key: "slow down", value: "замедлиться" },
  { key: "sludge", value: "осадок, отстой, ил" },
  { key: "slum", value: "трущобы" },
  { key: "slump", value: "спад, сваливаться" },
  { key: "slut", value: "шлюха" },
  { key: "sly", value: "лукавый, коварный" },
  { key: "smack", value: "шлёпнуть, хлопнуть" },
  { key: "smart", value: "умный, хитрый" },
  { key: "smash", value: "громить, разбивать" },
  { key: "smear", value: "мазать" },
  { key: "smell", value: "запах, пахнуть, нюхать" },
  { key: "smirk", value: "ухмылка" },
  { key: "smooth", value: "гладкий" },
  { key: "smother", value: "задушить" },
  { key: "smudge", value: "смазать" },
  { key: "smuggle", value: "провозить тайно" },
  { key: "snack", value: "лёгкая закуска" },
  { key: "snag", value: "коряга или загвоздка" },
  { key: "snail", value: "улитка" },
  { key: "snake", value: "змея" },
  { key: "snap", value: "щёлкать, щелчок" },
  { key: "snapshot", value: "снимок" },
  { key: "snarl", value: "рычать, огрызаться" },
  { key: "snatch", value: "схватить, утащить" },
  { key: "sneak", value: "красться" },
  { key: "sneakers", value: "кеды, кроссовки" },
  { key: "sneer", value: "усмешка, насмехаться" },
  { key: "sneeze", value: "чихать" },
  { key: "sniff", value: "нюхать, сопеть, фы и т. д." },
  { key: "snore", value: "храп, храпеть" },
  { key: "snort", value: "фыркнуть, хмыкнуть" },
  { key: "snowball", value: "снежок" },
  { key: "snug", value: "уютный, тесный" },
  { key: "so far", value: "до сих пор" },
  { key: "soak", value: "мочить, пропитывать" },
  { key: "soap", value: "мыло" },
  { key: "soar", value: "парить, взмывать (втч. о ценах)" },
  { key: "sob", value: "рыдать, всхлипывать" },
  { key: "sober", value: "трезвый" },
  { key: "sober up", value: "протрезветь" },
  { key: "so-called", value: "так называемый" },
  { key: "soccer", value: "футбол" },
  { key: "society", value: "общество" },
  { key: "sock", value: "носок" },
  { key: "socket", value: "разъем, розетка" },
  { key: "soften", value: "смягчать" },
  { key: "software", value: "программое обеспечение" },
  { key: "soil", value: "почва" },
  { key: "solar", value: "солнечный" },
  { key: "sole", value: ["единственный", "подошва"] },
  { key: "solemn", value: "торжественный, серьёзный" },
  { key: "solid", value: ["сплошной", "твёрдый, крепкий"] },
  { key: "solitary", value: "уединенный" },
  { key: "solitude", value: "одиночество" },
  { key: "solution", value: ["решение, ответ", "раствор"] },
  { key: "solve", value: "решить" },
  { key: "someday", value: "когда-нибудь" },
  { key: "somewhat", value: "слегка" },
  { key: "soon", value: "скоро или рано" },
  { key: "soot", value: "сажа" },
  { key: "soothe", value: "успокаивать" },
  { key: "sophisticated", value: "сложный, изощрённый" },
  { key: "sore", value: "больной, рана" },
  { key: "sorrow", value: "горе, скорбь" },
  { key: "sound", value: "здоровый" },
  { key: "sour", value: "кислый" },
  { key: "source", value: "источник" },
  { key: "south", value: "юг, южный" },
  { key: "sovereign", value: "суверенный" },
  { key: "sow (sowed, sown)", value: "сеять" },
  { key: "space", value: ["пространство", "космос"] },
  { key: "spade", value: "лопата" },
  { key: "span", value: "пролёт, интервал" },
  { key: "spare", value: ["щадить, избавить", "запасной, лишний", "выделить, уделить"] },
  { key: "spark", value: "искра, вспыхивать" },
  { key: "sparkle", value: "сверкать, блистать, искриться" },
  { key: "sparse", value: "редкий, разреженный" },
  { key: "spawn", value: "порождать, порождение и т. д." },
  { key: "speak out", value: "высказать" },
  { key: "speak up", value: "говорить громче" },
  { key: "spear", value: "копье" },
  { key: "special", value: "особенный, специальный" },
  { key: "species", value: "вид (биол.)" },
  { key: "specific", value: "конкретный" },
  { key: "specify", value: "указать, установить, уточнить" },
  { key: "specimen", value: "образец, экземпляр" },
  { key: "speck", value: "пятнышко, крупинка" },
  { key: "spectacle", value: "зрелище" },
  { key: "spectator", value: "зритель, наблюдатель" },
  { key: "speculate", value: "предполагать, строить догадки" },
  { key: "speed up", value: "ускориться" },
  { key: "spell", value: ["заклинание, чары", "произносить (писать) по буквам"] },
  { key: "spell out", value: "разъяснить" },
  { key: "spend (spent, spent)", value: "тратить, проводить (время)" },
  { key: "spice", value: "пряность, специя" },
  { key: "spike", value: "шип, штырь, острие, клин" },
  { key: "spill", value: "проливать, рассыпать" },
  { key: "spin", value: "крутить" },
  { key: "spine", value: "позвоночник" },
  { key: "spirit", value: "дух" },
  { key: "spit (spat, spat)", value: "плевать" },
  { key: "splash", value: "брызги, всплеск" },
  { key: "splendid", value: "великолепный, блестящий" },
  { key: "splinter", value: "шепка, осколок, заноза" },
  { key: "split (split, split)", value: "расколоться, распасться" },
  { key: "split up", value: "разделиться" },
  { key: "spoil", value: "портить" },
  { key: "spokesman", value: "представитель, прес-секретарь" },
  { key: "sponge", value: "губка" },
  { key: "spooky", value: "жуткий" },
  { key: "spot", value: ["место", "пятно", "заметить, увидеть"] },
  { key: "spotlight", value: "прожектор, центр внимания" },
  { key: "spouse", value: "супруг, супруга" },
  { key: "sprawl", value: "растягиваться, расползаться" },
  { key: "spread (spread, spread)", value: "распространять(ся)" },
  { key: "spring (sprang, sprung)", value: ["прыгать", "источник, проистекать"] },
  { key: "sprinkle", value: "побрызгать, посыпать" },
  { key: "sprout", value: "росток, прорастать" },
  { key: "spur", value: "шпора, побуждать" },
  { key: "spy(on)", value: "шпион, шпионить" },
  { key: "squad", value: "команда, отряд" },
  { key: "square", value: ["квадрат, квадратный", "площадь"] },
  { key: "squash", value: "раздавливать, расплющивать" },
  { key: "squat", value: "приседать, приземистый" },
  { key: "squeak", value: "пищать, скрипеть" },
  { key: "squeal", value: "визг, визжать" },
  { key: "squeeze", value: "сжимать" },
  { key: "squid", value: "кальмар" },
  { key: "squint", value: "щуриться или коситься" },
  { key: "squirm", value: "извиваться, ёрзать" },
  { key: "squirrel", value: "белка" },
  { key: "squirt", value: "тонкая струя" },
  { key: "stab", value: "ударить ножом, зарезать" },
  { key: "stable", value: "устойчивый" },
  { key: "stack", value: "стопка, куча, складывать" },
  { key: "staff", value: "персонал" },
  { key: "stage", value: ["сцена", "стадия, ступень"] },
  { key: "stagger", value: "шататься, колебаться" },
  { key: "stain", value: "пятно, окрашиваться, пачкать" },
  { key: "stairs", value: "ступеньки, лестница" },
  { key: "stake", value: ["стойка, кол, столб", "ставка, делать ставку"] },
  { key: "stale", value: "несвежий" },
  { key: "stalk", value: ["красться, преследовать", "стебель"] },
  { key: "stall", value: ["задержаться, застопориться", "палатка, ларёк"] },
  { key: "stamp", value: "печать, штамп, марка" },
  { key: "stance", value: "поза, положение" },
  { key: "stand", value: "терпеть, выносить" },
  { key: "stand against", value: "противостоять" },
  { key: "stand by", value: "поддерживать, быть наготове" },
  { key: "stand for", value: ["выступать за", "обозначать (в сокращении)"] },
  { key: "stand out", value: "выделяться" },
  { key: "standpoint", value: "точка зрения" },
  { key: "staple", value: "скоба, скрепка" },
  { key: "stare", value: "пялиться, пристальный взгляд" },
  { key: "stark", value: "чёткий, жёсткий, острый (об. перен.)" },
  { key: "start up", value: "основать, установить" },
  { key: "startle", value: "испугать (неожиданностью)" },
  { key: "starve", value: "голодать" },
  { key: "stash", value: "тайник, заначка,  прятать" },
  { key: "state", value: ["государство", "состояние", "заявить, отметить"] },
  { key: "stature", value: "рост" },
  { key: "statutory", value: "установленный законом" },
  { key: "stay", value: ["оставаться", "остановиться пожить"] },
  { key: "stay up", value: "не ложиться" },
  { key: "steady", value: "устойчивый" },
  { key: "steal (stole, stolen)", value: "красть" },
  { key: "stealth", value: "скрытность, хитрость" },
  { key: "steam", value: "пар" },
  { key: "steel", value: "сталь, стальной" },
  { key: "steep", value: "крутой" },
  { key: "steer", value: "управлять, направлять" },
  { key: "stellar", value: "звездный" },
  { key: "stem", value: "стебель" },
  { key: "step", value: "шаг, ступать, ступенька" },
  { key: "step down", value: "уйти в отставку" },
  { key: "step in", value: "вмешаться" },
  { key: "stern", value: "суровый, строгий" },
  { key: "stew", value: "тушить, рагу" },
  { key: "stick", value: "палка, тыкать палкой" },
  { key: "stick (stuck, stuck)", value: "приклеить" },
  { key: "stick at", value: "упорно продолжать" },
  { key: "stick out", value: "торчать, выделяться" },
  { key: "stick to", value: "придерживаться, соблюдать" },
  { key: "stick together", value: "держаться вместе" },
  { key: "stiff", value: "жёсткий, негнущийся" },
  { key: "stifle", value: "удушать" },
  { key: "still", value: "спокойный, неподвижный" },
  { key: "sting (stung, stung)", value: "жалить, жало" },
  { key: "stink (stank, stunk)", value: "вонять" },
  { key: "stir", value: "шевелить(ся), двигать и т.д." },
  { key: "stir up", value: "вызвать, возбудить" },
  { key: "stitch", value: "стежок, сшить, зашить" },
  { key: "stock", value: ["запас", "акции"] },
  { key: "stock up on", value: "запастись" },
  { key: "stocking", value: "чулок" },
  { key: "stomach", value: "желудок, живот" },
  { key: "stomp", value: "топать" },
  { key: "stool", value: "табурет" },
  { key: "stoop", value: ["крыльцо со ступеньками (амер.)", "наклоняться или сутулиться"] },
  { key: "stop over", value: "заехать, остановиться" },
  { key: "store", value: ["хранить, хранилище", "магазин"] },
  { key: "stout", value: "толстый, плотный, крепкий" },
  { key: "stove", value: "плита" },
  { key: "straight", value: "прямой, прямо" },
  { key: "straightforward", value: "простой, прямой, откровенный" },
  { key: "strain", value: "напрягать, напряжение" },
  { key: "strait", value: "пролив" },
  { key: "strand", value: ["застрять, сесть на мель", "прядь, нить (об. скрученная)"] },
  { key: "strangle", value: "придушить" },
  { key: "strap", value: "ремень" },
  { key: "straw", value: "солома" },
  { key: "strawberry", value: "клубника" },
  { key: "stray", value: "бродить, бродячий" },
  { key: "streak", value: "полоса, след, струя" },
  { key: "stream", value: "поток, ручей" },
  { key: "strength", value: "сила, мощность, прочность" },
  { key: "stress", value: "подчеркнуть, заострить внимание" },
  { key: "stretch", value: "тянуть, вытягивать" },
  { key: "strew (strewn, strewn)", value: "разбрасывать" },
  { key: "strict", value: "строгий, точный" },
  { key: "stride (strode, stridden)", value: "шагать, шаг" },
  { key: "strike", value: "забастовка" },
  { key: "strike (struck, struck)", value: "бить, удар" },
  { key: "strike out", value: "потерпеть неудачу" },
  { key: "string", value: "струна, тетива, бечева" },
  { key: "stringent", value: "строгий" },
  { key: "strip", value: ["полоса, лента", "снимать (обнажать)"] },
  { key: "stripe", value: "полоса" },
  { key: "strive (strove, striven)", value: "стремиться, добиваться" },
  { key: "stroke", value: "гладить" },
  { key: "stroll", value: "прогулка, прогуливаться" },
  { key: "struggle", value: "бороться, борьба" },
  { key: "stubborn", value: "упрямый" },
  { key: "stud", value: "шпилька" },
  { key: "stuff", value: "вещи, всякая фигня" },
  { key: "stuffy", value: "душный" },
  { key: "stumble", value: "спотыкаться, запинаться" },
  { key: "stump", value: "пень" },
  { key: "stun", value: "ошеломить, оглушить" },
  { key: "stunt", value: "трюк, выходка" },
  { key: "stupid", value: "глупый" },
  { key: "sturdy", value: "крепкий" },
  { key: "subdue", value: "подавить, укротить" },
  { key: "subject", value: ["предмет, тема", "подверженный, подвергать"] },
  { key: "sublime", value: "возвышенный, величественный" },
  { key: "submerge", value: "погружаться под воду" },
  { key: "submit", value: "подавать информацию" },
  { key: "submit to", value: "подчиниться" },
  { key: "subordinate", value: "подчиненный, подчинять" },
  { key: "subscribe", value: "подписываться" },
  { key: "subsequent", value: "последующий" },
  { key: "subside", value: "утихать, спадать" },
  { key: "subsidiary", value: "вспомогательный, дополнительный" },
  { key: "subsist", value: "существовать, прокормиться" },
  { key: "substance", value: "вещество, материя" },
  { key: "substantial", value: "существенный, значительный" },
  { key: "substantive", value: "существенный, основной" },
  { key: "substitute", value: "заменять, замена" },
  { key: "subtitle", value: "субтитры или подзаголовок" },
  { key: "subtle", value: "тонкий, неуловимый" },
  { key: "subtract", value: "вычитать" },
  { key: "suburb", value: "пригород" },
  { key: "subvert", value: "подорвать" },
  { key: "subway", value: "метро (амер.)" },
  { key: "succeed", value: "достичь цели" },
  { key: "success", value: "успех" },
  { key: "succession", value: "последовательность, преемственность" },
  { key: "successor", value: "преемник" },
  { key: "succumb", value: "поддаться, не устоять" },
  { key: "suck", value: "сосать" },
  { key: "sudden", value: "внезапный" },
  { key: "sue", value: "предъявить иск" },
  { key: "suffer", value: "страдать" },
  { key: "suffice", value: "хватать, быть достаточным" },
  { key: "sufficient", value: "достаточный" },
  { key: "suffocate", value: "задыхаться" },
  { key: "suggest", value: "предлагать" },
  { key: "suit", value: ["костюм, комплект", "подходить, соответствовать"] },
  { key: "suitcase", value: "чемодан" },
  { key: "suite", value: "апартаменты, номер люкс" },
  { key: "sulfur (sulphur)", value: "сера" },
  { key: "sum", value: "сумма, суммировать" },
  { key: "sum up", value: "подытожить" },
  { key: "summary", value: "сводка, конспект" },
  { key: "summit", value: "вершина, верх" },
  { key: "summon", value: "вызывать" },
  { key: "sunset", value: "закат солнца" },
  { key: "superb", value: "превосходный" },
  { key: "superficial", value: "поверхностный" },
  { key: "superintendent", value: "управляющий, начальник" },
  { key: "superior", value: "высший, превосходящий" },
  { key: "supervise", value: "надзирать, контролировать" },
  { key: "supplement", value: "дополнение, дополнять" },
  { key: "supply", value: ["поставлять, поставка", "предложение"] },
  { key: "support", value: "поддерживать" },
  { key: "suppose", value: "полагать" },
  { key: "suppress", value: "подавлять, удерживать" },
  { key: "supreme", value: "высший,  верховный" },
  { key: "sure", value: "уверенный" },
  { key: "surf", value: "прибой" },
  { key: "surface", value: "поверхность" },
  { key: "surge", value: "волна, всплеск, вздыматься" },
  { key: "surgery", value: "хирургия, операция" },
  { key: "surpass", value: "превзойти" },
  { key: "surplus", value: "избыток, излишек (экон.)" },
  { key: "surprise", value: "удивлять, удивление" },
  { key: "surrender", value: "сдаваться, капитулировать" },
  { key: "surround", value: "окружать" },
  { key: "surveillance", value: "наблюдение" },
  { key: "survey", value: "обзор, исследование" },
  { key: "survive", value: "выжить" },
  { key: "susceptible", value: "восприимчивый, подверженный" },
  { key: "suspect", value: "подозревать, подозреваемый" },
  { key: "suspend", value: "приостановить, подвесить" },
  { key: "suspicious", value: "подозрительный" },
  { key: "sustain", value: "поддерживать" },
  { key: "swallow", value: "проглатывать, глоток" },
  { key: "swamp", value: "болото, топь" },
  { key: "swan", value: "лебедь" },
  { key: "swap", value: "менять, обмен" },
  { key: "swarm", value: "рой, роиться, толпиться" },
  { key: "sway", value: "раскачивать" },
  { key: "swear", value: ["клясться", "ругаться"] },
  { key: "sweat", value: "пот, потеть" },
  { key: "sweep", value: "размах, охват" },
  { key: "sweep (swept, swept)", value: "подметать" },
  { key: "sweetheart", value: "возлюбленный (ая), милый" },
  { key: "swell (swelled, swollen)", value: "раздуваться, распухать" },
  { key: "swift", value: "быстрый, скорый" },
  { key: "swing (swung, swung)", value: "качать, махать" },
  { key: "swirl", value: "кружить, вихрь, водоворот" },
  { key: "switch", value: "переключать, переключатель" },
  { key: "swoop", value: "кинуться, напасть" },
  { key: "sword", value: "меч" },
  { key: "syllable", value: "слог" },
  { key: "symbol", value: "символ" },
  { key: "sympathy", value: "сочуствие" },
  { key: "syringe", value: "шприц" },
]
