import { TDictionaryItem } from "../types"
export const t_arr: TDictionaryItem[] = [
  { key: "table", value: "таблица" },
  { key: "tablet", value: "плитка, пластина" },
  { key: "tack", value: ["канцелярская кнопка, гвоздик", "курс, линия поведения"] },
  { key: "tackle", value: ["принадлежности, снаряжение", "взяться за что-л."] },
  { key: "tag", value: "этикетка, ярлык" },
  { key: "tail", value: "хвост" },
  { key: "tailor", value: "портной, кроить" },
  { key: "taint", value: "загрязнить, испортить" },
  { key: "take", value: "воспринимать" },
  { key: "take a look", value: "взглянуть" },
  { key: "take a walk", value: "прогуляться" },
  { key: "take aback", value: "ошеломить" },
  { key: "take advantage of", value: "воспользоваться" },
  { key: "take after", value: "быть в (родителей)" },
  { key: "take apart", value: "разбирать" },
  { key: "take away", value: "отнять" },
  { key: "take care", value: "позаботиться, заняться" },
  { key: "take down", value: "записать" },
  { key: "take in", value: "понять, вникнуть" },
  { key: "take off", value: ["снять", "взлететь"] },
  { key: "take on", value: ["соревноваться, столкнуться", "набрать (напр. рабочих)"] },
  { key: "take over", value: "принять обязанности" },
  { key: "take part", value: "принимать участие" },
  { key: "take place", value: "происходить, бывать" },
  { key: "take up", value: "заняться чем-либо" },
  { key: "talk into", value: "уговорить" },
  { key: "talk over", value: "обговорить" },
  { key: "talk smb out", value: "отговорить" },
  { key: "tall", value: "высокий (чел)" },
  { key: "tally", value: "подсчитывать, подсчёт, итог" },
  { key: "tame", value: "ручной, приручать" },
  { key: "tan", value: "загар, загорать" },
  { key: "tangible", value: "осязаемый" },
  { key: "tangle", value: "запутывать" },
  { key: "tank", value: "бак" },
  { key: "tap", value: ["стучать", "кран"] },
  { key: "tape", value: "лента, записывать на ленту" },
  { key: "tar", value: "смола" },
  { key: "target", value: "цель, мишень" },
  { key: "tart", value: "пирог, обычно фруктовый" },
  { key: "task", value: "задание, задача" },
  { key: "taste", value: "вкус, иметь вкус" },
  { key: "tattered", value: "оборванный" },
  { key: "taunt", value: "насмехаться, насмешка" },
  { key: "tax", value: "налог" },
  { key: "team", value: "команда, бригада" },
  { key: "tear", value: "слеза" },
  { key: "tear (tore, torn)", value: "рвать" },
  { key: "tease", value: "дразнить" },
  { key: "tedious", value: "утомительный, нудный" },
  { key: "teenage", value: "возраста 1-19" },
  { key: "tell apart", value: "различать" },
  { key: "tell from", value: "отличить" },
  { key: "tell off", value: "ругать" },
  { key: "tell on", value: "донести на кого-то" },
  { key: "temper", value: "характер" },
  { key: "temple", value: ["храм", "висок"] },
  { key: "temporary", value: "временный" },
  { key: "tempt", value: "искушать" },
  { key: "tenant", value: "арендатор" },
  { key: "tend", value: ["иметь склонность", "ухаживать"] },
  { key: "tender", value: "нежный" },
  { key: "tense", value: "напряжённый, напрягать" },
  { key: "tent", value: "палатка, шатёр" },
  { key: "tentative", value: "пробный, экспериментальный" },
  { key: "term", value: ["срок, период", "термин"] },
  { key: "terminal", value: "конечный, заключительный" },
  { key: "terminate", value: "прекратить, завершить (офиц.)" },
  { key: "terms", value: ["отношения", "условия, соглашение"] },
  { key: "terrain", value: "местность" },
  { key: "terrible", value: "ужасный" },
  { key: "terrify", value: "устрашать" },
  { key: "terror", value: "ужас" },
  { key: "testament", value: "завет, завещание" },
  { key: "testify", value: "свидетельствовать" },
  { key: "testimony", value: "показание, свидетельство" },
  { key: "text", value: "писать (сообщение)" },
  { key: "thank", value: "благодарить" },
  { key: "thaw", value: "оттепель, оттаивать" },
  { key: "theater (theatre)", value: "театр" },
  { key: "theft", value: "кража" },
  { key: "theme", value: "тема" },
  { key: "thereafter", value: "впоследствии" },
  { key: "thereby", value: "тем самым" },
  { key: "therefore", value: "следовательно" },
  { key: "thermal", value: "тепловой" },
  { key: "thick", value: ["толстый", "густой"] },
  { key: "thief (pl: thieves)", value: "вор" },
  { key: "thigh", value: "бедро" },
  { key: "thin", value: "тонкий, худой" },
  { key: "think over", value: "обдумать" },
  { key: "thirst", value: "жажда" },
  { key: "thorn", value: "шип, колючка" },
  { key: "thorough", value: "основательный, полный" },
  { key: "though (even though)", value: "хотя" },
  { key: "thought", value: "мысль" },
  { key: "thread", value: "нить" },
  { key: "threat", value: "угроза" },
  { key: "threshold", value: "порог" },
  { key: "thrift", value: "бережливость" },
  { key: "thrill", value: "трепет, дрожь, дрожать" },
  { key: "thrive", value: "процветать, преуспевать" },
  { key: "throat", value: "горло" },
  { key: "throng", value: "толпа, толчея, толпиться" },
  { key: "throw (threw, thrown)", value: "бросать" },
  { key: "throw away", value: "выбрасывать" },
  { key: "throw up", value: "блевануть" },
  { key: "thrust", value: "сунуть, пихнуть (быстро)" },
  { key: "thud", value: "глухой удар" },
  { key: "thug", value: "бандит, головорез" },
  { key: "thumb", value: "большой палец" },
  { key: "thump", value: "колотить" },
  { key: "thunder", value: "гром" },
  { key: "thus", value: "таким образом, поэтому" },
  { key: "thwart", value: "помешать, сорвать" },
  { key: "tick", value: ["галочка, поставить галочку", "клещ"] },
  { key: "ticket", value: "билет, талон" },
  { key: "tickle", value: "щекотать" },
  { key: "tide", value: "волна, поток, прилив" },
  { key: "tidy", value: "опрятный, аккуратный" },
  { key: "tie", value: ["галстук, завязка и т.п.", "связывать, завязывать"] },
  { key: "tied up", value: "занятый" },
  { key: "tier", value: "ярус" },
  { key: "tight", value: "тугой, тесный" },
  { key: "tile", value: "плитка, черепица" },
  { key: "tilt", value: "наклонять, наклон" },
  { key: "timber", value: "древесина, лесоматериалы" },
  { key: "timely", value: "своевременный" },
  { key: "timetable", value: "расписание" },
  { key: "timid", value: "робкий, пугливый" },
  { key: "tin", value: "олово или жесть" },
  { key: "tinker with", value: "возиться, пытаться сделать" },
  { key: "tint", value: "оттенок" },
  { key: "tiny", value: "крошечный" },
  { key: "tip", value: ["кончик, верхушка", "совет, рекомендация"] },
  { key: "tip (tips)", value: "чаевые" },
  { key: "tip smb off", value: "предупредить, секретно сообщить" },
  { key: "tire (tyre)", value: "шина" },
  { key: "tired", value: "усталый" },
  { key: "tissue", value: ["ткань", "бумажная салфетка"] },
  { key: "title", value: "заголовок" },
  { key: "toddler", value: "малыш (1- года)" },
  { key: "toe", value: "палец (ноги)" },
  { key: "toil", value: "тяжело трудиться" },
  { key: "token", value: "знак, признак, маркер" },
  { key: "tolerate", value: "терпеть" },
  { key: "toll", value: "плата, пошлина, тариф" },
  { key: "tomb", value: "надгробие, склеп" },
  { key: "tongue", value: "язык" },
  { key: "tool", value: "инструмент" },
  { key: "tooth (pl: teeth)", value: "зуб" },
  { key: "topic", value: "тема, предмет обсуждения" },
  { key: "topple", value: "опрокинуть(ся)" },
  { key: "tops", value: "самое большое" },
  { key: "torch", value: "факел, горелка" },
  { key: "torment", value: "мучение" },
  { key: "torture", value: "пытка, мучить" },
  { key: "toss", value: "бросать" },
  { key: "total", value: "полный, всеобщий" },
  { key: "touch", value: ["связь, контакт", "касаться, прикосновение"] },
  { key: "tough", value: "жёсткий, крепкий, тяжёлый" },
  { key: "tournament", value: "турнир" },
  { key: "tout", value: "рекламировать, нявязывать" },
  { key: "tow", value: "буксир или эвакуатор, буксировать" },
  { key: "toward (towards)", value: "по направлению к" },
  { key: "towel", value: "полотенце" },
  { key: "tower", value: "башня, возвышаться" },
  { key: "toy with", value: "подумывать о ч-л" },
  { key: "trace", value: "след, отслеживать" },
  { key: "track", value: "след, выслеживать" },
  { key: "track down", value: "разыскать, отследить" },
  { key: "trade", value: "торговля, торговый" },
  { key: "traffic light", value: "светофор" },
  { key: "trail", value: "след, тропа" },
  { key: "train", value: ["поезд", "тренировать"] },
  { key: "trait", value: "черта, характеристика" },
  { key: "traitor", value: "изменник" },
  { key: "tram", value: "трамвай" },
  { key: "tramp", value: "бродяга" },
  { key: "tranquil", value: "спокойный" },
  { key: "transcend", value: "преодолеть (пределы)" },
  { key: "transcript", value: "расшифровка, текст" },
  { key: "transfer", value: "перевести, перевод" },
  { key: "transition", value: "переход" },
  { key: "transmit", value: "передавать, переносить" },
  { key: "transparent", value: "прозрачный" },
  { key: "trap", value: "ловушка, ловить" },
  { key: "trash", value: "мусор" },
  { key: "tray", value: "лоток, поднос, поддон" },
  { key: "treachery", value: "предательство, вероломство" },
  { key: "tread", value: "ступать, шагать" },
  { key: "treasure", value: "сокровище" },
  { key: "treat", value: "обращаться, иметь дело" },
  { key: "treaty", value: "договор (между гос-вами)" },
  { key: "trek", value: "поход, переход" },
  { key: "tremble", value: "дрожать" },
  { key: "tremendous", value: "громадный, страшный" },
  { key: "trench", value: "траншея" },
  { key: "trial", value: ["испытание, пробный", "судебный процесс"] },
  { key: "triangle", value: "треугольник" },
  { key: "tribe", value: "племя" },
  { key: "tribute", value: "дань" },
  { key: "trick", value: "трюк, фокус, уловка" },
  { key: "trickle", value: "струйка, капать, сочиться" },
  { key: "trigger", value: "спусковой крючок" },
  { key: "trim", value: "подстригать, обрезать, ровнять" },
  { key: "trip", value: "поездка" },
  { key: "triple", value: "тройной" },
  { key: "troop", value: "отряд" },
  { key: "trophy", value: "трофей, приз" },
  { key: "troublesome", value: "хлопотный, беспокойный" },
  { key: "trousers", value: "брюки" },
  { key: "trout", value: "форель" },
  { key: "truck", value: "грузовик" },
  { key: "trump", value: "козырь" },
  { key: "trumpet", value: "труба" },
  { key: "trunk", value: ["багажник", "ствол дерева", "чемодан, сундук"] },
  { key: "trust", value: "доверять" },
  { key: "try on", value: "примерить" },
  { key: "try out", value: "испытать" },
  { key: "tub", value: "ванна, бадья" },
  { key: "tube", value: ["тюбик", "труба", "метро (в Лондоне)"] },
  { key: "tuck", value: "подоткнуть, заправить и т. д." },
  { key: "tug", value: "тянуть, рывок" },
  { key: "tuition", value: "обучение, плата за обучение" },
  { key: "tumble", value: "перевернуться, кувыркнуться" },
  { key: "tumor (tumour)", value: "опухоль" },
  { key: "tuna", value: "тунец" },
  { key: "tune", value: ["мелодия, мотив", "настраивать"] },
  { key: "turkey", value: "индейка, индюк" },
  { key: "turmoil", value: "смятение, беспорядок" },
  { key: "turn", value: "очередь, смена" },
  { key: "turn away", value: "не пустить" },
  { key: "turn down", value: "отказаться от предложения" },
  { key: "turn into", value: "превращать (ся)" },
  { key: "turn off", value: ["выключить", "свернуть (с дороги)"] },
  { key: "turn on", value: ["включить", "заводить, возбуждать"] },
  { key: "turn out", value: "оказаться" },
  { key: "turn over", value: "перевернуть" },
  { key: "turn up", value: "сделать погромче" },
  { key: "turnover", value: "оборот (экон.)" },
  { key: "turtle", value: "черепаха" },
  { key: "tutor", value: "репетитор, преподаватель" },
  { key: "tweak", value: "доделать, настроить (разг.)" },
  { key: "twig", value: "прут, веточка" },
  { key: "twilight", value: "сумерки" },
  { key: "twin", value: "близнец" },
  { key: "twinkle", value: "блеск, мерцание" },
  { key: "twirl", value: "вертеть" },
  { key: "twist", value: "скручивать" },
  { key: "twitch", value: "дёргаться" },
  { key: "type", value: "печатать, набирать текст" },
]
