import { TDictionaryItem } from "../types"
export const u_arr: TDictionaryItem[] = [
  { key: "ugly", value: "безобразный, уродливый" },
  { key: "ultimate", value: "окончательный, конечный" },
  { key: "umbrella", value: "зонтик" },
  { key: "unanimous", value: "единогласный" },
  { key: "unbelievable", value: "невероятный" },
  { key: "uncle", value: "дядя" },
  { key: "undergo", value: "пройти через, подвергнуться" },
  { key: "underground", value: "подземный" },
  { key: "underlie", value: "лежать в основе" },
  { key: "underline", value: "подчеркивнуть" },
  { key: "undermine", value: "подрывать" },
  { key: "underneath", value: "под" },
  { key: "underpants", value: "трусы" },
  { key: "underscore", value: "нижнее подчеркивание" },
  { key: "undertake", value: "предпринимать" },
  { key: "underwear", value: "нижнее белье" },
  { key: "undo", value: "расстёгнуть, развязать, открыть" },
  { key: "union", value: "союз" },
  { key: "unique", value: "уникальный" },
  { key: "unit", value: "единица, элемент" },
  { key: "unite", value: "объединять" },
  { key: "universe", value: "вселенная" },
  { key: "unless", value: "если не" },
  { key: "upcoming", value: "предстоящий, наступающий" },
  { key: "update", value: "обновлять, обновление" },
  { key: "uphill", value: "в гору" },
  { key: "uphold", value: "соблюдать, поддерживать" },
  { key: "upper", value: "верхний" },
  { key: "upright", value: ["вертикальный, стоячий", "честный"] },
  { key: "uprising (rising)", value: "восстание" },
  { key: "upset", value: "расстраивать, расстроенный" },
  { key: "upside down", value: "вверх ногами" },
  { key: "up-to-date", value: "современный, актуальный" },
  { key: "upwards (upward)", value: "вверх" },
  { key: "urban", value: "городской" },
  { key: "urge", value: "побуждать, гнать и т.д." },
  { key: "urgent", value: "срочный" },
  { key: "usage", value: "применение" },
  { key: "used to", value: "когда-то бывало" },
  { key: "useful", value: "полезный" },
  { key: "utility", value: "полезность" },
  { key: "utilize", value: "использовать" },
  { key: "utter", value: ["полный, абсолютный", "издать, произнести"] },
]
