import { TDictionaryItem } from "../types"
export const v_arr: TDictionaryItem[] = [
  { key: "vacation", value: "отпуск, каникулы" },
  { key: "vague", value: "смутный" },
  { key: "vain", value: ["тщеславный, самолюбивый", "напрасный, безрезультатный"] },
  { key: "valid", value: "действительный" },
  { key: "valley", value: "долина" },
  { key: "value", value: "ценность, оценивать" },
  { key: "valve", value: "задвижка, вентиль" },
  { key: "van", value: "фургон" },
  { key: "vanish", value: "исчезнуть" },
  { key: "vapor", value: "пар" },
  { key: "variety", value: "разнообразие, множество" },
  { key: "various", value: "разнообразный" },
  { key: "varnish", value: "лак, лакировать" },
  { key: "vary", value: "меняться, разниться" },
  { key: "vase", value: "ваза" },
  { key: "vast", value: "просторный, простор" },
  { key: "vault", value: ["свод, небосвод", "хранилище, об. в подвале"] },
  { key: "veer", value: "резко свернуть" },
  { key: "vegetable", value: "овощ" },
  { key: "vegetation", value: "растительность" },
  { key: "vehicle", value: "транспортное средство" },
  { key: "veil", value: "вуаль, закрывать" },
  { key: "vein", value: "вена" },
  { key: "velocity", value: "быстрота перемещения" },
  { key: "velvet", value: "бархат" },
  { key: "vendor", value: "продавец, торговец" },
  { key: "vengeance", value: "отмщение" },
  { key: "vent", value: "выход, отдушина" },
  { key: "venture", value: "авантюра, предприятие, решиться" },
  { key: "verb", value: "глагол" },
  { key: "verge", value: ["обочина", "грань, предел"] },
  { key: "verify", value: "проверить" },
  { key: "versatile", value: "универсальный, разносторонний" },
  { key: "verse", value: "стих" },
  { key: "vessel", value: ["сосуд", "судно"] },
  { key: "vest", value: "жилет" },
  { key: "via", value: "через" },
  { key: "viable", value: "жизнеспособный" },
  { key: "vice", value: "порок, недостаток" },
  { key: "vice versa", value: "(и) наоборот" },
  { key: "vicinity", value: "окрестность, близость" },
  { key: "vicious", value: "злобный, жестокий" },
  { key: "victim", value: "жертва" },
  { key: "view", value: "вид, взгляд" },
  { key: "vigil", value: "дежурство, бдение" },
  { key: "vigor", value: "сила, энергия, здоровье" },
  { key: "village", value: "деревня" },
  { key: "villain", value: "негодяй" },
  { key: "vine", value: "виноград (растение)" },
  { key: "vinegar", value: "уксус" },
  { key: "violate", value: "нарушать" },
  { key: "violent", value: "яростный, жестокий" },
  { key: "violet", value: "фиолетовый" },
  { key: "violin", value: "скрипка" },
  { key: "virgin", value: "девственница, дева" },
  { key: "virtual", value: "действительный, фактический" },
  { key: "virtue", value: "достоинство, добродетель" },
  { key: "visible", value: "видимый" },
  { key: "vision", value: "зрение или видение" },
  { key: "visit", value: "посетить, посещение" },
  { key: "vital", value: "жизненный, жизненно важный" },
  { key: "vivid", value: "яркий" },
  { key: "vocabulary", value: "словарный запас" },
  { key: "vocation", value: "призвание или профессия" },
  { key: "void", value: "недействительный, пустой" },
  { key: "volatile", value: "изменчивый, нестабильный" },
  { key: "volume", value: ["громкость", "том, книга", "объём"] },
  { key: "voluntary", value: "добровольный" },
  { key: "vomit", value: "рвота, блевать" },
  { key: "vote", value: "голосовать" },
  { key: "vow", value: "клятва, торжественное обещание" },
  { key: "voyage", value: "путешествие, рейс" },
  { key: "vulnerable", value: "уязвимый, чувствительный" },
]
