import { TDictionaryItem } from "../types"
export const w_arr: TDictionaryItem[] = [
  { key: "wad", value: "комок или пачка (денег)" },
  { key: "wade", value: "брод, переходить вброд" },
  { key: "waffle", value: "вафля, вафельный" },
  { key: "wag", value: "махать, вилять" },
  { key: "wage", value: "заработок, оплата" },
  { key: "wail", value: "вопить, вопль" },
  { key: "waist", value: "талия" },
  { key: "waiter", value: "официант" },
  { key: "waive", value: "отказаться, воздержаться от" },
  { key: "wake (up)", value: "просыпаться или будить" },
  { key: "wallet", value: "бумажник" },
  { key: "wallpaper", value: "обои" },
  { key: "walnut", value: "грецкий орех" },
  { key: "wander", value: "бродить, блуждать" },
  { key: "wane", value: "убывать" },
  { key: "ward", value: ["палата, отделение, камера", "округ, район"] },
  { key: "ward off", value: "предотвратить, отогнать" },
  { key: "warden", value: "смотритель, надзиратель" },
  { key: "wardrobe", value: "шкаф, гардероб" },
  { key: "warehouse", value: "склад" },
  { key: "warfare", value: "военные действия" },
  { key: "warmth", value: "тепло" },
  { key: "warn", value: "предостерегать" },
  { key: "warp", value: "деформироваться" },
  { key: "warrant", value: "гарантировать, ручаться" },
  { key: "warrior", value: "воин" },
  { key: "wary", value: "осторожный, настороженный" },
  { key: "wash down", value: "запивать" },
  { key: "wash up", value: ["умыться", "помыть посуду"] },
  { key: "waste", value: ["отходы, обрезки, потери и т.п.", "тратить (впустую)"] },
  { key: "watch", value: "часы (наручные)" },
  { key: "watchful", value: "бдительный" },
  { key: "water down", value: "разбавить, ослабить" },
  { key: "watercolor", value: "акварель" },
  { key: "waterfall", value: "водопад" },
  { key: "wave", value: ["волна", "махать, колебаться"] },
  { key: "waver", value: "дрогнуть" },
  { key: "wax", value: "воск" },
  { key: "way", value: "способ" },
  { key: "weak", value: "слабый" },
  { key: "wealth", value: "богатство" },
  { key: "weapon", value: "оружие" },
  { key: "wear", value: "надевать, носить" },
  { key: "wear off", value: "сойти на нет, выветриться" },
  { key: "wear out", value: "измотать, истрепать" },
  { key: "weary", value: "утомленный" },
  { key: "weave", value: "плести, ткать" },
  { key: "wedding", value: "свадьба" },
  { key: "wedge", value: "клин, клиновидный" },
  { key: "weed", value: "сорняк, пропалывать" },
  { key: "weep", value: "рыдать" },
  { key: "weigh", value: "весить" },
  { key: "weight", value: "вес" },
  { key: "weird", value: "нереальный, странный" },
  { key: "welcome", value: "желанный, приятный" },
  { key: "weld", value: "сварка, сваривать" },
  { key: "welfare", value: ["пособие, мат. помощь", "благополучие"] },
  { key: "well", value: "колодец" },
  { key: "well-being", value: "благополучие" },
  { key: "well-off", value: "обеспеченный" },
  { key: "west", value: "запад" },
  { key: "wet", value: "мокрый, мочить" },
  { key: "whack", value: "удар, сильно бить" },
  { key: "whale", value: "кит" },
  { key: "whatsoever", value: "совсем (не)" },
  { key: "wheat", value: "пшеница" },
  { key: "wheel", value: "колесо" },
  { key: "whereabouts", value: "местонахождение" },
  { key: "whereas", value: "тогда как" },
  { key: "whereby", value: "посредством чего" },
  { key: "whether", value: "ли" },
  { key: "whim", value: "каприз, прихоть" },
  { key: "whine", value: "ныть, скулить" },
  { key: "whip", value: "кнут, хлестать" },
  { key: "whirl", value: "вихрь, кружиться" },
  { key: "whisk", value: "сделать быстрое движение" },
  { key: "whisper", value: "шептать" },
  { key: "whistle", value: "свист, свистеть, свисток" },
  { key: "whiz", value: ["ловкач, умелец (в области)", "просвистеть, пронестись"] },
  { key: "whole", value: "весь, целый" },
  { key: "wholesale", value: "опт" },
  { key: "whore", value: "шлюха" },
  { key: "wicked", value: "злобный, безнравственный" },
  { key: "wide", value: "широкий, просторный" },
  { key: "widespread", value: "распространенный" },
  { key: "widow", value: "вдова" },
  { key: "width", value: "ширина" },
  { key: "wield", value: "владеть, управляться" },
  { key: "wiggle", value: "шевелить" },
  { key: "wilderness", value: "глушь, дикая местность" },
  { key: "wildlife", value: "дикая природа" },
  { key: "will", value: "воля, желание" },
  { key: "willow", value: "ива" },
  { key: "wince", value: "поморщиться, поёжиться" },
  { key: "wind (wound, wound)", value: "наматывать, виться, петлять" },
  { key: "wind up", value: "заканчивать" },
  { key: "windowpane", value: "оконное стекло" },
  { key: "wine", value: "вино" },
  { key: "wink", value: "подмигивать" },
  { key: "wipe", value: "вытирать, салфетка" },
  { key: "wipe out", value: "уничтожить" },
  { key: "wire", value: "проволока, провод" },
  { key: "wise", value: "мудрый" },
  { key: "wit", value: "ум, остроумие" },
  { key: "witch", value: "ведьма" },
  { key: "withdraw", value: "отводить, убирать" },
  { key: "wither", value: "увянуть, засохнуть" },
  { key: "withhold", value: "утаивать, удерживать" },
  { key: "within", value: ["в течение", "в пределах, внутри"] },
  { key: "withstand", value: "выдерживать" },
  { key: "witness", value: "свидетель" },
  { key: "wizard", value: "волшебник" },
  { key: "wobble", value: "качаться, шататься" },
  { key: "woe", value: "горе" },
  { key: "wonder", value: ["удивление, удивляться", "хотеть знать"] },
  { key: "woo", value: "ухаживать, добиваться" },
  { key: "wood", value: "древесина, лес" },
  { key: "wool", value: "шерсть, шерстяной" },
  { key: "work out", value: ["тренироваться", "получиться, сработать"] },
  { key: "workshop", value: "мастерская, студия" },
  { key: "worldwide", value: "всемирный" },
  { key: "worm", value: "червь" },
  { key: "worry", value: "волновать (ся)" },
  { key: "worsen", value: "ухудшать" },
  { key: "worship", value: "почитать, поклоняться" },
  { key: "worth", value: "стоимость, стоящий" },
  { key: "worthwhile", value: "стоящий" },
  { key: "wound", value: "рана, ранить" },
  { key: "wrap", value: "заворачивать" },
  { key: "wrath", value: "ярость" },
  { key: "wreath", value: "венок" },
  { key: "wreck", value: "разрушать, крушение, развалина" },
  { key: "wrench", value: "гаечный ключ" },
  { key: "wrestle", value: "бороться" },
  { key: "wretched", value: "жалкий, несчастный" },
  { key: "wrinkle", value: "морщина, сморщиваться" },
  { key: "wrist", value: "запястье" },
  { key: "write out", value: "выписать (документ)" },
  { key: "wrong", value: "не тот" },
  { key: "wrongdoing", value: "проступок, правонарушение" },
]
